import type { AnyColumn } from "drizzle-orm";
import {
  aiCreditReservations,
  aiCreditTransactions,
  alumniProfiles,
  assessmentAttempts,
  attendance,
  backgroundVerifications,
  biometricLogs,
  certifications,
  compOffBalances,
  employeeDevices,
  employeeSalaryProfiles,
  employeeShiftAssignments,
  employeeSkills,
  enpsScores,
  eventAttendees,
  feedbackRequests,
  goals,
  helpdeskTickets,
  hrAccommodationRequests,
  hrAccessProvisioning,
  hrArrearsAdjustments,
  hrBadgeAwards,
  hrBenefitEnrollments,
  hrCommunityMembers,
  hrCompRecommendations,
  hrContracts,
  hrDependents,
  hrDeviceEmployeeMappings,
  hrEffectiveDatedChanges,
  hrEmergencyResponses,
  hrEmployeeSensitiveFields,
  hrEmploymentHistory,
  hrEquityGrants,
  hrInsuranceClaims,
  hrLeaveLedger,
  hrMoodCheckins,
  hrPayrollAdjustments,
  hrPayrollInputSnapshots,
  hrPeople,
  hrPollVotes,
  hrProbationReviews,
  hrRewardPointsLedger,
  hrTravelVisitLogs,
  hrWellnessCheckins,
  hrWorkAuthorizations,
  kbChatConversations,
  kbChatMessages,
  leaveBalances,
  leaveRequests,
  meetingAttendees,
  meetingStandupEntries,
  notificationConsentEvents,
  notificationConsents,
  onboardingSteps,
  onboardingTasks,
  overtimeRequests,
  payrollBankBatchItems,
  payrollExceptions,
  payrollInputs,
  payrollRunEmployees,
  payslipPublications,
  performanceImprovementPlans,
  performanceReviews,
  projectMembers,
  resignations,
  rosterEntries,
  signRecipients,
  surveyResponses,
  taxDeclarations,
  terminations,
  timesheetExceptions,
  timesheetPeriods,
  timesheetRates,
  timesheets,
  timerSessions,
  travelRequests,
  wfhRequests,
} from "../../db/schema";
import type {
  EmploymentScopedAdapter,
  MembershipScopedAdapter,
  SubjectScopedAdapter,
  SubjectScopedTable,
} from "./gdpr-export-types";

const SUBJECT_SCOPED_TABLE_DEFINITIONS: ReadonlyArray<
  readonly [string, SubjectScopedTable, AnyColumn]
> = [
  ["ai_credit_reservations", aiCreditReservations, aiCreditReservations.userId],
  ["ai_credit_transactions", aiCreditTransactions, aiCreditTransactions.userId],
  ["attendance", attendance, attendance.userId],
  ["hr_people", hrPeople, hrPeople.userId],
  ["biometric_logs", biometricLogs, biometricLogs.userId],
  ["meeting_standup_entries", meetingStandupEntries, meetingStandupEntries.userId],
  ["comp_off_balances", compOffBalances, compOffBalances.userId],
  ["employee_devices", employeeDevices, employeeDevices.userId],
  ["employee_salary_profiles", employeeSalaryProfiles, employeeSalaryProfiles.userId],
  ["employee_shift_assignments", employeeShiftAssignments, employeeShiftAssignments.userId],
  ["enps_scores", enpsScores, enpsScores.userId],
  ["feedback_requests", feedbackRequests, feedbackRequests.subjectUserId],
  ["hr_arrears_adjustments", hrArrearsAdjustments, hrArrearsAdjustments.userId],
  ["hr_accommodation_requests", hrAccommodationRequests, hrAccommodationRequests.userId],
  ["hr_access_provisioning", hrAccessProvisioning, hrAccessProvisioning.userId],
  ["hr_badge_awards", hrBadgeAwards, hrBadgeAwards.userId],
  ["hr_benefit_enrollments", hrBenefitEnrollments, hrBenefitEnrollments.userId],
  ["hr_community_members", hrCommunityMembers, hrCommunityMembers.userId],
  ["hr_comp_recommendations", hrCompRecommendations, hrCompRecommendations.userId],
  ["hr_dependents", hrDependents, hrDependents.userId],
  ["hr_device_employee_mappings", hrDeviceEmployeeMappings, hrDeviceEmployeeMappings.userId],
  ["hr_emergency_responses", hrEmergencyResponses, hrEmergencyResponses.userId],
  ["hr_equity_grants", hrEquityGrants, hrEquityGrants.userId],
  ["hr_insurance_claims", hrInsuranceClaims, hrInsuranceClaims.userId],
  ["hr_leave_ledger", hrLeaveLedger, hrLeaveLedger.userId],
  ["hr_mood_checkins", hrMoodCheckins, hrMoodCheckins.userId],
  ["hr_payroll_adjustments", hrPayrollAdjustments, hrPayrollAdjustments.userId],
  ["hr_payroll_input_snapshots", hrPayrollInputSnapshots, hrPayrollInputSnapshots.userId],
  ["hr_poll_votes", hrPollVotes, hrPollVotes.userId],
  ["hr_reward_points_ledger", hrRewardPointsLedger, hrRewardPointsLedger.userId],
  ["hr_travel_visit_logs", hrTravelVisitLogs, hrTravelVisitLogs.userId],
  ["hr_wellness_checkins", hrWellnessCheckins, hrWellnessCheckins.userId],
  ["helpdesk_tickets", helpdeskTickets, helpdeskTickets.userId],
  ["leave_balances", leaveBalances, leaveBalances.userId],
  ["leave_requests", leaveRequests, leaveRequests.userId],
  ["notification_consent_events", notificationConsentEvents, notificationConsentEvents.userId],
  ["overtime_requests", overtimeRequests, overtimeRequests.userId],
  ["payroll_bank_batch_items", payrollBankBatchItems, payrollBankBatchItems.userId],
  ["payroll_exceptions", payrollExceptions, payrollExceptions.userId],
  ["payroll_inputs", payrollInputs, payrollInputs.userId],
  ["payroll_run_employees", payrollRunEmployees, payrollRunEmployees.userId],
  ["payslip_publications", payslipPublications, payslipPublications.userId],
  ["performance_improvement_plans", performanceImprovementPlans, performanceImprovementPlans.userId],
  ["performance_reviews", performanceReviews, performanceReviews.userId],
  ["goals", goals, goals.userId],
  ["employee_skills", employeeSkills, employeeSkills.userId],
  ["assessment_attempts", assessmentAttempts, assessmentAttempts.userId],
  ["roster_entries", rosterEntries, rosterEntries.userId],
  ["survey_responses", surveyResponses, surveyResponses.userId],
  ["tax_declarations", taxDeclarations, taxDeclarations.userId],
  ["travel_requests", travelRequests, travelRequests.userId],
  ["wfh_requests", wfhRequests, wfhRequests.userId],
  ["onboarding_steps", onboardingSteps, onboardingSteps.userId],
  ["onboarding_tasks", onboardingTasks, onboardingTasks.userId],
  ["resignations", resignations, resignations.userId],
  ["terminations", terminations, terminations.userId],
  ["alumni_profiles", alumniProfiles, alumniProfiles.userId],
  ["background_verifications", backgroundVerifications, backgroundVerifications.userId],
  ["certifications", certifications, certifications.userId],
];

export const SUBJECT_SCOPED_TABLES: readonly SubjectScopedAdapter[] =
  SUBJECT_SCOPED_TABLE_DEFINITIONS.map(([source, table, userColumn]) => ({
    source,
    table,
    userColumn,
  }));

const MEMBERSHIP_SCOPED_TABLE_DEFINITIONS: ReadonlyArray<
  readonly [string, SubjectScopedTable, AnyColumn]
> = [
  ["event_attendees", eventAttendees, eventAttendees.membershipId],
  ["kb_chat_conversations", kbChatConversations, kbChatConversations.userMembershipId],
  ["kb_chat_messages", kbChatMessages, kbChatMessages.userMembershipId],
  ["meeting_attendees", meetingAttendees, meetingAttendees.membershipId],
  ["notification_consents", notificationConsents, notificationConsents.membershipId],
  ["project_members", projectMembers, projectMembers.membershipId],
  ["sign_recipients", signRecipients, signRecipients.userMembershipId],
  ["timer_sessions", timerSessions, timerSessions.userMembershipId],
  ["timesheet_exceptions", timesheetExceptions, timesheetExceptions.userMembershipId],
  ["timesheet_periods", timesheetPeriods, timesheetPeriods.userMembershipId],
  ["timesheet_rates", timesheetRates, timesheetRates.userMembershipId],
  ["timesheets", timesheets, timesheets.userMembershipId],
];

export const MEMBERSHIP_SCOPED_TABLES: readonly MembershipScopedAdapter[] =
  MEMBERSHIP_SCOPED_TABLE_DEFINITIONS.map(([source, table, membershipColumn]) => ({
    source,
    table,
    membershipColumn,
  }));

const EMPLOYMENT_SCOPED_TABLE_DEFINITIONS: ReadonlyArray<
  readonly [string, SubjectScopedTable, AnyColumn]
> = [
  ["hr_contracts", hrContracts, hrContracts.employmentId],
  ["hr_effective_dated_changes", hrEffectiveDatedChanges, hrEffectiveDatedChanges.employmentId],
  ["hr_employee_sensitive_fields", hrEmployeeSensitiveFields, hrEmployeeSensitiveFields.employmentId],
  ["hr_employment_history", hrEmploymentHistory, hrEmploymentHistory.employmentId],
  ["hr_probation_reviews", hrProbationReviews, hrProbationReviews.employmentId],
  ["hr_work_authorizations", hrWorkAuthorizations, hrWorkAuthorizations.employmentId],
];

export const EMPLOYMENT_SCOPED_TABLES: readonly EmploymentScopedAdapter[] =
  EMPLOYMENT_SCOPED_TABLE_DEFINITIONS.map(([source, table, employmentColumn]) => ({
    source,
    table,
    employmentColumn,
  }));

export const GENERIC_GDPR_EXPORT_EXCLUDED_SOURCES = [
  "announcement_reads",
  "agent_tokens",
  "notification_digest_runs",
  "notification_suppression_rules",
  "onboarding_analytics_events",
  "onboarding_flow_sessions",
  "push_subscriptions",
  "user_integration_connections",
  "user_tour_progress",
] as const;

export const SUBJECT_SCOPED_GDPR_EXPORT_SOURCES = SUBJECT_SCOPED_TABLES.map(
  ({ source }) => source,
);

export const MEMBERSHIP_SCOPED_GDPR_EXPORT_SOURCES = MEMBERSHIP_SCOPED_TABLES.map(
  ({ source }) => source,
);

export const EMPLOYMENT_SCOPED_GDPR_EXPORT_SOURCES = EMPLOYMENT_SCOPED_TABLES.map(
  ({ source }) => source,
);

export const REQUIRED_GDPR_EXPORT_SOURCES = [
  "users",
  "organization_members",
  "hr_employments",
  "hr_reporting_lines",
  "hr_data_requests",
  "hr_legal_holds",
  "audit_logs",
  "hr_attendance_regularizations",
  "ai_chat_conversations",
  "ai_chat_messages",
  "ai_feedback",
  "ai_action_proposals",
  "ai_jobs",
  "ai_usage_logs",
  "chat_channel_members",
  "chat_messages",
  "chat_message_reactions",
  "chat_attachments",
  "chat_pinned_messages",
  "chat_saved_messages",
  "chat_reply_reminders",
  "mail_message_metadata",
  "notifications",
  "notification_read_watermarks",
  "notification_deliveries",
  "notification_preferences",
  "documents",
  "policy_acknowledgments",
  "onboarding_documents",
  "expenses",
  "reimbursements",
  "salary_loans",
  "bonuses",
  "fnf_settlements",
  "asset_returns",
  ...SUBJECT_SCOPED_GDPR_EXPORT_SOURCES,
  ...MEMBERSHIP_SCOPED_GDPR_EXPORT_SOURCES,
  ...EMPLOYMENT_SCOPED_GDPR_EXPORT_SOURCES,
] as const;

export const GDPR_EXPORT_SOURCE_ADAPTERS = new Set<string>([
  ...REQUIRED_GDPR_EXPORT_SOURCES,
]);
