export const AI_FEATURE_COSTS: Readonly<Record<string, number>> = {
  "crm.score-lead": 1,
  "crm.predict-deal": 1,
  "crm.churn-risk": 1,
  "crm.next-action": 1,
  "crm.account-summary": 1,
  "crm.meeting-prep": 1,
  "crm.nl-search": 1,
  "crm.enrich-lead": 2,
  "crm.generate-email": 1,
  "crm.objection-handler": 1,
  "crm.sentiment": 1,
  "crm.summarize": 1,
  "crm.report-narrator": 1,
  "crm.prioritize-tasks": 1,
  "crm.copilot.summary": 1,
  "crm.copilot.next-best-actions": 1,
  "crm.copilot.email-draft": 1,
  "crm.copilot.notes": 1,
  "crm.copilot.objection": 1,
  "crm.copilot.duplicates": 1,
  "hr.attrition-risk": 1,
  "hr.generate-review": 2,
  "hr.generate-jd": 1,
  "hr.score-candidate": 1,
  "hr.helpdesk-reply": 1,
  "pm.summary": 1,
  "pm.risks": 1,
  "pm.client-update": 1,
  "pm.plan": 2,
  "pm.extract-tasks": 1,
  "pm.ask": 1,
  "ticket.summarize": 1,
  "ticket.improve-description": 1,
  "ticket.suggest-subtasks": 1,
  "support.analysis": 1,
  "support.reply": 1,
  "support.macro": 1,
  "support.translate": 1,
  "support.handoff": 1,
  "support.root-cause": 2,
  "kb.ask": 1,
  "kb.public-ask": 1,
  "chat.message": 1,
  "feedbucket.analyze": 5,
  "feedbucket.assist": 5,
  "inv.insight-explain": 1,
};

export function getFeatureCost(feature: string): number {
  return AI_FEATURE_COSTS[feature] ?? 1;
}
