/**
 * Every table that holds personal data, and how a person is scoped within it.
 *
 * Phase 3, ticket 17.
 *
 * The ticket asks for erasure "across every region and generation". What was
 * there before was a `runAcrossRegions` helper with no callers, no table names
 * and no database import, plus `scripts/purge-user.mjs` — the only working
 * erasure, which finds rows by three predicates: `org_id = ANY(orgs the subject
 * OWNS)`, a single-column foreign key to `public.users`, and a column literally
 * named `email`.
 *
 * Measured against the schema, that misses most of the surface. This file is the
 * measurement: 154 tables carry personal data, of which 138 are scoped by
 * `org_id`, 10 by `organization_id` — invisible to a script that queries the
 * first — and 6 by nothing at all, so no tenant predicate reaches them.
 *
 * This is deliberately an INVENTORY, not a disposition. Whether a given table is
 * erased, anonymised, or retained under a legal basis is a decision per table
 * with a legal answer, and inventing 134 of those would produce a document that
 * looks like a compliance control and is not one. What it does do is make the
 * surface countable and stop it growing in the dark: `personal-data-registry.spec.ts`
 * fails the build when a schema table gains a personal-data column without being
 * listed here.
 *
 * Generated by scanning `db/schema` for column declarations whose names denote
 * an identifiable person, then reviewed. A false positive is cheap — one line
 * that says a table holds nothing sensitive after all. A false negative is a
 * table nobody erases.
 */
export type TenantScope = "org_id" | "organization_id" | "global";

export interface PersonalDataTable {
  readonly table: string;
  /** Columns naming or describing an identifiable person. */
  readonly columns: readonly string[];
  /**
   * How a person's rows are found.
   *
   * `global` is the one that matters: no tenant predicate reaches these, so an
   * erasure written against organisations misses them entirely.
   */
  readonly scope: TenantScope;
}

export const PERSONAL_DATA_TABLES: readonly PersonalDataTable[] = [
  { table: "accounts", columns: ["email", "ip_address", "user_agent"], scope: "org_id" },
  { table: "activity_participants", columns: ["address"], scope: "organization_id" },
  { table: "alumni_profiles", columns: ["email"], scope: "org_id" },
  { table: "api_keys", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "ar_documents", columns: ["ecommerce_gstin"], scope: "org_id" },
  { table: "audit_logs", columns: ["email_enabled", "ip_address", "user_agent", "whatsapp_enabled"], scope: "org_id" },
  { table: "billing_profiles", columns: ["address_line1", "address_line2", "billing_email", "gstin", "pan", "pincode"], scope: "org_id" },
  { table: "biometric_devices", columns: ["ip_address"], scope: "org_id" },
  { table: "blog_authors", columns: ["email"], scope: "global" },
  { table: "booking_link_interviewers", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "broadcasts", columns: ["email_enabled", "ip_address", "user_agent", "whatsapp_enabled"], scope: "org_id" },
  /*
    Took over from `leads`, `clients`, `contacts` and `crm_organizations`, which
    ticket 08 dropped. Their personal data did not go with them -- it was always
    a mirror of these columns, and `gstin` and `whatsapp_number` are `tax_number`
    and `whatsapp_phone` under the merged model's names.

    `acquisition_context` is the one that is not a rename. `leads.ip_address` was
    a column; on a party it is a key inside this JSONB blob, so the registry's
    scan -- which reads column declarations, not the shape of a JSON value --
    cannot find it. Listed by hand for exactly that reason: an IP address is
    personal data wherever it is stored, and this is the storage nobody would
    have flagged.
  */
  { table: "business_parties", columns: ["acquisition_context", "email", "phone", "tax_number", "whatsapp_phone"], scope: "organization_id" },
  { table: "calendar_events", columns: ["email_enabled", "whatsapp_enabled"], scope: "org_id" },
  { table: "calibration_participants", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "calibration_sessions", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidate_applications", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidate_documents", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "candidate_documents_vault", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidate_offers", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "candidate_reference_checks", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidate_referrals", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidate_resumes", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidate_sla_tracking", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidate_sources", columns: ["contact_email", "contact_phone", "email", "first_name", "last_name", "phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidates", columns: ["contact_email", "contact_phone", "email", "first_name", "last_name", "phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "client_account_activities", columns: ["email", "phone", "respondent_email"], scope: "org_id" },
  { table: "client_accounts", columns: ["client_email", "client_phone", "client_whatsapp", "email", "phone", "respondent_email"], scope: "org_id" },
  { table: "client_onboarding_items", columns: ["respondent_email"], scope: "org_id" },
  { table: "client_onboarding_templates", columns: ["respondent_email"], scope: "org_id" },
  { table: "client_opportunities", columns: ["respondent_email"], scope: "org_id" },
  { table: "crm_contact_channel_consent", columns: ["address_hash"], scope: "org_id" },
  { table: "crm_contact_consent_events", columns: ["address_hash"], scope: "org_id" },
  { table: "crm_mailbox_sync", columns: ["mailbox_address"], scope: "organization_id" },
  { table: "crm_outbound_messages", columns: ["recipient_email"], scope: "organization_id" },
  { table: "crm_people", columns: ["email", "phone"], scope: "org_id" },
  { table: "crm_suppression_hashes", columns: ["address_hash"], scope: "org_id" },
  { table: "csat_responses", columns: ["respondent_email"], scope: "org_id" },
  { table: "csat_surveys", columns: ["respondent_email"], scope: "org_id" },
  { table: "deals", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "devices", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "document_audit_logs", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "document_template_versions", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "document_templates", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "document_type_roles", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "document_types", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "documents", columns: ["ip_address"], scope: "org_id" },
  { table: "email_otp_codes", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "email_outbox", columns: ["to_email"], scope: "organization_id" },
  { table: "email_sequence_enrollments", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "email_sequence_steps", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "email_sequences", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "email_suppressions", columns: ["email"], scope: "org_id" },
  { table: "exit_checklists", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "external_referrals", columns: ["ip_address"], scope: "org_id" },
  { table: "external_referrers", columns: ["email", "email_verified_at", "ip_address", "phone"], scope: "org_id" },
  { table: "gl_parties", columns: ["billing_postal_code", "email", "phone", "shipping_postal_code"], scope: "org_id" },
  { table: "handbook_versions", columns: ["ip_address"], scope: "org_id" },
  { table: "hiring_flow_rounds", columns: ["contact_email", "contact_phone", "email", "first_name", "last_name", "phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "hiring_flows", columns: ["contact_email", "contact_phone", "email", "first_name", "last_name", "phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "hr_audit_logs", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "hr_dependents", columns: ["date_of_birth"], scope: "org_id" },
  { table: "hr_employee_sensitive_fields", columns: ["national_id", "passport_expiry", "passport_number"], scope: "org_id" },
  { table: "hr_employments", columns: ["national_id", "passport_expiry", "passport_number"], scope: "org_id" },
  { table: "hr_people", columns: ["address", "date_of_birth", "first_name", "last_name", "national_id", "passport_expiry", "passport_number", "personal_email", "phone", "work_email"], scope: "org_id" },
  { table: "interview_booking_links", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "interview_panel_members", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "interview_questions", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "interview_scorecards", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "interview_slas", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "interviews", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "inv_sales_orders", columns: ["shipping_address"], scope: "org_id" },
  { table: "inv_vendors", columns: ["address", "email", "gstin", "phone"], scope: "org_id" },
  { table: "inv_warehouses", columns: ["address"], scope: "org_id" },
  { table: "invitations", columns: ["email", "ip_address", "user_agent"], scope: "org_id" },
  { table: "invoice_items", columns: ["supplier_gstin", "vendor_gstin"], scope: "org_id" },
  { table: "invoices", columns: ["customer_gstin", "supplier_gstin", "vendor_gstin"], scope: "org_id" },
  { table: "job_postings", columns: ["contact_email", "contact_phone", "email", "first_name", "last_name", "phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "lead_activities", columns: ["from_email", "to_email"], scope: "org_id" },
  { table: "lead_emails", columns: ["from_email", "to_email"], scope: "org_id" },
  { table: "lead_notes", columns: ["from_email", "to_email"], scope: "org_id" },
  { table: "lead_tasks", columns: ["from_email", "to_email"], scope: "org_id" },
  { table: "legal_entities", columns: ["gstin", "pan", "registered_address"], scope: "org_id" },
  { table: "login_history", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "magic_link_tokens", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "mail_message_metadata", columns: ["sender_email"], scope: "org_id" },
  { table: "mfa_backup_codes", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "notification_audit_logs", columns: ["email_enabled", "ip_address", "user_agent", "whatsapp_enabled"], scope: "org_id" },
  { table: "notification_consent_events", columns: ["user_agent"], scope: "org_id" },
  { table: "notification_consents", columns: ["user_agent"], scope: "org_id" },
  { table: "notification_deliveries", columns: ["recipient_address"], scope: "org_id" },
  { table: "notification_events", columns: ["recipient_address"], scope: "org_id" },
  { table: "notification_preferences", columns: ["email_enabled", "whatsapp_enabled"], scope: "org_id" },
  { table: "notification_templates", columns: ["email_enabled", "ip_address", "user_agent", "whatsapp_enabled"], scope: "org_id" },
  { table: "nps_responses", columns: ["respondent_email"], scope: "org_id" },
  { table: "nps_surveys", columns: ["respondent_email"], scope: "org_id" },
  { table: "offer_letter_templates", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "offer_negotiations", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "offer_versions", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "onboarding_documents", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "onboarding_steps", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "onboarding_tasks", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "onboarding_template_steps", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "onboarding_templates", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "org_custom_domains", columns: ["date_of_birth", "email", "email_verified", "first_name", "ip_address", "last_name", "phone", "user_agent", "whatsapp_number", "whatsapp_same_as_phone"], scope: "org_id" },
  { table: "org_holidays", columns: ["date_of_birth", "email", "email_verified", "first_name", "ip_address", "last_name", "phone", "user_agent", "whatsapp_number", "whatsapp_same_as_phone"], scope: "org_id" },
  { table: "organization_allowed_email_domains", columns: ["date_of_birth", "email", "email_verified", "first_name", "ip_address", "last_name", "phone", "user_agent", "whatsapp_number", "whatsapp_same_as_phone"], scope: "org_id" },
  { table: "organization_members", columns: ["date_of_birth", "email", "email_verified", "first_name", "ip_address", "last_name", "phone", "user_agent", "whatsapp_number", "whatsapp_same_as_phone"], scope: "org_id" },
  { table: "organization_people", columns: ["address", "date_of_birth", "first_name", "last_name", "personal_email", "phone", "whatsapp_number", "work_email"], scope: "organization_id" },
  { table: "organizations", columns: ["address", "billing_email", "date_of_birth", "email", "email_verified", "first_name", "ip_address", "last_name", "phone", "support_email", "support_phone", "tax_number", "user_agent", "whatsapp_number", "whatsapp_same_as_phone"], scope: "org_id" },
  { table: "party_contacts", columns: ["email", "first_name", "last_name", "phone"], scope: "organization_id" },
  { table: "payment_audit_events", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "payment_provider_accounts", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "payment_provider_credentials", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "payment_providers", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "payment_test_transactions", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "payment_webhook_endpoints", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "payment_webhook_events", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "payments", columns: ["supplier_gstin", "vendor_gstin"], scope: "org_id" },
  { table: "payroll_entities", columns: ["pan"], scope: "org_id" },
  { table: "permissions", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "pipeline_automations", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "platform_messages", columns: ["email", "ip_address", "phone", "user_agent"], scope: "global" },
  { table: "platform_payments", columns: ["customer_email"], scope: "org_id" },
  { table: "platform_visits", columns: ["user_agent"], scope: "global" },
  { table: "platform_waitlist", columns: ["email", "ip_address", "user_agent"], scope: "global" },
  { table: "policy_acknowledgments", columns: ["ip_address"], scope: "org_id" },
  { table: "portal_invitations", columns: ["email"], scope: "organization_id" },
  { table: "purchase_bills", columns: ["supplier_gstin", "vendor_gstin"], scope: "org_id" },
  { table: "push_subscriptions", columns: ["email_enabled", "user_agent", "whatsapp_enabled"], scope: "org_id" },
  { table: "recruitment_vendors", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "referrals", columns: ["referred_email"], scope: "global" },
  { table: "relationship_participants", columns: ["address"], scope: "organization_id" },
  { table: "resignations", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "rich_documents", columns: ["ip_address"], scope: "org_id" },
  { table: "roles", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "scorecard_templates", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "sign_audit_events", columns: ["actor_email", "ip_address", "user_agent"], scope: "org_id" },
  { table: "sign_recipients", columns: ["consent_user_agent", "email", "phone"], scope: "org_id" },
  { table: "subject_requests", columns: ["subject_email"], scope: "global" },
  { table: "subprocessor_subscribers", columns: ["email"], scope: "organization_id" },
  { table: "support_ticket_messages", columns: ["source_contact_email"], scope: "org_id" },
  { table: "support_tickets", columns: ["requester_email", "source_contact_email"], scope: "org_id" },
  { table: "survey_collectors", columns: ["email", "phone"], scope: "org_id" },
  { table: "survey_participants", columns: ["email", "phone"], scope: "org_id" },
  { table: "terminations", columns: ["email", "email_sent_at", "email_status"], scope: "org_id" },
  { table: "user_integration_connections", columns: ["account_email"], scope: "org_id" },
  { table: "user_sessions", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "users", columns: ["date_of_birth", "email", "email_verified", "first_name", "ip_address", "last_name", "phone", "user_agent", "whatsapp_number", "whatsapp_same_as_phone"], scope: "org_id" },
  { table: "vault_access_logs", columns: ["contact_email", "contact_phone", "reference_email", "reference_phone"], scope: "org_id" },
  { table: "verification_tokens", columns: ["email", "ip_address", "user_agent"], scope: "org_id" },
];

export const PERSONAL_DATA_TABLE_NAMES: ReadonlySet<string> = new Set(
  PERSONAL_DATA_TABLES.map((entry) => entry.table),
);

/**
 * Tables no tenant predicate reaches.
 *
 * Called out separately because they are the ones an erasure built around
 * organisations silently skips. `subject_requests` is on this list and is worth
 * reading twice: the record of an erasure request retains the subject's own
 * email address, globally, for as long as the record is kept.
 */
export const GLOBAL_PERSONAL_DATA_TABLES: readonly string[] = PERSONAL_DATA_TABLES.filter(
  (entry) => entry.scope === "global",
).map((entry) => entry.table);
