/**
 * Every table that holds personal data, and how a person is scoped within it.
 *
 * Phase 3, ticket 17.
 *
 * The ticket asks for erasure "across every region and generation". What was
 * there before was a `runAcrossRegions` helper with no callers, no table names
 * and no database import, plus `scripts/purge-user.mjs` — the only working
 * erasure, which finds rows by three predicates: `org_id = ANY(orgs the subject
 * OWNS)`, a single-column foreign key to `public.users`, and a column literally
 * named `email`.
 *
 * Measured against the schema, that misses most of the surface. This file is the
 * measurement: 70 tables carry personal data, of which 52 are scoped by
 * `org_id`, 12 by `organization_id` — invisible to a script that queries the
 * first — and 6 by nothing at all, so no tenant predicate reaches them.
 *
 * The count is prose and prose drifts: it read 68 / 52 / 10 / 6 while the list
 * already held 69 entries, because an entry can be added without touching the
 * paragraph above it. The spec counts the list, not this sentence — so treat
 * the numbers here as a reading taken on a date, and re-take it when you add
 * a row.
 *
 * **Those numbers were 154 / 138 / 10 / 6 until 2026-09-09, and they were
 * wrong.** The generator extracted a table's body with
 * `split("\n);")[0]`, which does not terminate at a table written
 * `pgTable("x", { … });` — that form ends `});`, so the body ran on into every
 * table below it until one happened to end with a line-initial `);`. Columns
 * therefore bled backwards into earlier tables: `organization_members` was
 * credited with `users`' email and phone, and `crm_contact_channel_consent` with
 * an `address_hash` that exists only on `crm_suppression_hashes` further down
 * the same file. 81 of the 149 entries described a table that holds none of what
 * was claimed, and 13 more named at least one column that does not exist.
 *
 * The correction was made against `information_schema` rather than by re-running
 * the generator, so every column named below is one a database actually has; a
 * brace-matching re-scan of the schema source independently arrives at the same
 * 68 tables. Nothing was dropped that holds personal data: the broken scan's
 * window strictly contains each table's real body, so it could only ever
 * over-report.
 *
 * This is deliberately an INVENTORY, not a disposition. Whether a given table is
 * erased, anonymised, or retained under a legal basis is a decision per table
 * with a legal answer, and inventing 68 of those would produce a document that
 * looks like a compliance control and is not one. What it does do is make the
 * surface countable and stop it growing in the dark, in both directions:
 * `personal-data-registry.spec.ts` fails the build when a schema table gains a
 * personal-data column without being listed here, **and** when an entry here
 * names a column no table has. Only the first of those existed before, which is
 * why a phantom column could sit in a compliance inventory unchallenged.
 *
 * Generated by scanning `db/schema` for column declarations whose names denote
 * an identifiable person, then reviewed. A false positive is cheap — one line
 * that says a table holds nothing sensitive after all. A false negative is a
 * table nobody erases. `business_parties.acquisition_context` is the standing
 * example of an entry the scan cannot produce and a person must keep.
 */
export type TenantScope = "org_id" | "organization_id" | "global";

export interface PersonalDataTable {
  readonly table: string;
  /** Columns naming or describing an identifiable person. */
  readonly columns: readonly string[];
  /**
   * How a person's rows are found.
   *
   * `global` is the one that matters: no tenant predicate reaches these, so an
   * erasure written against organisations misses them entirely.
   */
  readonly scope: TenantScope;
}

export const PERSONAL_DATA_TABLES: readonly PersonalDataTable[] = [
  { table: "activity_participants", columns: ["address"], scope: "organization_id" },
  { table: "alumni_profiles", columns: ["email"], scope: "org_id" },
  { table: "ar_documents", columns: ["ecommerce_gstin"], scope: "org_id" },
  { table: "audit_logs", columns: ["ip_address"], scope: "org_id" },
  { table: "billing_invoice_snapshots", columns: ["buyer_address", "buyer_name", "seller_address", "seller_name"], scope: "org_id" },
  { table: "billing_profiles", columns: ["address_line1", "address_line2", "billing_email", "gstin", "pan", "pincode"], scope: "org_id" },
  { table: "biometric_devices", columns: ["ip_address"], scope: "org_id" },
  { table: "blog_authors", columns: ["email"], scope: "global" },
  /*
    Took over from `leads`, `clients`, `contacts` and `crm_organizations`, which
    ticket 08 dropped. Their personal data did not go with them -- it was always
    a mirror of these columns, and `gstin` and `whatsapp_number` are `tax_number`
    and `whatsapp_phone` under the merged model's names.

    `acquisition_context` is the one that is not a rename. `leads.ip_address` was
    a column; on a party it is a key inside this JSONB blob, so the registry's
    scan -- which reads column declarations, not the shape of a JSON value --
    cannot find it. Listed by hand for exactly that reason: an IP address is
    personal data wherever it is stored, and this is the storage nobody would
    have flagged.
  */
  { table: "business_parties", columns: ["acquisition_context", "email", "phone", "tax_number", "whatsapp_phone"], scope: "organization_id" },
  { table: "candidate_reference_checks", columns: ["reference_email", "reference_phone"], scope: "org_id" },
  { table: "candidates", columns: ["email", "first_name", "last_name", "phone"], scope: "org_id" },
  { table: "client_accounts", columns: ["client_email", "client_phone", "client_whatsapp"], scope: "org_id" },
  /*
    The one of the four legacy CRM identity tables that is still declared.

    CRM no longer writes it — a client is a Party now — but `build/ticket-core.ts`
    and `support/agent-routing.ts` hold foreign keys to it, so the declaration and
    the table both survive until the opt-in 0278 drop runs. "Nothing writes it" is
    not "nothing is in it": the rows written before the Party cutover are still
    there, still hold an address and a phone number, and an erasure that skipped
    the table because CRM stopped writing it would leave every one of them.
  */
  { table: "clients", columns: ["email", "gstin", "phone"], scope: "org_id" },
  { table: "crm_mailbox_sync", columns: ["mailbox_address"], scope: "organization_id" },
  { table: "crm_outbound_messages", columns: ["recipient_email"], scope: "organization_id" },
  { table: "crm_people", columns: ["email", "phone"], scope: "org_id" },
  /*
    A scheduled report's recipient list is a standing instruction to email a
    person on a timetable, so it is the one kind of address where leaving the
    row behind keeps sending mail after the person is gone — an erasure that
    misses it does not merely retain data, it goes on acting on it.
  */
  { table: "crm_report_schedule_recipients", columns: ["email"], scope: "organization_id" },
  { table: "crm_suppression_hashes", columns: ["address_hash"], scope: "org_id" },
  /*
    Listed, and a false positive — the scan flags `business_phone_number_id`
    because it contains "phone", but the number it identifies is the TENANT's own
    WhatsApp Business sender, not a data subject's. It is here anyway, because
    the alternative is teaching the scan an exception and the registry's whole
    argument is that a false positive costs one line and an argument in a diff,
    while a false negative costs a table nobody erases. `app_secret` and
    `verify_token` on the same table are credentials rather than personal data;
    they need rotating on a breach, not erasing on a subject request.
  */
  { table: "crm_whatsapp_channels", columns: ["business_phone_number_id"], scope: "organization_id" },
  { table: "csat_responses", columns: ["respondent_email"], scope: "org_id" },
  { table: "deals", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "email_outbox", columns: ["to_email"], scope: "organization_id" },
  { table: "email_suppressions", columns: ["email"], scope: "org_id" },
  { table: "external_referrals", columns: ["ip_address"], scope: "org_id" },
  { table: "external_referrers", columns: ["email", "email_verified_at", "phone"], scope: "org_id" },
  { table: "gl_parties", columns: ["billing_postal_code", "email", "phone", "shipping_postal_code"], scope: "org_id" },
  { table: "hr_audit_logs", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "hr_dependents", columns: ["date_of_birth"], scope: "org_id" },
  { table: "hr_employee_sensitive_fields", columns: ["national_id", "passport_expiry", "passport_number"], scope: "org_id" },
  { table: "hr_reporting_line_bulk_job_rows", columns: ["employee_email", "requested_primary_manager_email", "secondary_manager_email_1", "secondary_manager_email_2", "secondary_manager_email_3"], scope: "org_id" },
  { table: "inv_projects", columns: ["site_address", "site_contact_name", "site_contact_phone"], scope: "org_id" },
  { table: "inv_sales_orders", columns: ["shipping_address"], scope: "org_id" },
  // A false positive, kept on purpose: `qc_zepto_email_po_enabled` is a boolean
  // switch (receive Zepto POs by email), not an address. The scan matches "email"
  // and the registry accounts for every hit, so this line is the argument.
  { table: "inv_settings", columns: ["qc_zepto_email_po_enabled"], scope: "org_id" },
  { table: "inv_vendors", columns: ["address", "email", "gstin", "phone"], scope: "org_id" },
  { table: "inv_warehouses", columns: ["address"], scope: "org_id" },
  { table: "invitations", columns: ["email"], scope: "org_id" },
  { table: "invoices", columns: ["customer_gstin", "supplier_gstin"], scope: "org_id" },
  { table: "lead_emails", columns: ["from_email", "to_email"], scope: "org_id" },
  { table: "legal_entities", columns: ["gstin", "pan", "registered_address"], scope: "org_id" },
  { table: "login_history", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "mail_message_metadata", columns: ["sender_email"], scope: "org_id" },
  { table: "notification_audit_logs", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "notification_consent_events", columns: ["user_agent"], scope: "org_id" },
  { table: "notification_consents", columns: ["user_agent"], scope: "org_id" },
  { table: "notification_deliveries", columns: ["recipient_address"], scope: "org_id" },
  { table: "notification_preferences", columns: ["email_enabled", "whatsapp_enabled"], scope: "org_id" },
  { table: "nps_responses", columns: ["respondent_email"], scope: "org_id" },
  { table: "operator_access_log", columns: ["ip_address"], scope: "org_id" },
  { table: "organization_people", columns: ["address", "date_of_birth", "first_name", "last_name", "personal_email", "phone", "whatsapp_number", "work_email"], scope: "organization_id" },
  { table: "organizations", columns: ["address", "billing_email", "support_email", "support_phone", "tax_number"], scope: "org_id" },
  { table: "party_contacts", columns: ["email", "first_name", "last_name", "phone"], scope: "organization_id" },
  { table: "payment_audit_events", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "payroll_entities", columns: ["pan"], scope: "org_id" },
  { table: "platform_messages", columns: ["email", "ip_address", "phone", "user_agent"], scope: "global" },
  { table: "platform_payments", columns: ["customer_email"], scope: "org_id" },
  { table: "platform_visits", columns: ["user_agent"], scope: "global" },
  { table: "platform_waitlist", columns: ["email", "ip_address", "user_agent"], scope: "global" },
  { table: "policy_acknowledgments", columns: ["ip_address"], scope: "org_id" },
  { table: "portal_invitations", columns: ["email"], scope: "organization_id" },
  { table: "purchase_bills", columns: ["supplier_gstin", "vendor_gstin"], scope: "org_id" },
  { table: "push_subscriptions", columns: ["user_agent"], scope: "org_id" },
  { table: "recruitment_vendors", columns: ["contact_email", "contact_phone"], scope: "org_id" },
  { table: "referrals", columns: ["referred_email"], scope: "global" },
  { table: "relationship_participants", columns: ["address"], scope: "organization_id" },
  { table: "sign_audit_events", columns: ["actor_email", "ip_address", "user_agent"], scope: "org_id" },
  { table: "sign_recipients", columns: ["consent_user_agent", "email", "phone"], scope: "org_id" },
  { table: "subject_requests", columns: ["subject_email"], scope: "global" },
  { table: "subprocessor_subscribers", columns: ["email"], scope: "organization_id" },
  { table: "support_ticket_messages", columns: ["source_contact_email"], scope: "org_id" },
  { table: "support_tickets", columns: ["requester_email"], scope: "org_id" },
  { table: "survey_participants", columns: ["email", "phone"], scope: "org_id" },
  { table: "terminations", columns: ["email_sent_at", "email_status"], scope: "org_id" },
  { table: "user_integration_connections", columns: ["account_email"], scope: "org_id" },
  { table: "user_sessions", columns: ["ip_address", "user_agent"], scope: "org_id" },
  { table: "users", columns: ["date_of_birth", "email", "email_verified", "first_name", "last_name", "phone", "whatsapp_number", "whatsapp_same_as_phone"], scope: "org_id" },
];

export const PERSONAL_DATA_TABLE_NAMES: ReadonlySet<string> = new Set(
  PERSONAL_DATA_TABLES.map((entry) => entry.table),
);

/**
 * Tables no tenant predicate reaches.
 *
 * Called out separately because they are the ones an erasure built around
 * organisations silently skips. `subject_requests` is on this list and is worth
 * reading twice: the record of an erasure request retains the subject's own
 * email address, globally, for as long as the record is kept.
 */
export const GLOBAL_PERSONAL_DATA_TABLES: readonly string[] = PERSONAL_DATA_TABLES.filter(
  (entry) => entry.scope === "global",
).map((entry) => entry.table);
