export { AdmissionModule } from "./admission.module";
export { AdmissionService } from "./admission.service";
export type { AdmissionConfig } from "./admission.config";
export type { AdmissionDecision, AdmissionSnapshot } from "./admission.service";
export { resolveAdmissionConfig, admissionEnvShape } from "./admission.config";
export { AdmissionGuard } from "./admission.guard";
export { AdmissionInterceptor } from "./admission.interceptor";
export { UseWorkClass, WORK_CLASS_KEY } from "./work-class.decorator";
export { isReserved, shedRank, NUM_SHEDDABLE_RANKS } from "./work-class";
export type { WorkClass, SheddableClass, ReservedClass } from "./work-class";
