/**
 * The executable-code half of the PRD-C057 inventory: routes/operations,
 * permissions, modules, events, commands, query/cache keys, configuration,
 * environment variables, feature flags and translations.
 *
 * Every extractor here reports its own population size. A registry that comes
 * back empty is recorded as EMPTY WITH EVIDENCE rather than silently omitted —
 * "no translations" and "the extractor broke" are the same shape otherwise, and
 * this repo has already paid once for a scan that reported everything dead.
 */

import { existsSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";

import { loadBackendCatalog } from "../permission-key-extractors.mjs";
import { walk } from "./corpus.mjs";

export function operations(openapiPath) {
  const document = JSON.parse(readFileSync(openapiPath, "utf8"));
  const out = [];
  for (const [path, item] of Object.entries(document.paths ?? {})) {
    for (const [method, operation] of Object.entries(item ?? {})) {
      if (!["get", "post", "put", "patch", "delete", "head", "options"].includes(method)) continue;
      const responses = operation.responses ?? {};
      const success = Object.entries(responses).filter(([code]) => code.startsWith("2"));
      const hasResponseSchema = success.some(
        ([, response]) => response?.content?.["application/json"]?.schema !== undefined,
      );
      out.push({
        item: `${method.toUpperCase()} ${path}`,
        exposure: operation["x-exposure"] ?? "",
        permission: operation["x-permission"] ?? "",
        published: operation["x-published"] === true || operation["x-consumer"] !== undefined,
        hasRequestSchema: operation.requestBody?.content?.["application/json"]?.schema !== undefined,
        hasResponseSchema,
      });
    }
  }
  return out;
}

/**
 * Only `name: "<key>"` counts. Matching every quoted `a:b` in the catalog folder
 * also collects the `resource:` half of each entry and reports 984 keys where the
 * catalog holds 704 — an inventory that overcounts its own registry is worse than
 * no inventory.
 */
const PERMISSION_NAME = /^\s*name:\s*["'`]([a-z][a-z0-9-]*(?::[a-z0-9-]+){1,3})["'`]/;

export function permissions(permissionsDir) {
  const keys = new Map();
  const catalog = loadBackendCatalog();
  for (const name of catalog.names) keys.set(name, "(generated by the catalog module)");
  for (const file of walk(permissionsDir, { extensions: new Set([".ts"]) })) {
    if (/\.spec\.ts$/.test(file)) continue;
    const lines = readFileSync(file, "utf8").split("\n");
    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i] ?? "";
      if (/^\s*(\/\/|\*|\/\*)/.test(line)) continue;
      const match = PERMISSION_NAME.exec(line);
      const key = match?.[1];
      if (key === undefined) continue;
      keys.set(key, `${relative(permissionsDir, file)}:${String(i + 1)}`);
    }
  }
  const accessManaged = new Set(catalog.accessManaged);
  return [...keys.entries()].map(([item, evidence]) => ({
    item,
    evidence,
    // `<module>:access:view` and `<module>:access:manage` are synthesised per
    // access-managed module and consumed through a template, never as a literal.
    // A literal search reports all 20 of them dead; they are not.
    generated: /:access:(view|manage)$/.test(item) && accessManaged.has(item.split(":")[0] ?? ""),
  }));
}

export function modules(manifestPath) {
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const list = Array.isArray(manifest) ? manifest : (manifest.modules ?? []);
  return list.map((entry) => ({
    item: entry.id ?? entry.key ?? entry.moduleKey ?? entry.name ?? JSON.stringify(entry).slice(0, 60),
    productKey: entry.productKey ?? "",
    planGated: entry.planGated === true,
    administersNamespaces: entry.administersNamespaces ?? [],
  }));
}

const EVENT_KEY = /["'`]([a-z][a-z0-9_]*(?:\.[a-z0-9_]+){1,4})["'`]/g;

export function events(catalogDir, webhookSchemaPath) {
  const out = new Map();
  for (const file of walk(catalogDir, { extensions: new Set([".ts"]) })) {
    if (!/notification-events.*\.catalog\.ts$/.test(file)) continue;
    const lines = readFileSync(file, "utf8").split("\n");
    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i] ?? "";
      if (/^\s*(\/\/|\*|\/\*)/.test(line)) continue;
      if (!line.includes("e(")) continue;
      for (const match of line.matchAll(EVENT_KEY)) {
        const key = match[1];
        if (key === undefined) continue;
        if (!out.has(key)) out.set(key, { kind: "notification", evidence: `${relative(catalogDir, file)}:${String(i + 1)}` });
      }
    }
  }
  if (existsSync(webhookSchemaPath)) {
    const lines = readFileSync(webhookSchemaPath, "utf8").split("\n");
    let inside = false;
    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i] ?? "";
      if (line.includes("WEBHOOK_EVENTS")) inside = true;
      if (!inside) continue;
      for (const match of line.matchAll(EVENT_KEY)) {
        const key = match[1];
        if (key === undefined) continue;
        if (!out.has(key)) out.set(key, { kind: "webhook", evidence: `webhooks.schemas.ts:${String(i + 1)}` });
      }
      if (inside && line.includes("]")) inside = false;
    }
  }
  return [...out.entries()].map(([item, meta]) => ({ item, ...meta }));
}

/**
 * The API contract registry's own event surfaces: `events` are OutboxWriter
 * events and `webhooks` are the outbound customer-facing names, both versioned
 * and gated by check:contract-registry. They are a DIFFERENT population from the
 * notification catalog — an inventory built from the notification catalogs alone
 * misses all 47 of them.
 */
export function contractRegistryEvents(registryPath) {
  if (!existsSync(registryPath)) return [];
  const registry = JSON.parse(readFileSync(registryPath, "utf8"));
  const out = [];
  for (const [name, entry] of Object.entries(registry.events ?? {}))
    out.push({ item: name, kind: "outbox", version: entry?.version ?? "", evidence: "contracts/api-contract-registry.json (events)" });
  for (const [name, entry] of Object.entries(registry.webhooks ?? {}))
    out.push({ item: name, kind: "outbound-webhook", version: entry?.version ?? "", evidence: "contracts/api-contract-registry.json (webhooks)" });
  return out;
}

export function commands(commandCatalogPath) {
  if (!existsSync(commandCatalogPath)) return [];
  const lines = readFileSync(commandCatalogPath, "utf8").split("\n");
  const out = [];
  let group = "";
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    const groupMatch = /export const ([A-Z_]+_COMMANDS)\s*=/.exec(line);
    if (groupMatch?.[1] !== undefined) group = groupMatch[1];
    const keyMatch = /^\s{2}([A-Za-z][A-Za-z0-9_]*)\s*:/.exec(line);
    if (keyMatch?.[1] !== undefined && group !== "")
      out.push({ item: `${group}.${keyMatch[1]}`, evidence: `lib/command-catalog.ts:${String(i + 1)}` });
  }
  return out;
}

/**
 * The registry entry is the key FAMILY, not the file. `payrollQueryKeys` is one
 * export holding dozens of independently invalidated families, and it was a
 * collision between two of them — bankBatches and bankBatch on independent id
 * sequences — that this granularity exists to make visible.
 */
export function queryKeyFactories(queryKeysDir) {
  const out = [];
  for (const file of walk(queryKeysDir, { extensions: new Set([".ts"]) })) {
    if (/\.test\.ts$/.test(file)) continue;
    const lines = readFileSync(file, "utf8").split("\n");
    let exported = "";
    let domain = "";
    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i] ?? "";
      if (/^\s*(\/\/|\*|\/\*)/.test(line)) continue;
      const exportMatch = /^export const ([A-Za-z][A-Za-z0-9_]*)\s*=/.exec(line);
      if (exportMatch?.[1] !== undefined) {
        exported = exportMatch[1];
        domain = "";
        if (!line.includes("{")) out.push({ item: exported, evidence: `${relative(queryKeysDir, file)}:${String(i + 1)}`, file });
        continue;
      }
      if (exported === "") continue;
      const domainMatch = /^ {2}([A-Za-z][A-Za-z0-9_]*):\s*\{/.exec(line);
      if (domainMatch?.[1] !== undefined) {
        domain = domainMatch[1];
        continue;
      }
      const memberMatch = /^ {4}([A-Za-z][A-Za-z0-9_]*):/.exec(line);
      if (memberMatch?.[1] === undefined || domain === "") continue;
      out.push({
        item: `${exported}.${domain}.${memberMatch[1]}`,
        evidence: `${relative(queryKeysDir, file)}:${String(i + 1)}`,
        file,
      });
    }
  }
  return out;
}

/**
 * A namespace is what `namespace(`…`)` brands, not every colon-joined literal in
 * the file: an exact key and a namespace are different types on purpose
 * (`ExactCacheKey` refuses a namespace) and only the namespace half is bumped.
 */
export function cacheNamespaces(cacheKeysPath, extraRoot) {
  if (!existsSync(cacheKeysPath)) return [];
  const lines = readFileSync(cacheKeysPath, "utf8").split("\n");
  const out = new Map();
  if (extraRoot !== undefined) {
    for (const file of walk(extraRoot, { skipPaths: ["db/schema"], extensions: new Set([".ts"]) })) {
      if (/\.spec\.ts$/.test(file) || file.endsWith("cache-keys.ts")) continue;
      const moduleLines = readFileSync(file, "utf8").split("\n");
      for (let i = 0; i < moduleLines.length; i += 1) {
        const line = moduleLines[i] ?? "";
        if (/^\s*(\/\/|\*|\/\*)/.test(line)) continue;
        const local = /^\s*(?:export )?const ([A-Z][A-Z0-9_]*(?:NS|NAMESPACE))\b/.exec(line);
        if (local?.[1] === undefined) continue;
        if (!out.has(local[1])) out.set(local[1], { prefix: "", evidence: `${relative(extraRoot, file)}:${String(i + 1)}` });
      }
    }
  }
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    if (/^\s*(\/\/|\*|\/\*)/.test(line)) continue;
    const factory = /^\s{2}([A-Za-z][A-Za-z0-9_]*Namespace)\s*:/.exec(line);
    if (factory?.[1] !== undefined && !out.has(factory[1]))
      out.set(factory[1], { prefix: "", evidence: `common/cache/cache-keys.ts:${String(i + 1)}` });
    for (const match of line.matchAll(/namespace\(`([^`$]*)/g)) {
      const prefix = (match[1] ?? "").replace(/:$/, "");
      if (prefix === "") continue;
      const owner = [...out.entries()].reverse().find(([, meta]) => meta.prefix === "");
      if (owner !== undefined) owner[1].prefix = prefix;
    }
  }
  return [...out.entries()].map(([item, meta]) => ({ item, prefix: meta.prefix, evidence: meta.evidence }));
}

export function environmentVariables(envValidationPath, poolConfigPath) {
  const out = new Map();
  for (const path of [envValidationPath, poolConfigPath]) {
    if (!existsSync(path)) continue;
    const lines = readFileSync(path, "utf8").split("\n");
    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i] ?? "";
      if (/^\s*(\/\/|\*|\/\*)/.test(line)) continue;
      const match = /^\s{2,}([A-Z][A-Z0-9_]{2,})\s*:/.exec(line);
      if (match?.[1] === undefined) continue;
      if (!out.has(match[1])) out.set(match[1], `${path.split("/src/")[1] ?? path}:${String(i + 1)}`);
    }
  }
  return [...out.entries()].map(([item, evidence]) => ({ item, evidence }));
}

export function translations(frontendRoot) {
  const candidates = ["messages", "locales", "i18n", "public/locales", "lib/i18n"];
  const found = [];
  for (const candidate of candidates) {
    const path = join(frontendRoot, candidate);
    if (existsSync(path)) found.push(candidate);
  }
  return found;
}

/**
 * Module configuration: the tenant-facing settings keys each module accepts,
 * taken from the Zod schema that validates them. This is the registry PRD-C057
 * calls "configuration", and it is distinct from the environment variables — a
 * settings key is per-organisation and set through the API, an environment
 * variable is per-deployment and set by an operator.
 *
 * A configuration key the API accepts and no code reads is the defect this
 * registry exists to surface: the tenant changes it, the request succeeds, and
 * nothing happens.
 */
const SETTINGS_SCHEMA = /^export const ([A-Za-z][A-Za-z0-9_]*[Ss]ettingsSchema)\s*=\s*z\s*$|^export const ([A-Za-z][A-Za-z0-9_]*[Ss]ettingsSchema)\s*=\s*z\.object\(\{/;

export function configuration(modulesRoot) {
  const out = [];
  for (const file of walk(modulesRoot, { extensions: new Set([".ts"]) })) {
    if (!/schemas\.ts$/.test(file) || /\.spec\.ts$/.test(file)) continue;
    const lines = readFileSync(file, "utf8").split("\n");
    let schema = "";
    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i] ?? "";
      if (/^\s*(\/\/|\*|\/\*)/.test(line)) continue;
      const match = SETTINGS_SCHEMA.exec(line);
      if (match !== null) {
        schema = match[1] ?? match[2] ?? "";
        continue;
      }
      if (schema === "") continue;
      if (/^\}\)/.test(line)) {
        schema = "";
        continue;
      }
      const key = /^ {2}([A-Za-z][A-Za-z0-9_]*)\s*:/.exec(line);
      if (key?.[1] === undefined) continue;
      const owningModule = relative(modulesRoot, file).split("/")[0] ?? "platform-core";
      out.push({
        item: `${owningModule}.${schema}.${key[1]}`,
        key: key[1],
        owner: owningModule,
        evidence: `src/modules/${relative(modulesRoot, file)}:${String(i + 1)}`,
      });
    }
  }
  return out;
}

/**
 * Feature flags. Two populations, and they fail differently: six per-organisation
 * flags declared as a TypeScript interface, and the `feature_flags` table whose
 * keys are rows rather than symbols.
 */
export function featureFlags(settingsHelpersPath) {
  const out = [];
  if (!existsSync(settingsHelpersPath)) return out;
  const lines = readFileSync(settingsHelpersPath, "utf8").split("\n");
  let inside = false;
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    if (/export interface OrgFeatureFlags/.test(line)) {
      inside = true;
      continue;
    }
    if (!inside) continue;
    if (/^\}/.test(line)) break;
    const key = /^\s{2}([A-Za-z][A-Za-z0-9_]*)\s*:/.exec(line);
    if (key?.[1] === undefined) continue;
    out.push({ item: `OrgFeatureFlags.${key[1]}`, key: key[1], evidence: `src/modules/settings/settings.helpers.ts:${String(i + 1)}` });
  }
  return out;
}
