-- 1208 — Knowledge base: `kb_ai_interactions` — one reconstructable row per Ask
--
-- `kb_ai_interactions` closes the observability gap in the KB Ask feature. Before this migration,
-- the record of a single Ask was spread across five tables (kb_chat_messages, kb_chat_conversations,
-- kb_events, tenant_ai_credits, tenant_ai_credit_transactions) with no shared key, so cost,
-- latency, which passages were sent, which model answered, and what the user did with the answer
-- were not recoverable together. This table provides the anchor.
--
-- Every row carries:
--   - `correlation_id` — a UUID generated by KbAskService at call time. Every kb_events row emitted
--     for the same Ask carries the same value (see migration 1209).
--   - `source_ids_with_revisions` — the source documents whose passages reached the model context,
--     recorded at send time so a later revocation is detectable rather than silently rewriting history.
--   - `result_state` — terminal state of the interaction (answered / no_context / credits_exhausted /
--     provider_unavailable / error).
--   - Token counts, latency, cost and the gateway's own correlationId for a join to ai_usage_logs.
--
-- RLS is enabled with the standard tenant_isolation policy. The table is append-only from the
-- application's perspective: the result_state is set at insert time. The streaming path may update
-- token counts after the stream completes (see HANDOFF in SESSION-06.md).
--
-- Rollback: migrations/rollback/1208_kb_ai_interactions.down.sql
SET lock_timeout = '5s';
--> statement-breakpoint

DO $$
BEGIN
  IF to_regclass('public.kb_chat_conversations') IS NULL THEN
    RAISE EXCEPTION '1208 precondition: public.kb_chat_conversations is absent';
  END IF;
  IF to_regclass('public.kb_chat_messages') IS NULL THEN
    RAISE EXCEPTION '1208 precondition: public.kb_chat_messages is absent';
  END IF;
  IF to_regclass('public.organization_members') IS NULL THEN
    RAISE EXCEPTION '1208 precondition: public.organization_members is absent';
  END IF;
END $$;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "public"."kb_ai_interactions" (
  "id" serial PRIMARY KEY,
  "org_id" text NOT NULL,
  "correlation_id" text NOT NULL,
  "actor_membership_id" integer,
  "conversation_id" integer,
  "message_id" integer,
  "provider" text,
  "model" text,
  "prompt_policy_version" integer,
  "source_ids_with_revisions" jsonb,
  "prompt_tokens" integer,
  "completion_tokens" integer,
  "total_tokens" integer,
  "latency_ms" integer,
  "result_state" text NOT NULL,
  "feedback" text,
  "cost_credits" integer,
  "gateway_correlation_id" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "uniq_kb_ai_interactions_org_id" UNIQUE ("org_id", "id"),
  CONSTRAINT "uniq_kb_ai_interactions_org_correlation" UNIQUE ("org_id", "correlation_id"),
  CONSTRAINT "chk_kb_ai_interactions_result_state" CHECK (
    "result_state" IN ('answered', 'no_context', 'credits_exhausted', 'provider_unavailable', 'error')
  )
);
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_kb_ai_interactions_org_time"
  ON "public"."kb_ai_interactions" ("org_id", "created_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_kb_ai_interactions_org_actor"
  ON "public"."kb_ai_interactions" ("org_id", "actor_membership_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_kb_ai_interactions_org_conversation"
  ON "public"."kb_ai_interactions" ("org_id", "conversation_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_kb_ai_interactions_org_correlation"
  ON "public"."kb_ai_interactions" ("org_id", "correlation_id");
--> statement-breakpoint

ALTER TABLE "public"."kb_ai_interactions" DROP CONSTRAINT IF EXISTS "kb_ai_interactions_org_id_organizations_id_fk";
--> statement-breakpoint
ALTER TABLE "public"."kb_ai_interactions" ADD CONSTRAINT "kb_ai_interactions_org_id_organizations_id_fk"
  FOREIGN KEY ("org_id") REFERENCES "public"."organizations" ("id") ON DELETE CASCADE NOT VALID;
--> statement-breakpoint
ALTER TABLE "public"."kb_ai_interactions" VALIDATE CONSTRAINT "kb_ai_interactions_org_id_organizations_id_fk";
--> statement-breakpoint

ALTER TABLE "public"."kb_ai_interactions" DROP CONSTRAINT IF EXISTS "fk_kb_ai_interactions_org_actor";
--> statement-breakpoint
ALTER TABLE "public"."kb_ai_interactions" ADD CONSTRAINT "fk_kb_ai_interactions_org_actor"
  FOREIGN KEY ("org_id", "actor_membership_id") REFERENCES "public"."organization_members" ("org_id", "id")
  ON DELETE SET NULL ("actor_membership_id") NOT VALID;
--> statement-breakpoint
ALTER TABLE "public"."kb_ai_interactions" VALIDATE CONSTRAINT "fk_kb_ai_interactions_org_actor";
--> statement-breakpoint

ALTER TABLE "public"."kb_ai_interactions" DROP CONSTRAINT IF EXISTS "fk_kb_ai_interactions_org_conversation";
--> statement-breakpoint
ALTER TABLE "public"."kb_ai_interactions" ADD CONSTRAINT "fk_kb_ai_interactions_org_conversation"
  FOREIGN KEY ("org_id", "conversation_id") REFERENCES "public"."kb_chat_conversations" ("org_id", "id")
  ON DELETE SET NULL ("conversation_id") NOT VALID;
--> statement-breakpoint
ALTER TABLE "public"."kb_ai_interactions" VALIDATE CONSTRAINT "fk_kb_ai_interactions_org_conversation";
--> statement-breakpoint

ALTER TABLE "public"."kb_ai_interactions" DROP CONSTRAINT IF EXISTS "fk_kb_ai_interactions_org_message";
--> statement-breakpoint
ALTER TABLE "public"."kb_ai_interactions" ADD CONSTRAINT "fk_kb_ai_interactions_org_message"
  FOREIGN KEY ("org_id", "message_id") REFERENCES "public"."kb_chat_messages" ("org_id", "id")
  ON DELETE SET NULL ("message_id") NOT VALID;
--> statement-breakpoint
ALTER TABLE "public"."kb_ai_interactions" VALIDATE CONSTRAINT "fk_kb_ai_interactions_org_message";
--> statement-breakpoint

ALTER TABLE "public"."kb_ai_interactions" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "public"."kb_ai_interactions";
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "public"."kb_ai_interactions"
  USING ("org_id" = app.current_org_id())
  WITH CHECK ("org_id" = app.current_org_id());
--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."kb_ai_interactions" TO streamline_app;
--> statement-breakpoint
GRANT USAGE, SELECT ON SEQUENCE "public"."kb_ai_interactions_id_seq" TO streamline_app;
--> statement-breakpoint

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'kb_ai_interactions'
  ) THEN
    RAISE EXCEPTION '1208 postcondition: kb_ai_interactions was not created';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'kb_ai_interactions' AND policyname = 'tenant_isolation'
  ) THEN
    RAISE EXCEPTION '1208 postcondition: RLS policy tenant_isolation is absent on kb_ai_interactions';
  END IF;
END $$;
--> statement-breakpoint
