import type { MembershipArtifact } from "../membership-artifact.types";

export const HR_LIFECYCLE_AND_RECORDS_ARTIFACTS = [
  {
    id: "worker_engagements_creator",
    mechanism: "database-cascade",
    table: "worker_engagements",
    keyedBy: "created_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "The composite FK fk_worker_engagements_created_actor is ON DELETE SET NULL (migration 0836). The engagement record survives with the creator slot cleared automatically. The updated_by and archived_by FKs are pending (hrms-phase1) and will be authored as SET NULL directly.",
  },
  {
    id: "onboarding_flow_sessions",
    mechanism: "database-cascade",
    table: "onboarding_flow_sessions",
    keyedBy: "membership_id",
    onRemoval: "cascade",
    onSuspension: "retain",
    reason:
      "Corrected 2026-09-03 against pg_catalog at journal head 676 (ticket 03, PRD-C053). This entry previously ruled set-null and asserted in prose that fk_onboarding_flow_sessions_actor was ON DELETE SET NULL. It never was: the migration that created it, the Drizzle declaration and the catalog have all said CASCADE the whole time, so the ruling was documentation that nothing implemented. CASCADE is also the correct behaviour here — the row is per-member state keyed on the membership, and org_id leads the composite key as NOT NULL, so a bare SET NULL would raise 23502 on every removal instead of orphaning anything safely. A grant or preference belonging to nobody is residue, not history.",
  },
  {
    id: "resignations",
    mechanism: "database-cascade",
    table: "resignations",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Added by the actor contraction: the row carries a membership pointer beside its legacy user id. The composite tenant foreign key nulls the pointer on removal so historical display survives, and a suspension is reversible so nothing is written.",
  },
  {
    id: "documents",
    mechanism: "database-cascade",
    table: "documents",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Added by the actor contraction: the row carries a membership pointer beside its legacy user id. The composite tenant foreign key nulls the pointer on removal so historical display survives, and a suspension is reversible so nothing is written.",
  },
  {
    id: "asset_returns",
    mechanism: "database-cascade",
    table: "asset_returns",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Added by the actor contraction: the row carries a membership pointer beside its legacy user id. The composite tenant foreign key nulls the pointer on removal so historical display survives, and a suspension is reversible so nothing is written.",
  },
  {
    id: "assets_assigned_to_membership",
    mechanism: "database-write",
    table: "assets",
    keyedBy: "assigned_to_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "An assigned asset must be returned or reassigned before removal so custody is never silently lost.",
  },
  {
    id: "exit_checklists_assigned_to_membership",
    mechanism: "database-write",
    table: "exit_checklists",
    keyedBy: "assigned_to_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "An exit checklist assignee must be reassigned before removal so offboarding work remains owned.",
  },
  {
    id: "terminations_user_membership",
    mechanism: "database-write",
    table: "terminations",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Termination records are employment history and require explicit preservation or reassignment before removal.",
  },
  {
    id: "alumni_profiles_user_membership",
    mechanism: "database-write",
    table: "alumni_profiles",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "The alumni profile is a tenant-scoped person record and cannot be silently detached during membership removal.",
  },
  {
    id: "background_verifications_user_membership",
    mechanism: "database-write",
    table: "background_verifications",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Background verification ownership requires explicit handling before removal to preserve compliance history.",
  },
  {
    id: "travel_requests_memberships",
    mechanism: "database-write",
    table: "travel_requests",
    keyedBy: "user_membership_id / manager_approver_membership_id / finance_approver_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Travel request ownership and approval authority must be explicitly reassigned or resolved before removal.",
  },
  {
    id: "hr_travel_visit_logs_user_membership",
    mechanism: "database-write",
    table: "hr_travel_visit_logs",
    keyedBy: "user_membership_id",
    onRemoval: "delete",
    onSuspension: "retain",
    reason:
      "The FK on (org_id, user_membership_id) is ON DELETE SET NULL without a column list, so Postgres would attempt to null both org_id (NOT NULL) and user_membership_id, raising 23502. The revocation path must explicitly clear all user_membership_id pointers for this membership before the membership row is removed.",
  },
  {
    id: "hr_legal_holds_subject_membership",
    mechanism: "database-write",
    table: "hr_legal_holds",
    keyedBy: "subject_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "A legal hold subject cannot be silently detached; compliance handling is required before removal.",
  },
  {
    id: "hr_data_requests_subject_membership",
    mechanism: "database-write",
    table: "hr_data_requests",
    keyedBy: "subject_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "A data-request subject requires explicit privacy-workflow handling before membership removal.",
  },
  {
    id: "hr_union_memberships_user_membership",
    mechanism: "database-write",
    table: "hr_union_memberships",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Union membership records are employment data and require explicit handling before removal.",
  },
  {
    id: "hr_accommodation_requests_user_membership",
    mechanism: "database-write",
    table: "hr_accommodation_requests",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Accommodation requests are sensitive employment records and require explicit handling before removal.",
  },
  {
    id: "hr_accommodation_tasks_assignee_membership",
    mechanism: "database-write",
    table: "hr_accommodation_tasks",
    keyedBy: "assignee_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Accommodation task ownership must be reassigned before removal so sensitive work remains owned.",
  },
  {
    id: "hr_emergency_responses_user_membership",
    mechanism: "database-write",
    table: "hr_emergency_responses",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Emergency-response records require explicit continuity and cannot be silently detached on removal.",
  },
  {
    id: "hr_access_provisioning_user_membership",
    mechanism: "database-write",
    table: "hr_access_provisioning",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "revoke",
    reason: "Access-provisioning state controls tenant access and must be revoked on suspension and explicitly resolved before removal.",
  },
  {
    id: "hr_audit_logs_actor_membership",
    mechanism: "database-cascade",
    table: "hr_audit_logs",
    keyedBy: "actor_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Actor attribution on hr_audit_logs is cleared by fk_hr_audit_logs_actor_membership, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
  {
    id: "hr_effective_dated_changes_approved_by_membership",
    mechanism: "database-cascade",
    table: "hr_effective_dated_changes",
    keyedBy: "approved_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Approval attribution on hr_effective_dated_changes is cleared by fk_hr_eff_changes_approved_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
  {
    id: "hr_effective_dated_changes_created_by_membership",
    mechanism: "database-cascade",
    table: "hr_effective_dated_changes",
    keyedBy: "created_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Authorship on hr_effective_dated_changes is cleared by fk_hr_eff_changes_created_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
  {
    id: "hr_employment_history_created_by_membership",
    mechanism: "database-cascade",
    table: "hr_employment_history",
    keyedBy: "created_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Authorship on hr_employment_history is cleared by fk_hr_emp_history_created_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
] as const satisfies readonly MembershipArtifact[];
