import type { MembershipArtifact } from "../membership-artifact.types";

export const HR_PERFORMANCE_AND_ENGAGEMENT_ARTIFACTS = [
  {
    id: "hr_badge_awards_awarded_by_actor",
    mechanism: "database-write",
    table: "hr_badge_awards",
    keyedBy: "awarded_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Award attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "hr_polls_created_by_actor",
    mechanism: "database-write",
    table: "hr_polls",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Poll authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "hr_communities_created_by_actor",
    mechanism: "database-write",
    table: "hr_communities",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Community authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "hr_campaigns_created_by_actor",
    mechanism: "database-write",
    table: "hr_campaigns",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Campaign authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "review_cycles_created_by_actor",
    mechanism: "database-write",
    table: "review_cycles",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Review-cycle authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "pulse_surveys_created_by_actor",
    mechanism: "database-write",
    table: "pulse_surveys",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Survey authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "feedback_requests_subject_actor",
    mechanism: "database-write",
    table: "feedback_requests",
    keyedBy: "subject_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Feedback subject attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "feedback_requests_reviewer_actor",
    mechanism: "database-write",
    table: "feedback_requests",
    keyedBy: "reviewer_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Feedback reviewer attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "skill_assessments_created_by_actor",
    mechanism: "database-write",
    table: "skill_assessments",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Assessment authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "performance_reviews",
    mechanism: "database-cascade",
    table: "performance_reviews",
    keyedBy: "reviewer_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "fk_performance_reviews_reviewer_actor is ON DELETE SET NULL, so performance review records are preserved with the reviewer membership pointer cleared on removal.",
  },
  {
    id: "hr_wellness_checkins",
    mechanism: "database-cascade",
    table: "hr_wellness_checkins",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Added by the actor contraction: the row carries a membership pointer beside its legacy user id. The composite tenant foreign key nulls the pointer on removal so historical display survives, and a suspension is reversible so nothing is written.",
  },
  {
    id: "hr_mood_checkins",
    mechanism: "database-cascade",
    table: "hr_mood_checkins",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "fk_hr_mood_checkins_user_actor is ON DELETE SET NULL, so mood check-in records are preserved with the membership pointer cleared on removal.",
  },
  {
    id: "recognitions",
    mechanism: "database-write",
    table: "recognitions",
    keyedBy: "from_membership_id / to_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason:
      "Both recognition participants are tenant-scoped membership references. Their composite FKs are RESTRICT, so removal must first preserve or detach the recognition without silently changing its recipient.",
  },
  {
    id: "certifications_user_membership",
    mechanism: "database-write",
    table: "certifications",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Certification records are tenant employment history and require explicit handling before membership removal.",
  },
  {
    id: "one_on_one_meetings_memberships",
    mechanism: "database-write",
    table: "one_on_one_meetings",
    keyedBy: "manager_membership_id / employee_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Both participants in a one-on-one are tenant-scoped authority references and require explicit reassignment before removal.",
  },
  {
    id: "goals_user_membership",
    mechanism: "database-write",
    table: "goals",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Goal ownership is operational attribution that must be reassigned or closed before membership removal.",
  },
  {
    id: "performance_improvement_plans_memberships",
    mechanism: "database-write",
    table: "performance_improvement_plans",
    keyedBy: "user_membership_id / manager_membership_id / hr_rep_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "The employee, manager, and HR representative are active plan participants; removal requires explicit reassignment or resolution.",
  },
  {
    id: "enps_scores_user_membership",
    mechanism: "database-write",
    table: "enps_scores",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "The eNPS score belongs to a tenant member and requires explicit handling before removal.",
  },
  {
    id: "employee_skills_user_membership",
    mechanism: "database-write",
    table: "employee_skills",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Employee skill records are person-owned employment data and require explicit preservation or reassignment before removal.",
  },
  {
    id: "assessment_attempts_user_membership",
    mechanism: "database-write",
    table: "assessment_attempts",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Assessment attempts are retained employment history and must not be silently detached on removal.",
  },
  {
    id: "hr_calibration_entries_employee_membership",
    mechanism: "database-write",
    table: "hr_calibration_entries",
    keyedBy: "employee_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Calibration entries are employment records tied to a tenant member and require explicit handling before removal.",
  },
  {
    id: "policy_acknowledgments_user_membership",
    mechanism: "database-write",
    table: "policy_acknowledgments",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Policy acknowledgments are compliance evidence and cannot lose their member association silently.",
  },
  {
    id: "team_event_participants_user_membership",
    mechanism: "database-write",
    table: "team_event_participants",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Team-event participation requires explicit handling before removal to preserve attendance and access history.",
  },
  {
    id: "feedback_cycle_requests_memberships",
    mechanism: "database-write",
    table: "feedback_cycle_requests",
    keyedBy: "subject_membership_id / reviewer_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Feedback-cycle participants require explicit reassignment or closure before removal.",
  },
  {
    id: "announcement_reads_user_membership",
    mechanism: "database-write",
    table: "announcement_reads",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Announcement read state is tenant-scoped member data and requires explicit handling before removal.",
  },
  {
    id: "hr_reward_points_ledger_user_membership",
    mechanism: "database-write",
    table: "hr_reward_points_ledger",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Reward ledger history must retain its member association and be explicitly handled before removal.",
  },
  {
    id: "hr_poll_votes_user_membership",
    mechanism: "database-write",
    table: "hr_poll_votes",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Poll vote ownership is tenant-scoped and requires explicit handling before removal.",
  },
  {
    id: "hr_community_members_user_membership",
    mechanism: "database-write",
    table: "hr_community_members",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Community membership must be explicitly removed or transferred before the organization membership is removed.",
  },
] as const satisfies readonly MembershipArtifact[];
