import type { MembershipArtifact } from "../membership-artifact.types";

export const HR_TIME_AND_ATTENDANCE_ARTIFACTS = [
  {
    id: "wfh_requests",
    mechanism: "database-cascade",
    table: "wfh_requests",
    keyedBy: "approver_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "The composite foreign key on the approver column is ON DELETE SET NULL, so WFH records are preserved with the approver column cleared on membership removal.",
  },
  {
    id: "leave_requests",
    mechanism: "database-cascade",
    table: "leave_requests",
    keyedBy: "approver_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "The composite foreign keys on approver_membership_id, created_by_membership_id and updated_by_membership_id are all ON DELETE SET NULL, so leave records are preserved with the membership columns cleared on removal.",
  },
  {
    id: "hr_attendance_regularizations",
    mechanism: "database-cascade",
    table: "hr_attendance_regularizations",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Added by the actor contraction: the row carries a membership pointer beside its legacy user id. The composite tenant foreign key nulls the pointer on removal so historical display survives, and a suspension is reversible so nothing is written.",
  },
  {
    id: "attendance_user_membership",
    mechanism: "database-cascade",
    table: "attendance",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason: "Attendance history preserves its row while the membership pointer is nulled by the declared SET NULL foreign key.",
  },
  {
    id: "employee_devices_user_membership",
    mechanism: "database-write",
    table: "employee_devices",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "revoke",
    reason: "A device assignment is membership authority and must be explicitly detached before removal and revoked on suspension.",
  },
  {
    id: "leave_balances_user_membership",
    mechanism: "database-write",
    table: "leave_balances",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Leave balances are tenant employment records and must be explicitly settled or reassigned before membership removal.",
  },
  {
    id: "hr_leave_ledger_user_membership",
    mechanism: "database-write",
    table: "hr_leave_ledger",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Leave ledger history is retained and requires an explicit membership-removal decision rather than silently changing attribution.",
  },
  {
    id: "employee_shift_assignments_user_membership",
    mechanism: "database-cascade",
    table: "employee_shift_assignments",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason: "The declared SET NULL foreign key preserves the shift record while clearing the departing member pointer.",
  },
  {
    id: "shift_swap_requests_memberships",
    mechanism: "database-cascade",
    table: "shift_swap_requests",
    keyedBy: "requester_membership_id / target_membership_id / approver_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason: "The declared SET NULL foreign keys preserve the swap history while clearing departed participants.",
  },
  {
    id: "roster_entries_user_membership",
    mechanism: "database-write",
    table: "roster_entries",
    keyedBy: "user_membership_id",
    onRemoval: "delete",
    onSuspension: "retain",
    reason:
      "No FK from roster_entries.user_membership_id to organization_members exists in the live database, so removal is not enforced by the DB. The revocation path must explicitly delete or null all roster_entries for the membership before the membership row is removed.",
  },
  {
    id: "overtime_requests_memberships",
    mechanism: "database-cascade",
    table: "overtime_requests",
    keyedBy: "user_membership_id / approver_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason: "The declared SET NULL foreign keys preserve overtime history while clearing departed participants.",
  },
  {
    id: "comp_off_balances_user_membership",
    mechanism: "database-cascade",
    table: "comp_off_balances",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason: "The declared SET NULL foreign key preserves the balance record while clearing the departed member pointer.",
  },
  {
    id: "biometric_logs_user_membership",
    mechanism: "database-write",
    table: "biometric_logs",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Biometric attendance history is sensitive employment data and requires explicit retention handling before removal.",
  },
  {
    id: "hr_device_employee_mappings_user_membership",
    mechanism: "database-write",
    table: "hr_device_employee_mappings",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "revoke",
    reason: "The device-to-employee mapping grants operational access and must be detached before removal and revoked on suspension.",
  },
  {
    id: "hr_attendance_regularizations_approved_by_membership",
    mechanism: "database-cascade",
    table: "hr_attendance_regularizations",
    keyedBy: "approved_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Approval attribution on hr_attendance_regularizations is cleared by fk_hr_attendance_regularizations_approved_by_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
  {
    id: "hr_attendance_regularizations_rejected_by_membership",
    mechanism: "database-cascade",
    table: "hr_attendance_regularizations",
    keyedBy: "rejected_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Rejection attribution on hr_attendance_regularizations is cleared by fk_hr_attendance_regularizations_rejected_by_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
  {
    id: "leave_requests_covering_employee_membership",
    mechanism: "database-cascade",
    table: "leave_requests",
    keyedBy: "covering_employee_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "The covering-employee pointer on leave_requests is cleared by fk_leave_requests_covering_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
  {
    id: "leave_requests_created_by_membership",
    mechanism: "database-cascade",
    table: "leave_requests",
    keyedBy: "created_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "Authorship on leave_requests is cleared by fk_leave_requests_created_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written. The Drizzle table declares this foreign key as blocking, which is stale against the migration.",
  },
  {
    id: "leave_requests_updated_by_membership",
    mechanism: "database-cascade",
    table: "leave_requests",
    keyedBy: "updated_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "The last-editor pointer on leave_requests is cleared by fk_leave_requests_updated_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written. The Drizzle table declares this foreign key as blocking, which is stale against the migration.",
  },
  {
    id: "leave_requests_user_membership",
    mechanism: "database-cascade",
    table: "leave_requests",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "The member pointer on leave_requests is cleared by fk_leave_requests_user_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
  {
    id: "wfh_requests_user_membership",
    mechanism: "database-cascade",
    table: "wfh_requests",
    keyedBy: "user_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "The member pointer on wfh_requests is cleared by fk_wfh_requests_user_actor, an ON DELETE SET NULL composite tenant foreign key, so the record survives the departure without its member pointer. A suspension is reversible, so nothing is written.",
  },
  {
    id: "hr_leave_policy_template_dismissals_dismissed_by_membership",
    mechanism: "database-cascade",
    table: "hr_leave_policy_template_dismissals",
    keyedBy: "dismissed_by_membership_id",
    onRemoval: "set-null",
    onSuspension: "retain",
    reason:
      "fk_hr_leave_policy_template_dismissals_org_membership is ON DELETE SET NULL (dismissed_by_membership_id), so the organisation's dismissal survives the departure without naming who dismissed it. A suspension is reversible, so nothing is written.",
  },
] as const satisfies readonly MembershipArtifact[];
