import type { MembershipArtifact } from "../membership-artifact.types";

export const RECRUITMENT_ARTIFACTS = [
  {
    id: "candidate_referrals_created_by_actor",
    mechanism: "database-write",
    table: "candidate_referrals",
    keyedBy: "referred_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Referral authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "hiring_flows_created_by_actor",
    mechanism: "database-write",
    table: "hiring_flows",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Hiring-flow authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "scorecard_templates_created_by_actor",
    mechanism: "database-write",
    table: "scorecard_templates",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Scorecard authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "job_postings_posted_by_actor",
    mechanism: "database-write",
    table: "job_postings",
    keyedBy: "posted_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Posting attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "candidate_sources_created_by_actor",
    mechanism: "database-write",
    table: "candidate_sources",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Source authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "interviews_interviewer_actor",
    mechanism: "database-write",
    table: "interviews",
    keyedBy: "interviewer_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Interview attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "interview_scorecards_interviewer_actor",
    mechanism: "database-write",
    table: "interview_scorecards",
    keyedBy: "interviewer_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Scorecard attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "interview_booking_links_created_by_actor",
    mechanism: "database-write",
    table: "interview_booking_links",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Booking-link authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "interview_panel_members_user_actor",
    mechanism: "database-write",
    table: "interview_panel_members",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Panel attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "booking_link_interviewers_user_actor",
    mechanism: "database-write",
    table: "booking_link_interviewers",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Interviewer attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "interview_questions_created_by_actor",
    mechanism: "database-write",
    table: "interview_questions",
    keyedBy: "created_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Question authorship is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "headcount_requests_actor_one",
    mechanism: "database-write",
    table: "headcount_requests",
    keyedBy: "requested_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Headcount attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "headcount_requests_actor_two",
    mechanism: "database-write",
    table: "headcount_requests",
    keyedBy: "approved_by_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Headcount attribution is retained for audit history; departure must explicitly resolve this RESTRICT dependency before removal.",
  },
  {
    id: "interviews",
    mechanism: "database-write",
    table: "interviews",
    keyedBy: "interviewer_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason:
      "The interviewer is an authority-bearing participant. Its composite FK is RESTRICT, so removal must be blocked until the interview is reassigned or archived; suspension remains reversible.",
  },
  {
    id: "interview_scorecards",
    mechanism: "database-write",
    table: "interview_scorecards",
    keyedBy: "interviewer_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason:
      "A scorecard must retain its reviewer attribution. Its composite FK is RESTRICT, so the removal flow must explicitly detach or preserve the record before the membership can be removed.",
  },
  {
    id: "job_recruiters_user_membership",
    mechanism: "database-write",
    table: "job_recruiters",
    keyedBy: "user_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Recruiter assignment is operational authority and requires explicit reassignment before membership removal.",
  },
  {
    id: "job_requisitions_memberships",
    mechanism: "database-write",
    table: "job_requisitions",
    keyedBy: "hiring_manager_membership_id / approver_membership_id",
    onRemoval: "blocks-removal",
    onSuspension: "retain",
    reason: "Hiring authority references must be reassigned or resolved before removal so requisitions remain governed.",
  },
] as const satisfies readonly MembershipArtifact[];
