export const ROLE_SLUG = {
  OWNER: "OWNER",
  CEO: "CEO",
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
  HR: "HR",
  HR_ADMIN: "HR_ADMIN",
  BRANCH_HR: "BRANCH_HR",
  BRANCH_MANAGER: "BRANCH_MANAGER",
  SALES: "SALES",
  SALES_REP: "SALES_REP",
  CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
  ENGINEERING: "ENGINEERING",
  DESIGN: "DESIGN",
  VIDEO_EDITOR: "VIDEO_EDITOR",
  DIGITAL_MARKETING: "DIGITAL_MARKETING",
  BLOG_EDITOR: "BLOG_EDITOR",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  ACCOUNTANT: "ACCOUNTANT",
  RECRUITER: "RECRUITER",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  CRM_ADMIN: "CRM_ADMIN",
  INVENTORY_ADMIN: "INVENTORY_ADMIN",
  PRODUCT_MANAGEMENT_ADMIN: "PRODUCT_MANAGEMENT_ADMIN",
  VIEWER: "VIEWER",
  CLIENT_USER: "CLIENT_USER",
} as const;

export type RoleSlug = (typeof ROLE_SLUG)[keyof typeof ROLE_SLUG];

export const HR_ROLE_SLUGS = [
  ROLE_SLUG.HR,
  ROLE_SLUG.HR_ADMIN,
  ROLE_SLUG.BRANCH_HR,
] as const;

export const FINANCE_ROLE_SLUGS = [ROLE_SLUG.ACCOUNTANT] as const;

export const SALES_ROLE_SLUGS = [ROLE_SLUG.SALES, ROLE_SLUG.SALES_REP] as const;

export const HR_ROLE_SET: ReadonlySet<string> = new Set<string>(HR_ROLE_SLUGS);
export const FINANCE_ROLE_SET: ReadonlySet<string> = new Set<string>(FINANCE_ROLE_SLUGS);
export const SALES_ROLE_SET: ReadonlySet<string> = new Set<string>(SALES_ROLE_SLUGS);
