import type { PayrollTemplateSeed } from "../payroll.types";
import { DEFAULT_PAYROLL_TOGGLES, PAYROLL_TEMPLATE_KEYS } from "../payroll.types";

type PayrollTemplateKey = (typeof PAYROLL_TEMPLATE_KEYS)[number];

export const OT_MULTIPLIER_DEFAULT = "1.50";

const COUNTRY_STANDARD_TOGGLES = {
  ...DEFAULT_PAYROLL_TOGGLES,
  pf: false,
  esi: false,
  professionalTax: false,
  tds: false,
  gratuity: false,
  lwf: false,
  lopFromAttendance: true,
  leaveSync: true,
  bankPayoutFile: true,
  payslipPublishing: true,
  approvalWorkflow: true,
  lockAfterApproval: true,
  payrollVarianceWarnings: true,
};

export const PAYROLL_TEMPLATE_SEEDS: PayrollTemplateSeed[] = [
  {
    key: "INDIAN_STANDARD",
    name: "Indian Standard",
    description: "Full statutory compliance for salaried employees in India: PF, PT, ESI-optional, TDS with declaration mode, and LOP-linked attendance.",
    bestFor: "Mid-size Indian companies with salaried workforce and full statutory obligations",
    complexity: "MODERATE",
    badge: "Most Popular",
    category: "INDIAN_STANDARD",
    isRecommended: true,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: true,
      professionalTax: true,
      tds: true,
      lopFromAttendance: true,
      leaveSync: true,
      employeeDeclarations: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
      payrollVarianceWarnings: true,
      essAllowReimbursements: false,
      essAllowTaxDeclarations: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Salary",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc * 0.40",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "HRA",
        name: "House Rent Allowance",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "50",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "SPECIAL",
        name: "Special Allowance",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc - basic - (basic * 0.50)",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "PF_EMP",
        name: "Provident Fund (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 4,
      },
      {
        code: "PF_ER",
        name: "Provident Fund (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 5,
      },
      {
        code: "PT",
        name: "Professional Tax",
        type: "DEDUCTION",
        calcMethod: "FIXED",
        amount: "200.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pt",
        sortOrder: 6,
      },
      {
        code: "TDS",
        name: "Tax Deducted at Source",
        type: "TAX",
        calcMethod: "MANUAL",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "tds",
        sortOrder: 7,
      },
      {
        code: "LOP",
        name: "Loss of Pay",
        type: "DEDUCTION",
        calcMethod: "ATTENDANCE_BASED",
        formula: "(basic / days_in_month) * lop_days",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 8,
      },
    ],
  },
  {
    key: "INDIAN_STARTUP",
    name: "Indian Startup",
    description: "Lean structure for startup employees with flexible reimbursements, bonuses, and simplified PF compliance.",
    bestFor: "Early-stage and growth startups with tech employees, flexible comp, and reimbursement culture",
    complexity: "MODERATE",
    badge: "Startup Friendly",
    category: "INDIAN_STARTUP",
    isRecommended: true,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: true,
      professionalTax: true,
      tds: true,
      lopFromAttendance: true,
      reimbursements: true,
      bonuses: true,
      employeeDeclarations: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
      payrollVarianceWarnings: true,
      essAllowReimbursements: true,
      essAllowTaxDeclarations: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Salary",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc * 0.40",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "HRA",
        name: "House Rent Allowance",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "50",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "SPECIAL",
        name: "Special Allowance",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc - basic - (basic * 0.50)",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "INTERNET",
        name: "Internet Allowance",
        type: "REIMBURSEMENT",
        calcMethod: "FIXED",
        amount: "1000.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 4,
      },
      {
        code: "TRAVEL",
        name: "Travel Allowance",
        type: "REIMBURSEMENT",
        calcMethod: "FIXED",
        amount: "2000.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 5,
      },
      {
        code: "MEAL",
        name: "Meal Allowance",
        type: "REIMBURSEMENT",
        calcMethod: "FIXED",
        amount: "2200.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 6,
      },
      {
        code: "BONUS",
        name: "Performance Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 7,
      },
      {
        code: "PF_EMP",
        name: "Provident Fund (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 8,
      },
      {
        code: "PF_ER",
        name: "Provident Fund (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 9,
      },
      {
        code: "PT",
        name: "Professional Tax",
        type: "DEDUCTION",
        calcMethod: "FIXED",
        amount: "200.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pt",
        sortOrder: 10,
      },
      {
        code: "LOP",
        name: "Loss of Pay",
        type: "DEDUCTION",
        calcMethod: "ATTENDANCE_BASED",
        formula: "(basic / days_in_month) * lop_days",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 11,
      },
    ],
  },
  {
    key: "CONTRACTOR",
    name: "Contractor",
    description: "Minimal structure for independent contractors: contract fee with 10% TDS withholding; statutory deductions off.",
    bestFor: "Freelancers, consultants, and independent contractors billed on a fixed or daily rate",
    complexity: "SIMPLE",
    badge: "Contractor Ready",
    category: "CONTRACTOR",
    isRecommended: false,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: false,
      esi: false,
      professionalTax: false,
      tds: true,
      lopFromAttendance: false,
      leaveSync: false,
      timesheets: false,
      contractorPayments: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
    },
    defaultComponents: [
      {
        code: "CONTRACT_FEE",
        name: "Contract Fee",
        type: "EARNING",
        calcMethod: "FIXED",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "TDS",
        name: "TDS Withholding (Sec 194C)",
        type: "TAX",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "10",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "tds",
        sortOrder: 2,
      },
    ],
  },
  {
    key: "SALES_INCENTIVE",
    name: "Sales Incentive",
    description: "Fixed base plus variable commission and clawback support. Designed for quota-carrying sales roles.",
    bestFor: "Sales teams, BDRs, account executives, and commission-based field staff",
    complexity: "ADVANCED",
    badge: "Sales Optimized",
    category: "SALES_INCENTIVE",
    isRecommended: true,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: true,
      professionalTax: true,
      tds: true,
      lopFromAttendance: true,
      salesIncentives: true,
      incentives: true,
      manualAdjustments: true,
      employeeDeclarations: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
      payrollVarianceWarnings: true,
      essAllowTaxDeclarations: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Salary",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc * 0.40",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "HRA",
        name: "House Rent Allowance",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "50",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "SPECIAL",
        name: "Special Allowance",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc - basic - (basic * 0.50)",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "INCENTIVE",
        name: "Variable Incentive",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 4,
      },
      {
        code: "COMMISSION",
        name: "Sales Commission",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "incentive_amount * 0.05",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 5,
      },
      {
        code: "PF_EMP",
        name: "Provident Fund (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 6,
      },
      {
        code: "PF_ER",
        name: "Provident Fund (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 7,
      },
      {
        code: "TDS",
        name: "Tax Deducted at Source",
        type: "TAX",
        calcMethod: "MANUAL",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "tds",
        sortOrder: 8,
      },
      {
        code: "CLAWBACK",
        name: "Incentive Clawback",
        type: "ADJUSTMENT",
        calcMethod: "MANUAL",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 9,
      },
      {
        code: "LOP",
        name: "Loss of Pay",
        type: "DEDUCTION",
        calcMethod: "ATTENDANCE_BASED",
        formula: "(basic / days_in_month) * lop_days",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 10,
      },
    ],
  },
  {
    key: "GLOBAL_REMOTE",
    name: "Global Remote",
    description: "Multi-currency contractor support with country compliance checklists and global payment reporting.",
    bestFor: "Fully remote distributed teams, global contractors, and multi-country payroll operations",
    complexity: "ADVANCED",
    badge: "Global Ready",
    category: "GLOBAL_REMOTE",
    isRecommended: false,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: false,
      esi: false,
      professionalTax: false,
      tds: true,
      lopFromAttendance: false,
      contractorPayments: true,
      multiCurrency: true,
      reimbursements: true,
      bonuses: true,
      countryComplianceChecklist: true,
      globalPaymentReport: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
      essAllowReimbursements: true,
    },
    defaultComponents: [
      {
        code: "CONTRACT_FEE",
        name: "Contract Fee",
        type: "EARNING",
        calcMethod: "FIXED",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "INTERNET",
        name: "Internet / Home Office Allowance",
        type: "REIMBURSEMENT",
        calcMethod: "FIXED",
        amount: "100.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "TRAVEL",
        name: "Travel Allowance",
        type: "REIMBURSEMENT",
        calcMethod: "FIXED",
        amount: "200.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "BONUS",
        name: "Performance Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 4,
      },
      {
        code: "TDS",
        name: "Tax Withholding",
        type: "TAX",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "10",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "tds",
        sortOrder: 5,
      },
    ],
  },
  {
    key: "HOURLY",
    name: "Hourly / Timesheet",
    description: "Timesheet-driven earnings with overtime multiplier. Ideal for hourly workers billed on actual hours worked.",
    bestFor: "Part-time workers, hourly contract staff, and project-based billing by the hour",
    complexity: "MODERATE",
    badge: null,
    category: "HOURLY",
    isRecommended: false,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: true,
      professionalTax: true,
      tds: true,
      timesheets: true,
      overtime: true,
      lopFromAttendance: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Wages",
        type: "EARNING",
        calcMethod: "TIMESHEET_BASED",
        formula: "(basic / days_in_month / 8) * paid_days * 8",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "OT",
        name: "Overtime Pay",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: `(basic / days_in_month / 8) * overtime_hours * ${OT_MULTIPLIER_DEFAULT}`,
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "PF_EMP",
        name: "Provident Fund (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 3,
      },
      {
        code: "PF_ER",
        name: "Provident Fund (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 4,
      },
      {
        code: "PT",
        name: "Professional Tax",
        type: "DEDUCTION",
        calcMethod: "FIXED",
        amount: "200.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pt",
        sortOrder: 5,
      },
      {
        code: "TDS",
        name: "Tax Deducted at Source",
        type: "TAX",
        calcMethod: "MANUAL",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "tds",
        sortOrder: 6,
      },
    ],
  },
  {
    key: "MANUFACTURING",
    name: "Manufacturing",
    description: "Shift-based and overtime-heavy payroll with full ESI + PF compliance. Covers hourly overtime at 1.5x.",
    bestFor: "Factory workers, plant staff, and blue-collar manufacturing employees",
    complexity: "ADVANCED",
    badge: null,
    category: "MANUFACTURING",
    isRecommended: false,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: true,
      esi: true,
      professionalTax: true,
      tds: true,
      overtime: true,
      lopFromAttendance: true,
      leaveSync: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
      payrollVarianceWarnings: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Wages",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc * 0.40",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "HRA",
        name: "House Rent Allowance",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "50",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "SPECIAL",
        name: "Special Allowance",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc - basic - (basic * 0.50)",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "OT",
        name: "Overtime Pay",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: `(basic / days_in_month / 8) * overtime_hours * ${OT_MULTIPLIER_DEFAULT}`,
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 4,
      },
      {
        code: "ESI_EMP",
        name: "ESI (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "0.75",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "esi",
        sortOrder: 5,
      },
      {
        code: "ESI_ER",
        name: "ESI (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "3.25",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "esi",
        sortOrder: 6,
      },
      {
        code: "PF_EMP",
        name: "Provident Fund (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 7,
      },
      {
        code: "PF_ER",
        name: "Provident Fund (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 8,
      },
      {
        code: "PT",
        name: "Professional Tax",
        type: "DEDUCTION",
        calcMethod: "FIXED",
        amount: "200.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pt",
        sortOrder: 9,
      },
      {
        code: "TDS",
        name: "Tax Deducted at Source",
        type: "TAX",
        calcMethod: "MANUAL",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "tds",
        sortOrder: 10,
      },
      {
        code: "LOP",
        name: "Loss of Pay",
        type: "DEDUCTION",
        calcMethod: "ATTENDANCE_BASED",
        formula: "(basic / days_in_month) * lop_days",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 11,
      },
    ],
  },
  {
    key: "STAFFING",
    name: "Staffing Agency",
    description: "Optimized for staffing and workforce placement agencies with ESI + PF coverage and simplified comp structure.",
    bestFor: "Staffing agencies, workforce BPOs, and temp/contract deployment companies",
    complexity: "MODERATE",
    badge: null,
    category: "STAFFING",
    isRecommended: false,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: true,
      esi: true,
      professionalTax: true,
      tds: true,
      lopFromAttendance: true,
      leaveSync: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
      payrollVarianceWarnings: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Wages",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc * 0.35",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "HRA",
        name: "House Rent Allowance",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "40",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "SPECIAL",
        name: "Special Allowance",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc - basic - (basic * 0.40)",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "ESI_EMP",
        name: "ESI (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "0.75",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "esi",
        sortOrder: 4,
      },
      {
        code: "ESI_ER",
        name: "ESI (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "3.25",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "esi",
        sortOrder: 5,
      },
      {
        code: "PF_EMP",
        name: "Provident Fund (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 6,
      },
      {
        code: "PF_ER",
        name: "Provident Fund (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 7,
      },
      {
        code: "PT",
        name: "Professional Tax",
        type: "DEDUCTION",
        calcMethod: "FIXED",
        amount: "200.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pt",
        sortOrder: 8,
      },
      {
        code: "TDS",
        name: "Tax Deducted at Source",
        type: "TAX",
        calcMethod: "MANUAL",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "tds",
        sortOrder: 9,
      },
      {
        code: "LOP",
        name: "Loss of Pay",
        type: "DEDUCTION",
        calcMethod: "ATTENDANCE_BASED",
        formula: "(basic / days_in_month) * lop_days",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 10,
      },
    ],
  },
  {
    key: "EXECUTIVE",
    name: "Executive / Senior Leadership",
    description: "High fixed compensation with performance bonuses, retention bonus, gratuity provisioning, and full declaration support.",
    bestFor: "C-suite, VPs, directors, and senior leadership with complex compensation and tax needs",
    complexity: "ADVANCED",
    badge: "Executive",
    category: "EXECUTIVE",
    isRecommended: false,
    defaultToggles: {
      ...DEFAULT_PAYROLL_TOGGLES,
      pf: true,
      gratuity: true,
      professionalTax: true,
      tds: true,
      lopFromAttendance: true,
      bonuses: true,
      manualAdjustments: true,
      employeeDeclarations: true,
      bankPayoutFile: true,
      payslipPublishing: true,
      approvalWorkflow: true,
      lockAfterApproval: true,
      payrollVarianceWarnings: true,
      essShowSalaryStructure: true,
      essAllowTaxDeclarations: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Salary",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc * 0.40",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "HRA",
        name: "House Rent Allowance",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "50",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "SPECIAL",
        name: "Special Allowance",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc - basic - (basic * 0.50)",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "BONUS",
        name: "Performance Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 4,
      },
      {
        code: "RETENTION_BONUS",
        name: "Retention Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 5,
      },
      {
        code: "PF_EMP",
        name: "Provident Fund (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 6,
      },
      {
        code: "PF_ER",
        name: "Provident Fund (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "pf",
        sortOrder: 7,
      },
      {
        code: "GRATUITY_ER",
        name: "Gratuity Provision (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "4.81",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "gratuity",
        sortOrder: 8,
      },
      {
        code: "PT",
        name: "Professional Tax",
        type: "DEDUCTION",
        calcMethod: "FIXED",
        amount: "200.00",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pt",
        sortOrder: 9,
      },
      {
        code: "TDS",
        name: "Tax Deducted at Source",
        type: "TAX",
        calcMethod: "MANUAL",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "tds",
        sortOrder: 10,
      },
      {
        code: "LOP",
        name: "Loss of Pay",
        type: "DEDUCTION",
        calcMethod: "ATTENDANCE_BASED",
        formula: "(basic / days_in_month) * lop_days",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 11,
      },
    ],
  },
  {
    key: "US_STANDARD" as PayrollTemplateKey,
    name: "US Standard Payroll",
    description: "FICA (Social Security + Medicare), Federal Withholding, and 401(k) placeholder for US salaried employees.",
    bestFor: "US-based companies with salaried W-2 employees requiring FICA and federal withholding compliance",
    complexity: "MODERATE",
    badge: "US",
    category: "COUNTRY_STANDARD",
    isRecommended: false,
    defaultToggles: {
      ...COUNTRY_STANDARD_TOGGLES,
      bonuses: true,
      reimbursements: true,
      employeeDeclarations: false,
      essAllowReimbursements: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Base Salary",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "100",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "BONUS",
        name: "Performance Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "K401_EMP",
        name: "401(k) Employee Contribution",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "0",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "SS_EMP",
        name: "Social Security (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "6.2",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "ss",
        sortOrder: 4,
      },
      {
        code: "SS_ER",
        name: "Social Security (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "6.2",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "ss",
        sortOrder: 5,
      },
      {
        code: "MEDICARE_EMP",
        name: "Medicare (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "1.45",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "medicare",
        sortOrder: 6,
      },
      {
        code: "MEDICARE_ER",
        name: "Medicare (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "1.45",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "medicare",
        sortOrder: 7,
      },
      {
        code: "FWT",
        name: "Federal Withholding Tax",
        type: "TAX",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "fwt",
        sortOrder: 8,
      },
    ],
  },
  {
    key: "UK_STANDARD" as PayrollTemplateKey,
    name: "UK Standard Payroll",
    description: "PAYE income tax withholding, National Insurance (employee and employer), and workplace pension auto-enrolment for UK employees.",
    bestFor: "UK-registered employers running payroll for PAYE employees with full RTI compliance",
    complexity: "MODERATE",
    badge: "UK",
    category: "COUNTRY_STANDARD",
    isRecommended: false,
    defaultToggles: {
      ...COUNTRY_STANDARD_TOGGLES,
      bonuses: true,
      reimbursements: true,
      essAllowReimbursements: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Base Salary",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "100",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "BONUS",
        name: "Performance Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "PAYE",
        name: "PAYE Income Tax",
        type: "TAX",
        calcMethod: "FORMULA",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "paye",
        sortOrder: 3,
      },
      {
        code: "NI_EMP",
        name: "National Insurance (Employee)",
        type: "DEDUCTION",
        calcMethod: "FORMULA",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "ni_emp",
        sortOrder: 4,
      },
      {
        code: "NI_ER",
        name: "National Insurance (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "FORMULA",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "ni_er",
        sortOrder: 5,
      },
      {
        code: "PENSION_AE_EMP",
        name: "Workplace Pension (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "5",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "pension_ae",
        sortOrder: 6,
      },
      {
        code: "PENSION_AE_ER",
        name: "Workplace Pension (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "3",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "pension_ae",
        sortOrder: 7,
      },
    ],
  },
  {
    key: "UAE_STANDARD" as PayrollTemplateKey,
    name: "UAE Standard Payroll",
    description: "Typical UAE salary structure (Basic + Housing + Transport allowances) with no income tax, WPS-compliant payout, and gratuity accrual.",
    bestFor: "UAE-registered entities running payroll for expatriate and national employees in WPS-compliant environments",
    complexity: "SIMPLE",
    badge: "UAE",
    category: "COUNTRY_STANDARD",
    isRecommended: false,
    defaultToggles: {
      ...COUNTRY_STANDARD_TOGGLES,
      bonuses: true,
      reimbursements: true,
      gratuity: false,
      essAllowReimbursements: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Salary",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "100",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "HOUSING",
        name: "Housing Allowance",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc * 0.25",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "TRANSPORT",
        name: "Transport Allowance",
        type: "EARNING",
        calcMethod: "FORMULA",
        formula: "ctc * 0.10",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "BONUS",
        name: "Performance Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 4,
      },
      {
        code: "GPSSA_EMP",
        name: "GPSSA Pension (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "5",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "gpssa",
        sortOrder: 5,
      },
      {
        code: "GPSSA_ER",
        name: "GPSSA Pension (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "12.5",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "gpssa",
        sortOrder: 6,
      },
    ],
  },
  {
    key: "SG_STANDARD" as PayrollTemplateKey,
    name: "SG Standard Payroll",
    description: "CPF contributions (employee 20% + employer 17% on ordinary wages), itemized payslip, and annual AWS bonus provision for Singapore employees.",
    bestFor: "Singapore-registered companies employing Singapore citizens and permanent residents",
    complexity: "MODERATE",
    badge: "SG",
    category: "COUNTRY_STANDARD",
    isRecommended: false,
    defaultToggles: {
      ...COUNTRY_STANDARD_TOGGLES,
      bonuses: true,
      reimbursements: true,
      essAllowReimbursements: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Basic Salary",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "100",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "AWS_BONUS",
        name: "Annual Wage Supplement (AWS)",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "BONUS",
        name: "Performance Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 3,
      },
      {
        code: "CPF_EMP",
        name: "CPF (Employee)",
        type: "DEDUCTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "20",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "cpf",
        sortOrder: 4,
      },
      {
        code: "CPF_ER",
        name: "CPF (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "17",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "cpf",
        sortOrder: 5,
      },
    ],
  },
  {
    key: "AU_STANDARD" as PayrollTemplateKey,
    name: "AU Standard Payroll",
    description: "PAYG withholding, Superannuation Guarantee (12%), and Single Touch Payroll compliant structure for Australian employees.",
    bestFor: "Australian businesses running payroll for permanent and casual employees under STP Phase 2",
    complexity: "MODERATE",
    badge: "AU",
    category: "COUNTRY_STANDARD",
    isRecommended: false,
    defaultToggles: {
      ...COUNTRY_STANDARD_TOGGLES,
      bonuses: true,
      reimbursements: true,
      overtime: true,
      essAllowReimbursements: true,
    },
    defaultComponents: [
      {
        code: "BASIC",
        name: "Base Salary",
        type: "EARNING",
        calcMethod: "PERCENT_OF_BASIC",
        percent: "100",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: false,
        sortOrder: 1,
      },
      {
        code: "BONUS",
        name: "Performance Bonus",
        type: "EARNING",
        calcMethod: "MANUAL",
        taxable: true,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: false,
        sortOrder: 2,
      },
      {
        code: "PAYG",
        name: "PAYG Withholding",
        type: "TAX",
        calcMethod: "FORMULA",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: false,
        isStatutory: true,
        statutoryKey: "payg",
        sortOrder: 3,
      },
      {
        code: "SUPER_ER",
        name: "Superannuation Guarantee (Employer)",
        type: "EMPLOYER_CONTRIBUTION",
        calcMethod: "PERCENT_OF_GROSS",
        percent: "12",
        taxable: false,
        showOnPayslip: true,
        includeInCtc: true,
        isStatutory: true,
        statutoryKey: "super",
        sortOrder: 4,
      },
    ],
  },
];
