import {
  check,
  column as c,
  foreignKey,
  index as i,
  key,
  triggerFunction as f,
  type FileDefinitionRequirement,
  type FunctionRequirement,
} from "./bundle-definition-types";
import { functionBodyHashes } from "./bundle-function-hashes";
import {
  columns0000,
  exactColumnRelations0000,
} from "./bundle-columns-0000";

const sqlFunction = (
  name: string,
  argumentTypes: string[],
  resultType: string,
): FunctionRequirement => ({
  name,
  argumentTypes,
  resultType,
  language: "sql",
  securityDefiner: false,
  volatility: "i",
  strict: true,
  publicExecute: true,
  bodySha256: functionBodyHashes(name),
});

export const definitions0000: FileDefinitionRequirement = {
  columns: [
    ...columns0000,
    c("organization_people", "row_version", "integer", true, "1"),
    c("organization_people", "archived_at", "timestamp with time zone"),
    c("organization_people", "archived_by_membership_id", "integer"),
    c("organization_people", "updated_by_membership_id", "integer"),
    c("workers", "row_version", "integer", true, "1"),
    c("workers", "created_by_membership_id", "integer"),
    c("workers", "updated_by_membership_id", "integer"),
    c("workers", "archived_at", "timestamp with time zone"),
    c("workers", "archived_by_membership_id", "integer"),
    c("worker_engagements", "row_version", "integer", true, "1"),
    c("worker_engagements", "created_by_membership_id", "integer"),
    c("worker_engagements", "updated_by_membership_id", "integer"),
    c("worker_engagements", "archived_at", "timestamp with time zone"),
    c("worker_engagements", "archived_by_membership_id", "integer"),
    c("hr_people", "organization_person_id", "text"),
    c("hr_people", "row_version", "integer", true, "1"),
    c("hr_people", "archived_at", "timestamp with time zone"),
    c("hr_people", "archived_by_membership_id", "integer"),
    c("hr_people", "updated_by_membership_id", "integer"),
    c("hr_employments", "worker_id", "text"),
    c("hr_employments", "worker_engagement_id", "text"),
    c("hr_employments", "row_version", "integer", true, "1"),
    c("hr_employments", "archived_at", "timestamp with time zone"),
    c("hr_employments", "archived_by_membership_id", "integer"),
    c("hr_employments", "updated_by_membership_id", "integer"),
  ],
  exactColumnRelations: exactColumnRelations0000,
  ownerOnlyRelations: [],
  constraints: [
    key("app.hrms_sql_bundle_operations", "hrms_sql_bundle_operations_pkey", "primary", ["operation_id"]),
    key("hrms_migration_profiles", "hrms_migration_profiles_pkey", "primary", ["organization_id"]),
    foreignKey("hrms_migration_profiles", "hrms_migration_profiles_organization_id_fkey", ["organization_id"], "organizations", ["id"]),
    foreignKey("hrms_migration_profiles", "hrms_migration_profiles_changed_by_platform_user_id_fkey", ["changed_by_platform_user_id"], "users", ["id"]),
    foreignKey("hrms_migration_profile_events", "hrms_migration_profile_events_organization_id_fkey", ["organization_id"], "hrms_migration_profiles", ["organization_id"]),
    key("hrms_scope_versions", "hrms_scope_versions_pkey", "primary", ["organization_id"]),
    foreignKey("hrms_scope_versions", "hrms_scope_versions_organization_id_fkey", ["organization_id"], "organizations", ["id"]),
    foreignKey("hr_person_legacy_map", "hr_person_legacy_map_org_id_fkey", ["org_id"], "organizations", ["id"]),
    foreignKey("hr_employment_legacy_map", "hr_employment_legacy_map_org_id_fkey", ["org_id"], "organizations", ["id"]),
    key("hr_workforce_reconciliation_items", "hr_workforce_reconciliation_items_pkey", "primary", ["reconciliation_item_id"]),
    foreignKey("hr_workforce_reconciliation_items", "hr_workforce_reconciliation_items_org_id_fkey", ["org_id"], "organizations", ["id"]),
    foreignKey("hr_workforce_reconciliation_items", "hr_workforce_reconciliation_items_source_user_id_fkey", ["source_user_id"], "users", ["id"]),
    key("workers", "uniq_workers_org_person_worker", "unique", ["organization_id", "organization_person_id", "worker_id"]),
    key("worker_engagements", "uniq_worker_engagements_org_worker_engagement", "unique", ["organization_id", "worker_id", "worker_engagement_id"]),
    key("hr_people", "uniq_hr_people_org_id", "unique", ["org_id", "id"]),
    key("hr_employments", "uniq_hr_employments_org_id", "unique", ["org_id", "id"]),
    key("hr_employments", "uniq_hr_employments_org_id_person", "unique", ["org_id", "id", "person_id"]),
    key("worker_engagements", "uniq_worker_engagements_org_engagement", "unique", ["organization_id", "worker_engagement_id"]),
    check(
      "app.hrms_sql_bundle_operations",
      "chk_hrms_sql_bundle_operations_identity",
      "char_length(operation_id) BETWEEN 3 AND 512 " +
      "AND operation_id ~ '^[A-Za-z0-9][A-Za-z0-9_.:@/-]*$' " +
      "AND char_length(bundle_id) BETWEEN 3 AND 129 " +
      "AND bundle_id ~ '^[A-Za-z0-9][A-Za-z0-9_.:@-]*$' " +
      "AND file_name IN ('0000_hrms_profiles_workforce.sql', '0001_hrms_effective_history.sql', '0002_hrms_leave_ledger.sql', '0003_hrms_attendance_events.sql', '0004_hrms_hierarchy_audit.sql') " +
      "AND char_length(database_name) BETWEEN 1 AND 63 " +
      "AND database_name ~ '^[A-Za-z0-9_][A-Za-z0-9_.-]*$' " +
      "AND char_length(database_role) BETWEEN 1 AND 63 " +
      "AND database_role ~ '^[A-Za-z0-9_][A-Za-z0-9_.-]*$'",
    ),
    check("app.hrms_sql_bundle_operations", "chk_hrms_sql_bundle_operations_hashes", "sql_hash ~ '^[0-9a-f]{64}$' AND manifest_hash ~ '^[0-9a-f]{64}$' AND root_migration_hash ~ '^[0-9a-f]{64}$'"),
    check("app.hrms_sql_bundle_operations", "chk_hrms_sql_bundle_operations_state", "state IN ('RUNNING', 'VERIFYING', 'COMPLETE', 'FAILED', 'ROLLED_BACK')"),
    check("app.hrms_sql_bundle_operations", "chk_hrms_sql_bundle_operations_attempts", "attempts > 0"),
    check("app.hrms_sql_bundle_operations", "chk_hrms_sql_bundle_operations_server_version", "server_version_num > 0"),
    check("app.hrms_sql_bundle_operations", "chk_hrms_sql_bundle_operations_error", "last_error IS NULL OR last_error ~ '^[A-Z][A-Z0-9_.:-]{0,255}$'"),
    check("app.hrms_sql_bundle_operations", "chk_hrms_sql_bundle_operations_timestamps", "completed_at IS NULL OR completed_at >= started_at"),
    check("app.hrms_sql_bundle_operations", "chk_hrms_sql_bundle_operations_shape", "( state IN ('RUNNING', 'VERIFYING') AND completed_at IS NULL AND last_error IS NULL ) OR ( state IN ('COMPLETE', 'ROLLED_BACK') AND completed_at IS NOT NULL AND last_error IS NULL ) OR ( state = 'FAILED' AND completed_at IS NOT NULL AND last_error IS NOT NULL )"),
    check("hrms_migration_profiles", "chk_hrms_profile_revision", "profile_revision > 0"),
    check("hrms_migration_profiles", "chk_hrms_profile_sensitive_adapter_version", "minimum_sensitive_adapter_version > 0"),
    check("hrms_migration_profiles", "chk_hrms_profile_workforce_modes", "(workforce_read_mode, workforce_write_mode) IN ( ('LEGACY', 'LEGACY'), ('LEGACY', 'DUAL'), ('SHADOW', 'DUAL'), ('CANONICAL', 'CANONICAL_WITH_PROJECTION') )"),
    check("hrms_migration_profiles", "chk_hrms_profile_history_mode", "history_mode IN ('LEGACY', 'DUAL', 'EFFECTIVE')"),
    check("hrms_migration_profiles", "chk_hrms_profile_hierarchy_modes", "(hierarchy_read_mode, hierarchy_write_mode) IN ( ('ADJACENCY', 'LEGACY_ADAPTER'), ('SHADOW_CLOSURE', 'LOCKED_COMMAND'), ('CLOSURE', 'LOCKED_COMMAND') )"),
    check("hrms_migration_profiles", "chk_hrms_profile_attendance_modes", "(attendance_read_mode, attendance_write_mode) IN ( ('LEGACY', 'LEGACY'), ('LEGACY', 'DUAL'), ('SHADOW', 'DUAL'), ('EVENT', 'EVENT_WITH_PROJECTION') )"),
    check("hrms_migration_profiles", "chk_hrms_profile_leave_modes", "(leave_read_mode, leave_write_mode) IN ( ('LEGACY', 'LEGACY'), ('LEGACY', 'DUAL'), ('SHADOW', 'DUAL'), ('LEDGER', 'LEDGER_WITH_PROJECTION') )"),
    check("hrms_migration_profiles", "chk_hrms_profile_sensitive_modes", "(sensitive_read_mode, sensitive_write_mode) IN ( ('LEGACY_ADAPTER', 'LEGACY'), ('LEGACY_ADAPTER', 'DUAL_ENCRYPTED'), ('SHADOW_ENCRYPTED', 'DUAL_ENCRYPTED'), ('ENCRYPTED', 'ENCRYPTED'), ('SHADOW_ENCRYPTED', 'ENCRYPTED'), ('LEGACY_ADAPTER', 'ENCRYPTED') )"),
    check("hrms_migration_profiles", "chk_hrms_profile_sensitive_retirement", "(sensitive_write_mode = 'LEGACY') = (sensitive_plaintext_writes_retired_at IS NULL)"),
    check("hrms_migration_profiles", "chk_hrms_profile_change_metadata", "(change_ticket IS NULL OR btrim(change_ticket) <> '') AND (change_reason IS NULL OR btrim(change_reason) <> '') AND ( profile_revision = 1 OR ( changed_by_platform_user_id IS NOT NULL AND change_ticket IS NOT NULL AND change_reason IS NOT NULL ) )"),
    check("hrms_migration_profiles", "chk_hrms_profile_initial_state", "profile_revision <> 1 OR ( workforce_read_mode = 'LEGACY' AND workforce_write_mode = 'LEGACY' AND history_mode = 'LEGACY' AND hierarchy_read_mode = 'ADJACENCY' AND hierarchy_write_mode = 'LEGACY_ADAPTER' AND attendance_read_mode = 'LEGACY' AND attendance_write_mode = 'LEGACY' AND leave_read_mode = 'LEGACY' AND leave_write_mode = 'LEGACY' AND sensitive_read_mode = 'LEGACY_ADAPTER' AND sensitive_write_mode = 'LEGACY' AND sensitive_plaintext_writes_retired_at IS NULL )"),
    key("hrms_migration_profile_events", "pk_hrms_migration_profile_events", "primary", ["organization_id", "profile_revision"]),
    check("hrms_migration_profile_events", "chk_hrms_profile_events_revision", "profile_revision > 1"),
    check("hrms_migration_profile_events", "chk_hrms_profile_events_distinct_actors", "proposed_by_platform_user_id <> approved_by_platform_user_id"),
    check("hrms_migration_profile_events", "chk_hrms_profile_events_actor_snapshots", "btrim(proposed_by_platform_user_id) <> '' AND btrim(approved_by_platform_user_id) <> ''"),
    check("hrms_migration_profile_events", "chk_hrms_profile_events_manifest_hash", "btrim(manifest_hash) <> ''"),
    check("hrms_migration_profile_events", "chk_hrms_profile_events_before_modes", "app.hrms_modes_valid(before_modes)"),
    check("hrms_migration_profile_events", "chk_hrms_profile_events_after_modes", "app.hrms_modes_valid(after_modes)"),
    check("hrms_scope_versions", "chk_hrms_scope_revision", "scope_revision > 0"),
    key("hr_person_legacy_map", "pk_hr_person_legacy_map", "primary", ["org_id", "hr_person_id"]),
    key("hr_person_legacy_map", "uniq_hr_person_legacy_map_org_person", "unique", ["org_id", "organization_person_id"]),
    key("hr_person_legacy_map", "uniq_hr_person_legacy_map_chain", "unique", ["org_id", "hr_person_id", "organization_person_id"]),
    foreignKey("hr_person_legacy_map", "fk_hr_person_legacy_map_hr_person", ["org_id", "hr_person_id"], "hr_people", ["org_id", "id"], { deferrable: true, matchType: "f" }),
    foreignKey("hr_person_legacy_map", "fk_hr_person_legacy_map_org_person", ["org_id", "organization_person_id"], "organization_people", ["organization_id", "organization_person_id"], { deferrable: true, matchType: "f" }),
    foreignKey("hr_person_legacy_map", "fk_hr_person_legacy_map_created_actor", ["org_id", "created_by_membership_id"], "organization_members", ["org_id", "id"], { matchType: "f" }),
    foreignKey("hr_person_legacy_map", "fk_hr_person_legacy_map_updated_actor", ["org_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"], { matchType: "f" }),
    check("hr_person_legacy_map", "chk_hr_person_legacy_map_row_version", "row_version > 0"),
    key("hr_employment_legacy_map", "pk_hr_employment_legacy_map", "primary", ["org_id", "hr_employment_id"]),
    key("hr_employment_legacy_map", "uniq_hr_employment_legacy_map_engagement", "unique", ["org_id", "worker_engagement_id"]),
    foreignKey("hr_employment_legacy_map", "fk_hr_employment_legacy_map_hr_employment", ["org_id", "hr_employment_id", "hr_person_id"], "hr_employments", ["org_id", "id", "person_id"], { deferrable: true, matchType: "f" }),
    foreignKey("hr_employment_legacy_map", "fk_hr_employment_legacy_map_person_map", ["org_id", "hr_person_id", "organization_person_id"], "hr_person_legacy_map", ["org_id", "hr_person_id", "organization_person_id"], { deferrable: true, matchType: "f" }),
    foreignKey("hr_employment_legacy_map", "fk_hr_employment_legacy_map_worker", ["org_id", "organization_person_id", "worker_id"], "workers", ["organization_id", "organization_person_id", "worker_id"], { deferrable: true, matchType: "f" }),
    foreignKey("hr_employment_legacy_map", "fk_hr_employment_legacy_map_engagement", ["org_id", "worker_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"], { deferrable: true, matchType: "f" }),
    foreignKey("hr_employment_legacy_map", "fk_hr_employment_legacy_map_created_actor", ["org_id", "created_by_membership_id"], "organization_members", ["org_id", "id"], { matchType: "f" }),
    foreignKey("hr_employment_legacy_map", "fk_hr_employment_legacy_map_updated_actor", ["org_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"], { matchType: "f" }),
    check("hr_employment_legacy_map", "chk_hr_employment_legacy_map_row_version", "row_version > 0"),
    key("hr_workforce_reconciliation_items", "uniq_hr_workforce_reconciliation_org_id", "unique", ["org_id", "reconciliation_item_id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_source_membership", ["org_id", "source_membership_id"], "organization_members", ["org_id", "id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_source_person", ["org_id", "source_organization_person_id"], "organization_people", ["organization_id", "organization_person_id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_source_worker", ["org_id", "source_organization_person_id", "source_worker_id"], "workers", ["organization_id", "organization_person_id", "worker_id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_source_engagement", ["org_id", "source_worker_id", "source_worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_source_hr_person", ["org_id", "source_hr_person_id"], "hr_people", ["org_id", "id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_source_hr_employment", ["org_id", "source_hr_employment_id", "source_hr_person_id"], "hr_employments", ["org_id", "id", "person_id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_resolved_person", ["org_id", "resolved_organization_person_id"], "organization_people", ["organization_id", "organization_person_id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_resolved_worker", ["org_id", "resolved_organization_person_id", "resolved_worker_id"], "workers", ["organization_id", "organization_person_id", "worker_id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_resolved_engagement", ["org_id", "resolved_worker_id", "resolved_worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_prepared_actor", ["org_id", "prepared_by_membership_id"], "organization_members", ["org_id", "id"]),
    foreignKey("hr_workforce_reconciliation_items", "fk_hr_workforce_reconciliation_approved_actor", ["org_id", "approved_by_membership_id"], "organization_members", ["org_id", "id"]),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_status", "status IN ('OPEN', 'PREPARED', 'APPROVED')"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_issue_kind", "issue_kind IN ('CLASSIFICATION', 'IDENTITY_CONFLICT', 'FIELD_MISMATCH', 'PII_ATTRIBUTION')"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_classification", "classification IS NULL OR classification IN ('ACCESS_ONLY', 'PERSON_ONLY', 'WORKFORCE_SUBJECT', 'LEGACY_COMPATIBILITY_SUBJECT')"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_nonblank_source", "btrim(batch_id) <> '' AND btrim(source_fingerprint) <> '' AND btrim(source_snapshot_hash) <> '' AND (field_code IS NULL OR btrim(field_code) <> '')"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_nonblank_resolution", "(reason_code IS NULL OR btrim(reason_code) <> '') AND (resolution_hash IS NULL OR btrim(resolution_hash) <> '') AND (manifest_hash IS NULL OR btrim(manifest_hash) <> '')"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_has_source", "num_nonnulls(source_membership_id, source_user_id, source_organization_person_id, source_hr_person_id) > 0"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_source_chain", "(source_worker_id IS NULL OR source_organization_person_id IS NOT NULL) AND (source_worker_engagement_id IS NULL OR source_worker_id IS NOT NULL) AND (source_hr_employment_id IS NULL OR source_hr_person_id IS NOT NULL)"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_resolution_chain", "(resolved_worker_id IS NULL OR resolved_organization_person_id IS NOT NULL) AND (resolved_worker_engagement_id IS NULL OR resolved_worker_id IS NOT NULL)"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_approved_shape", "status <> 'APPROVED' OR ( classification = 'ACCESS_ONLY' AND resolved_organization_person_id IS NULL AND resolved_worker_id IS NULL AND resolved_worker_engagement_id IS NULL ) OR ( classification = 'PERSON_ONLY' AND resolved_organization_person_id IS NOT NULL AND resolved_worker_id IS NULL AND resolved_worker_engagement_id IS NULL ) OR ( classification IN ('WORKFORCE_SUBJECT', 'LEGACY_COMPATIBILITY_SUBJECT') AND resolved_organization_person_id IS NOT NULL AND resolved_worker_id IS NOT NULL AND resolved_worker_engagement_id IS NOT NULL )"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_distinct_reviewers", "prepared_by_membership_id IS NULL OR approved_by_membership_id IS NULL OR prepared_by_membership_id <> approved_by_membership_id"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_review_state", "( status = 'OPEN' AND classification IS NULL AND reason_code IS NULL AND resolution_hash IS NULL AND manifest_hash IS NULL AND prepared_by_membership_id IS NULL AND prepared_at IS NULL AND approved_by_membership_id IS NULL AND approved_at IS NULL ) OR ( status = 'PREPARED' AND classification IS NOT NULL AND reason_code IS NOT NULL AND resolution_hash IS NOT NULL AND manifest_hash IS NULL AND prepared_by_membership_id IS NOT NULL AND prepared_at IS NOT NULL AND approved_by_membership_id IS NULL AND approved_at IS NULL ) OR ( status = 'APPROVED' AND classification IS NOT NULL AND reason_code IS NOT NULL AND resolution_hash IS NOT NULL AND manifest_hash IS NOT NULL AND prepared_by_membership_id IS NOT NULL AND prepared_at IS NOT NULL AND approved_by_membership_id IS NOT NULL AND approved_at IS NOT NULL )"),
    check("hr_workforce_reconciliation_items", "chk_hr_workforce_reconciliation_row_version", "row_version > 0"),
    check("organization_people", "chk_org_people_row_version", "row_version > 0", false),
    foreignKey("organization_people", "fk_org_people_org_membership", ["organization_id", "organization_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("organization_people", "fk_org_people_updated_actor", ["organization_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("organization_people", "fk_org_people_archived_actor", ["organization_id", "archived_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    check("workers", "chk_workers_row_version", "row_version > 0", false),
    check("workers", "chk_workers_status", "status IN ('ACTIVE', 'INACTIVE', 'EXITED')", false),
    foreignKey("workers", "fk_workers_created_actor", ["organization_id", "created_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("workers", "fk_workers_updated_actor", ["organization_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("workers", "fk_workers_archived_actor", ["organization_id", "archived_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    check("worker_engagements", "chk_worker_engagements_row_version", "row_version > 0", false),
    foreignKey("worker_engagements", "fk_worker_engagements_created_actor", ["organization_id", "created_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_updated_actor", ["organization_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_archived_actor", ["organization_id", "archived_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    check("hr_people", "chk_hr_people_row_version", "row_version > 0", false),
    foreignKey("hr_people", "fk_hr_people_org_person", ["org_id", "organization_person_id"], "organization_people", ["organization_id", "organization_person_id"], { validated: false, deferrable: true }),
    foreignKey("hr_people", "fk_hr_people_updated_actor", ["org_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("hr_people", "fk_hr_people_archived_actor", ["org_id", "archived_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    check("hr_employments", "chk_hr_employments_canonical_link", "(worker_id IS NULL) = (worker_engagement_id IS NULL)", false),
    check("hr_employments", "chk_hr_employments_row_version", "row_version > 0", false),
    foreignKey("hr_employments", "fk_hr_employments_org_person", ["org_id", "person_id"], "hr_people", ["org_id", "id"], { validated: false, deferrable: true }),
    foreignKey("hr_employments", "fk_hr_employments_org_worker", ["org_id", "worker_id"], "workers", ["organization_id", "worker_id"], { validated: false, deferrable: true }),
    foreignKey("hr_employments", "fk_hr_employments_org_worker_engagement", ["org_id", "worker_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"], { validated: false, deferrable: true }),
    foreignKey("hr_employments", "fk_hr_employments_updated_actor", ["org_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("hr_employments", "fk_hr_employments_archived_actor", ["org_id", "archived_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
  ],
  indexes: [
    i("workers", "uniq_workers_org_person_worker", ["organization_id", "organization_person_id", "worker_id"], true),
    i("worker_engagements", "uniq_worker_engagements_org_worker_engagement", ["organization_id", "worker_id", "worker_engagement_id"], true),
    i("hr_people", "uniq_hr_people_org_id", ["org_id", "id"], true),
    i("hr_employments", "uniq_hr_employments_org_id", ["org_id", "id"], true),
    i("hr_employments", "uniq_hr_employments_org_id_person", ["org_id", "id", "person_id"], true),
    i("organization_people", "uniq_org_people_active_work_email_ci", ["organization_id", "lower(work_email)"], true, "work_email IS NOT NULL AND archived_at IS NULL AND deleted_at IS NULL"),
    i("workers", "uniq_workers_active_org_number", ["organization_id", "worker_number"], true, "worker_number IS NOT NULL AND archived_at IS NULL AND deleted_at IS NULL"),
    i("worker_engagements", "uniq_worker_engagements_active_primary_unarchived", ["organization_id", "worker_id"], true, "is_primary = true AND status = 'ACTIVE' AND archived_at IS NULL"),
    i("hr_people", "uniq_hr_people_org_person_link", ["org_id", "organization_person_id"], true, "organization_person_id IS NOT NULL"),
    i("hr_employments", "uniq_hr_employments_org_engagement_link", ["org_id", "worker_engagement_id"], true, "worker_engagement_id IS NOT NULL"),
    i("organization_people", "idx_org_people_updated_actor", ["organization_id", "updated_by_membership_id"]),
    i("organization_people", "idx_org_people_archived_actor", ["organization_id", "archived_by_membership_id"]),
    i("workers", "idx_workers_created_actor", ["organization_id", "created_by_membership_id"]),
    i("workers", "idx_workers_updated_actor", ["organization_id", "updated_by_membership_id"]),
    i("workers", "idx_workers_archived_actor", ["organization_id", "archived_by_membership_id"]),
    i("worker_engagements", "idx_worker_engagements_created_actor", ["organization_id", "created_by_membership_id"]),
    i("worker_engagements", "idx_worker_engagements_updated_actor", ["organization_id", "updated_by_membership_id"]),
    i("worker_engagements", "idx_worker_engagements_archived_actor", ["organization_id", "archived_by_membership_id"]),
    i("hr_people", "idx_hr_people_updated_actor", ["org_id", "updated_by_membership_id"]),
    i("hr_people", "idx_hr_people_archived_actor", ["org_id", "archived_by_membership_id"]),
    i("hr_employments", "idx_hr_employments_worker", ["org_id", "worker_id"]),
    i("hr_employments", "idx_hr_employments_updated_actor", ["org_id", "updated_by_membership_id"]),
    i("hr_employments", "idx_hr_employments_archived_actor", ["org_id", "archived_by_membership_id"]),
    i("hrms_migration_profiles", "idx_hrms_profiles_changed_actor", ["changed_by_platform_user_id"]),
    i("hrms_migration_profile_events", "idx_hrms_profile_events_org_time", ["organization_id", "occurred_at"]),
    i("hr_person_legacy_map", "idx_hr_person_legacy_map_created_actor", ["org_id", "created_by_membership_id"]),
    i("hr_person_legacy_map", "idx_hr_person_legacy_map_updated_actor", ["org_id", "updated_by_membership_id"]),
    i("hr_employment_legacy_map", "idx_hr_employment_legacy_map_person", ["org_id", "hr_person_id"]),
    i("hr_employment_legacy_map", "idx_hr_employment_legacy_map_worker", ["org_id", "worker_id"]),
    i("hr_employment_legacy_map", "idx_hr_employment_legacy_map_created_actor", ["org_id", "created_by_membership_id"]),
    i("hr_employment_legacy_map", "idx_hr_employment_legacy_map_updated_actor", ["org_id", "updated_by_membership_id"]),
    i("hr_workforce_reconciliation_items", "uniq_hr_workforce_reconciliation_source", ["org_id", "batch_id", "source_fingerprint", "issue_kind", "coalesce(field_code, '')"], true),
    i("hr_workforce_reconciliation_items", "idx_hr_workforce_reconciliation_status", ["org_id", "batch_id", "status"]),
    i("hr_workforce_reconciliation_items", "idx_hr_workforce_reconciliation_resolved_worker", ["org_id", "resolved_worker_id"]),
    i("hr_workforce_reconciliation_items", "idx_hr_workforce_reconciliation_prepared_actor", ["org_id", "prepared_by_membership_id"]),
    i("hr_workforce_reconciliation_items", "idx_hr_workforce_reconciliation_approved_actor", ["org_id", "approved_by_membership_id"]),
  ],
  functions: [
    f("reject_hrms_append_only_mutation"),
    f("enforce_hrms_bundle_operation_transition", false, false),
    sqlFunction("hrms_modes_valid", ["jsonb"], "boolean"),
    sqlFunction("hrms_profile_modes_json", ["hrms_migration_profiles"], "jsonb"),
    f("enforce_hrms_profile_transition"),
    f("verify_hrms_profile_event_coupling", true, false),
    f("enforce_hrms_scope_revision"),
    f("seed_hrms_profile_for_organization", true, false),
    f("verify_hr_workforce_mapping", true, false),
    f("enforce_hr_workforce_reconciliation_transition"),
  ],
  enums: [],
};
