import {
  column as c,
  type ColumnRequirement,
} from "./bundle-definition-types";

export const exactColumnRelations0003 = [
  "attendance_event_locators",
  "attendance_events",
  "attendance_correction_links",
  "attendance_event_evidence",
  "attendance_evidence_legal_holds",
  "attendance_session_projections",
  "attendance_daily_projections",
];

export const columns0003: ColumnRequirement[] = [
  c("attendance_event_locators", "organization_id", "text", true),
  c("attendance_event_locators", "event_id", "bigint", true, null, "a"),
  c("attendance_event_locators", "business_date", "date", true),
  c("attendance_event_locators", "command_scope", "text", true),
  c("attendance_event_locators", "command_id", "text", true),
  c("attendance_event_locators", "effect_ordinal", "integer", true),
  c("attendance_event_locators", "source_type", "text", true),
  c("attendance_event_locators", "source_id", "text", true),
  c("attendance_event_locators", "source_ordinal", "integer", true),
  c("attendance_event_locators", "created_at", "timestamp with time zone", true, "now()"),
  c("attendance_events", "organization_id", "text", true),
  c("attendance_events", "business_date", "date", true),
  c("attendance_events", "event_id", "bigint", true),
  c("attendance_events", "worker_id", "text", true),
  c("attendance_events", "worker_engagement_id", "text", true),
  c("attendance_events", "event_kind", "attendance_event_kind", true),
  c("attendance_events", "occurred_at", "timestamp with time zone", true),
  c("attendance_events", "recorded_at", "timestamp with time zone", true, "now()"),
  c("attendance_events", "organization_timezone", "text", true),
  c("attendance_events", "event_source", "attendance_event_source", true),
  c("attendance_events", "command_scope", "text", true),
  c("attendance_events", "command_id", "text", true),
  c("attendance_events", "effect_ordinal", "integer", true),
  c("attendance_events", "source_type", "text", true),
  c("attendance_events", "source_id", "text", true),
  c("attendance_events", "source_ordinal", "integer", true),
  c("attendance_events", "actor_membership_id", "integer"),
  c("attendance_events", "actor_user_id", "text"),
  c("attendance_events", "migration_batch_id", "text"),
  c("attendance_events", "geofence_id", "integer"),
  c("attendance_events", "geofence_passed", "boolean"),
  c("attendance_events", "accuracy_bucket", "attendance_accuracy_bucket"),
  c("attendance_events", "distance_bucket", "attendance_distance_bucket"),
  c("attendance_events", "corrects_business_date", "date"),
  c("attendance_events", "corrects_event_id", "bigint"),
  c("attendance_events", "correction_action", "attendance_correction_action"),
  c("attendance_events", "replacement_event_kind", "attendance_correction_replacement_kind"),
  c("attendance_events", "replacement_occurred_at", "timestamp with time zone"),
  c("attendance_events", "correction_reason_code", "text"),
  c("attendance_correction_links", "organization_id", "text", true),
  c("attendance_correction_links", "original_business_date", "date", true),
  c("attendance_correction_links", "original_event_id", "bigint", true),
  c("attendance_correction_links", "correction_business_date", "date", true),
  c("attendance_correction_links", "correction_event_id", "bigint", true),
  c("attendance_event_evidence", "organization_id", "text", true),
  c("attendance_event_evidence", "business_date", "date", true),
  c("attendance_event_evidence", "evidence_id", "bigint", true, null, "a"),
  c("attendance_event_evidence", "event_id", "bigint", true),
  c("attendance_event_evidence", "encrypted_coordinates", "text", true),
  c("attendance_event_evidence", "wrapped_data_key", "text", true),
  c("attendance_event_evidence", "kms_key_id", "text", true),
  c("attendance_event_evidence", "kms_key_version", "text", true),
  c("attendance_event_evidence", "encryption_version", "integer", true),
  c("attendance_event_evidence", "coordinate_decimal_places", "integer", true),
  c("attendance_event_evidence", "capture_source", "attendance_event_source", true),
  c("attendance_event_evidence", "device_fingerprint_hash", "text"),
  c("attendance_event_evidence", "captured_at", "timestamp with time zone", true),
  c("attendance_event_evidence", "retention_expires_at", "timestamp with time zone", true),
  c("attendance_event_evidence", "created_at", "timestamp with time zone", true, "now()"),
  c("attendance_evidence_legal_holds", "organization_id", "text", true),
  c("attendance_evidence_legal_holds", "business_date", "date", true),
  c("attendance_evidence_legal_holds", "evidence_id", "bigint", true),
  c("attendance_evidence_legal_holds", "case_id", "text", true),
  c("attendance_evidence_legal_holds", "reason_code", "text", true),
  c("attendance_evidence_legal_holds", "approved_by_membership_id", "integer", true),
  c("attendance_evidence_legal_holds", "second_approver_membership_id", "integer", true),
  c("attendance_evidence_legal_holds", "approved_at", "timestamp with time zone", true),
  c("attendance_evidence_legal_holds", "review_due_at", "timestamp with time zone", true),
  c("attendance_evidence_legal_holds", "expires_at", "timestamp with time zone", true),
  c("attendance_evidence_legal_holds", "row_version", "integer", true, "1"),
  c("attendance_evidence_legal_holds", "updated_at", "timestamp with time zone", true, "now()"),
  c("attendance_session_projections", "organization_id", "text", true),
  c("attendance_session_projections", "session_id", "bigint", true, null, "a"),
  c("attendance_session_projections", "business_date", "date", true),
  c("attendance_session_projections", "worker_id", "text", true),
  c("attendance_session_projections", "worker_engagement_id", "text", true),
  c("attendance_session_projections", "state", "attendance_session_state", true),
  c("attendance_session_projections", "opened_at", "timestamp with time zone", true),
  c("attendance_session_projections", "closed_at", "timestamp with time zone"),
  c("attendance_session_projections", "break_started_at", "timestamp with time zone"),
  c("attendance_session_projections", "worked_minutes", "integer", true, "0"),
  c("attendance_session_projections", "break_minutes", "integer", true, "0"),
  c("attendance_session_projections", "opened_event_business_date", "date", true),
  c("attendance_session_projections", "opened_event_id", "bigint", true),
  c("attendance_session_projections", "last_event_business_date", "date", true),
  c("attendance_session_projections", "last_event_id", "bigint", true),
  c("attendance_session_projections", "projection_version", "bigint", true, "1"),
  c("attendance_session_projections", "updated_at", "timestamp with time zone", true, "now()"),
  c("attendance_daily_projections", "organization_id", "text", true),
  c("attendance_daily_projections", "business_date", "date", true),
  c("attendance_daily_projections", "worker_id", "text", true),
  c("attendance_daily_projections", "worker_engagement_id", "text", true),
  c("attendance_daily_projections", "first_check_in_at", "timestamp with time zone"),
  c("attendance_daily_projections", "last_check_out_at", "timestamp with time zone"),
  c("attendance_daily_projections", "worked_minutes", "integer", true, "0"),
  c("attendance_daily_projections", "break_minutes", "integer", true, "0"),
  c("attendance_daily_projections", "overtime_minutes", "integer", true, "0"),
  c("attendance_daily_projections", "session_count", "integer", true, "0"),
  c("attendance_daily_projections", "has_open_session", "boolean", true, "false"),
  c("attendance_daily_projections", "last_event_business_date", "date", true),
  c("attendance_daily_projections", "last_event_id", "bigint", true),
  c("attendance_daily_projections", "projection_version", "bigint", true, "1"),
  c("attendance_daily_projections", "updated_at", "timestamp with time zone", true, "now()"),
];
