import {
  column as c,
  type ColumnRequirement,
} from "./bundle-definition-types";

export const exactColumnRelations0004 = [
  "app.hrms_partition_operations",
  "org_unit_closure",
  "hr_audit_event_sources",
  "hr_audit_events",
];

export const columns0004: ColumnRequirement[] = [
  c("app.hrms_partition_operations", "operation_id", "text", true),
  c("app.hrms_partition_operations", "approval_id", "text", true),
  c("app.hrms_partition_operations", "manifest_hash", "text", true),
  c("app.hrms_partition_operations", "base_bundle_id", "text", true),
  c("app.hrms_partition_operations", "root_migration_name", "text", true),
  c("app.hrms_partition_operations", "root_migration_hash", "text", true),
  c("app.hrms_partition_operations", "base_dependencies_hash", "text", true),
  c("app.hrms_partition_operations", "database_name", "text", true),
  c("app.hrms_partition_operations", "database_role", "text", true),
  c("app.hrms_partition_operations", "server_version_num", "integer", true),
  c("app.hrms_partition_operations", "parent_table", "text", true),
  c("app.hrms_partition_operations", "child_table", "text", true),
  c("app.hrms_partition_operations", "partition_kind", "text", true),
  c("app.hrms_partition_operations", "range_from", "date"),
  c("app.hrms_partition_operations", "range_to", "date"),
  c("app.hrms_partition_operations", "hash_modulus", "integer"),
  c("app.hrms_partition_operations", "hash_remainder", "integer"),
  c("app.hrms_partition_operations", "security_profile", "text", true),
  c("app.hrms_partition_operations", "ddl_hash", "text", true),
  c("app.hrms_partition_operations", "state", "text", true),
  c("app.hrms_partition_operations", "attempts", "integer", true, "1"),
  c("app.hrms_partition_operations", "started_at", "timestamp with time zone", true),
  c("app.hrms_partition_operations", "completed_at", "timestamp with time zone"),
  c("app.hrms_partition_operations", "last_error", "text"),
  c("org_unit_closure", "organization_id", "text", true),
  c("org_unit_closure", "ancestor_id", "text", true),
  c("org_unit_closure", "descendant_id", "text", true),
  c("org_unit_closure", "depth", "integer", true),
  c("hr_audit_event_sources", "organization_id", "text", true),
  c("hr_audit_event_sources", "audit_event_id", "bigint", true, null, "a"),
  c("hr_audit_event_sources", "occurred_at", "timestamp with time zone", true),
  c("hr_audit_event_sources", "source_type", "text", true),
  c("hr_audit_event_sources", "source_id", "text", true),
  c("hr_audit_event_sources", "source_ordinal", "integer", true),
  c("hr_audit_event_sources", "created_at", "timestamp with time zone", true, "now()"),
  c("hr_audit_events", "organization_id", "text", true),
  c("hr_audit_events", "occurred_at", "timestamp with time zone", true),
  c("hr_audit_events", "audit_event_id", "bigint", true),
  c("hr_audit_events", "actor_user_id", "text"),
  c("hr_audit_events", "actor_membership_id", "integer"),
  c("hr_audit_events", "entity_type", "text", true),
  c("hr_audit_events", "entity_id", "text", true),
  c("hr_audit_events", "action", "text", true),
  c("hr_audit_events", "request_id", "text"),
  c("hr_audit_events", "correlation_id", "text"),
  c("hr_audit_events", "source_type", "text", true),
  c("hr_audit_events", "source_id", "text", true),
  c("hr_audit_events", "source_ordinal", "integer", true),
  c("hr_audit_events", "migration_batch_id", "text"),
  c("hr_audit_events", "redacted_diff", "jsonb", true, "'{}'::jsonb"),
];
