import type { BundleFileName } from "./bundle-config";
import {
  attendanceCorrectionLeaf,
  attendanceFactLeaf,
  attendanceLocatorLeaf,
  auditFactLeaf,
  auditSourceLeaf,
  deferrable,
  evidenceLeaf,
  leaveFactLeaf,
  leaveReversalLeaf,
  locatorLeaf,
  partition,
  profileColumns,
  roleAccess,
  select,
  table,
  trigger,
  type FileCatalogRequirement,
} from "./bundle-catalog-recipes";

export type {
  ApplicationAccess,
  ConstraintRequirement,
  FileCatalogRequirement,
  RelationRequirement,
  TriggerRecipe,
  TriggerRequirement,
} from "./bundle-catalog-recipes";

export const bundleCatalogRegistry: Record<
  BundleFileName,
  FileCatalogRequirement
> = {
  "0000_hrms_profiles_workforce.sql": {
    relations: [
      table("hrms_migration_profiles", "organization_id", profileColumns, roleAccess("SELECT", "UPDATE")),
      table("hrms_migration_profile_events", "organization_id", undefined, roleAccess("SELECT", "INSERT")),
      table("hrms_scope_versions", "organization_id", select, roleAccess("SELECT", "UPDATE")),
      table("hr_person_legacy_map", "org_id", undefined, roleAccess("SELECT", "INSERT", "UPDATE")),
      table("hr_employment_legacy_map", "org_id", undefined, roleAccess("SELECT", "INSERT", "UPDATE")),
      table("hr_workforce_reconciliation_items", "org_id", undefined, roleAccess("SELECT", "INSERT", "UPDATE")),
    ],
    functions: [
      "reject_hrms_append_only_mutation",
      "enforce_hrms_bundle_operation_transition",
      "hrms_modes_valid",
      "hrms_profile_modes_json",
      "enforce_hrms_profile_transition",
      "verify_hrms_profile_event_coupling",
      "enforce_hrms_scope_revision",
      "seed_hrms_profile_for_organization",
      "verify_hr_workforce_mapping",
      "enforce_hr_workforce_reconciliation_transition",
    ],
    triggers: [
      trigger("app.hrms_sql_bundle_operations", "enforce_hrms_bundle_operation_transition", "enforce_hrms_bundle_operation_transition", 23),
      trigger("app.hrms_sql_bundle_operations", "reject_hrms_bundle_operation_delete", "reject_hrms_append_only_mutation", 11),
      trigger("app.hrms_sql_bundle_operations", "reject_hrms_bundle_operation_truncate", "reject_hrms_append_only_mutation", 34),
      trigger("hrms_migration_profiles", "enforce_hrms_profile_transition", "enforce_hrms_profile_transition", 19),
      trigger("hrms_migration_profiles", "verify_hrms_profile_update_event", "verify_hrms_profile_event_coupling", 17, true),
      trigger("hrms_migration_profile_events", "verify_hrms_profile_event_update", "verify_hrms_profile_event_coupling", 5, true),
      trigger("hrms_migration_profile_events", "reject_hrms_profile_event_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("hrms_migration_profile_events", "reject_hrms_profile_event_truncate", "reject_hrms_append_only_mutation", 34),
      trigger("hrms_migration_profiles", "reject_hrms_profile_delete", "reject_hrms_append_only_mutation", 11),
      trigger("hrms_migration_profiles", "reject_hrms_profile_truncate", "reject_hrms_append_only_mutation", 34),
      trigger("hrms_scope_versions", "enforce_hrms_scope_revision", "enforce_hrms_scope_revision", 19),
      trigger("hrms_scope_versions", "reject_hrms_scope_delete", "reject_hrms_append_only_mutation", 11),
      trigger("hrms_scope_versions", "reject_hrms_scope_truncate", "reject_hrms_append_only_mutation", 34),
      trigger("organizations", "seed_hrms_profile_for_organization", "seed_hrms_profile_for_organization", 5),
      trigger("hr_people", "verify_hr_people_workforce_mapping", "verify_hr_workforce_mapping", 29, true),
      trigger("hr_person_legacy_map", "verify_hr_person_legacy_mapping", "verify_hr_workforce_mapping", 29, true),
      trigger("hr_employments", "verify_hr_employments_workforce_mapping", "verify_hr_workforce_mapping", 29, true),
      trigger("hr_employment_legacy_map", "verify_hr_employment_legacy_mapping", "verify_hr_workforce_mapping", 29, true),
      trigger("hr_workforce_reconciliation_items", "enforce_hr_workforce_reconciliation_transition", "enforce_hr_workforce_reconciliation_transition", 19),
      trigger("hr_workforce_reconciliation_items", "reject_hr_workforce_reconciliation_delete", "reject_hrms_append_only_mutation", 11),
      trigger("hr_workforce_reconciliation_items", "reject_hr_workforce_reconciliation_truncate", "reject_hrms_append_only_mutation", 34),
    ],
    exactTriggerRelations: ["app.hrms_sql_bundle_operations"],
    constraints: [],
    sequences: ["hr_workforce_reconciliation_items_reconciliation_item_id_seq"],
    migrationSequencePrivileges: ["SELECT", "USAGE"],
  },
  "0001_hrms_effective_history.sql": {
    relations: [
      table("worker_assignment_periods", "organization_id", undefined, roleAccess("SELECT", "INSERT", "UPDATE")),
      table("worker_reporting_lines", "organization_id", undefined, roleAccess("SELECT", "INSERT", "UPDATE")),
      table("worker_engagement_state_events", "organization_id", undefined, roleAccess("SELECT", "INSERT")),
    ],
    functions: [
      "verify_workforce_org_unit_kinds",
      "enforce_workforce_period_revision",
      "lock_worker_reporting_line_tenant",
      "verify_worker_reporting_line_cycles",
      "verify_worker_engagement_state_chain",
      "verify_worker_engagement_state_projection",
    ],
    triggers: [
      trigger("worker_engagements", "verify_worker_engagement_org_unit_kinds", "verify_workforce_org_unit_kinds", 21, true, ["organization_id", "business_unit_id", "branch_id", "department_id", "team_id", "location_id"]),
      trigger("worker_assignment_periods", "verify_assignment_org_unit_kinds", "verify_workforce_org_unit_kinds", 21, true, ["organization_id", "business_unit_id", "branch_id", "department_id", "team_id", "location_id", "cost_center_id"]),
      trigger("org_units", "protect_referenced_org_unit_kinds", "verify_workforce_org_unit_kinds", 17, true, ["org_id", "id", "kind"]),
      trigger("worker_assignment_periods", "enforce_worker_assignment_period_revision", "enforce_workforce_period_revision", 19),
      trigger("worker_reporting_lines", "enforce_worker_reporting_line_revision", "enforce_workforce_period_revision", 19),
      trigger("worker_reporting_lines", "lock_worker_reporting_line_tenant", "lock_worker_reporting_line_tenant", 23),
      trigger("worker_engagement_state_events", "lock_worker_engagement_state_event", "lock_worker_engagement_state_transition", 7),
      trigger("worker_engagements", "lock_worker_engagement_state_projection", "lock_worker_engagement_state_transition", 19, false, ["status", "last_state_event_id"]),
      trigger("worker_reporting_lines", "verify_worker_reporting_line_cycles", "verify_worker_reporting_line_cycles", 21, true),
      trigger("worker_engagement_state_events", "verify_worker_engagement_state_chain", "verify_worker_engagement_state_chain", 5, true),
      trigger("worker_engagements", "verify_worker_engagement_state_projection", "verify_worker_engagement_state_projection", 21, true, ["status", "last_state_event_id"]),
      trigger("worker_engagement_state_events", "reject_worker_engagement_state_event_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("worker_engagement_state_events", "reject_worker_engagement_state_event_truncate", "reject_hrms_append_only_mutation", 34),
      trigger("worker_assignment_periods", "reject_worker_assignment_period_delete", "reject_hrms_append_only_mutation", 11),
      trigger("worker_assignment_periods", "reject_worker_assignment_period_truncate", "reject_hrms_append_only_mutation", 34),
      trigger("worker_reporting_lines", "reject_worker_reporting_line_delete", "reject_hrms_append_only_mutation", 11),
      trigger("worker_reporting_lines", "reject_worker_reporting_line_truncate", "reject_hrms_append_only_mutation", 34),
    ],
    exactTriggerRelations: [],
    constraints: [
      deferrable("worker_engagements", "fk_worker_engagements_last_state_projection"),
    ],
    sequences: ["worker_engagement_state_events_event_id_seq"],
    migrationSequencePrivileges: ["SELECT", "USAGE"],
  },
  "0002_hrms_leave_ledger.sql": {
    relations: [
      partition("worker_leave_entry_locators", "h", "organization_id", locatorLeaf),
      partition("worker_leave_ledger_entries", "r", "effective_date", leaveFactLeaf),
      partition("worker_leave_reversal_links", "h", "organization_id", leaveReversalLeaf),
      table("worker_leave_balance_projections", "organization_id"),
    ],
    functions: [
      "verify_worker_leave_locator_fact",
      "verify_worker_leave_reversal",
      "verify_worker_leave_balance_projection",
    ],
    triggers: [
      trigger("worker_leave_entry_locators", "reject_worker_leave_locator_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("worker_leave_ledger_entries", "reject_worker_leave_fact_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("worker_leave_reversal_links", "reject_worker_leave_reversal_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("worker_leave_balance_projections", "verify_worker_leave_balance_projection", "verify_worker_leave_balance_projection", 21, true),
    ],
    exactTriggerRelations: [],
    constraints: [
      deferrable("worker_leave_ledger_entries", "fk_worker_leave_entries_locator"),
      deferrable("worker_leave_entry_locators", "fk_worker_leave_locators_fact"),
      deferrable("worker_leave_reversal_links", "fk_worker_leave_reversal_original_fact"),
      deferrable("worker_leave_reversal_links", "fk_worker_leave_reversal_reversal_fact"),
    ],
    sequences: ["worker_leave_entry_locators_entry_id_seq"],
    migrationSequencePrivileges: [],
  },
  "0003_hrms_attendance_events.sql": {
    relations: [
      partition("attendance_event_locators", "h", "organization_id", attendanceLocatorLeaf),
      partition("attendance_events", "r", "business_date", attendanceFactLeaf),
      partition("attendance_correction_links", "h", "organization_id", attendanceCorrectionLeaf),
      partition("attendance_event_evidence", "r", "business_date", evidenceLeaf),
      table("attendance_evidence_legal_holds", "organization_id"),
      table("attendance_session_projections", "organization_id"),
      table("attendance_daily_projections", "organization_id"),
    ],
    functions: [
      "verify_attendance_locator_fact",
      "verify_attendance_correction",
      "verify_attendance_correction_link",
      "verify_attendance_projection_events",
      "reject_attendance_evidence_mutation",
    ],
    triggers: [
      trigger("attendance_event_locators", "reject_attendance_event_locator_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("attendance_events", "reject_attendance_event_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("attendance_correction_links", "reject_attendance_correction_link_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("attendance_event_evidence", "guard_attendance_event_evidence_mutation", "reject_attendance_evidence_mutation", 27),
      trigger("attendance_evidence_legal_holds", "reject_hrms_truncate", "reject_hrms_append_only_mutation", 34),
      trigger("attendance_session_projections", "verify_attendance_session_projection_events", "verify_attendance_projection_events", 21, true),
      trigger("attendance_daily_projections", "verify_attendance_daily_projection_events", "verify_attendance_projection_events", 21, true),
    ],
    exactTriggerRelations: [],
    constraints: [
      deferrable("attendance_events", "fk_attendance_events_locator"),
      deferrable("attendance_event_locators", "fk_attendance_event_locators_fact"),
      deferrable("attendance_events", "fk_attendance_events_correction_target"),
      deferrable("attendance_correction_links", "fk_attendance_correction_links_original_fact"),
      deferrable("attendance_correction_links", "fk_attendance_correction_links_correction_fact"),
    ],
    sequences: [
      "attendance_event_locators_event_id_seq",
      "attendance_event_evidence_evidence_id_seq",
      "attendance_session_projections_session_id_seq",
    ],
    migrationSequencePrivileges: [],
  },
  "0004_hrms_hierarchy_audit.sql": {
    relations: [
      table("org_unit_closure", "organization_id"),
      partition("hr_audit_event_sources", "h", "organization_id", auditSourceLeaf),
      partition("hr_audit_events", "r", "occurred_at", auditFactLeaf),
    ],
    functions: [
      "enforce_hrms_partition_operation_transition",
      "verify_org_unit_parent_cycle",
      "verify_hr_audit_source_fact",
    ],
    triggers: [
      trigger("app.hrms_partition_operations", "enforce_hrms_partition_operation_transition", "enforce_hrms_partition_operation_transition", 23),
      trigger("app.hrms_partition_operations", "reject_hrms_partition_operation_delete", "reject_hrms_append_only_mutation", 11),
      trigger("app.hrms_partition_operations", "reject_hrms_partition_operation_truncate", "reject_hrms_append_only_mutation", 34),
      trigger("org_units", "verify_org_unit_parent_cycle", "verify_org_unit_parent_cycle", 17, true, ["parent_id"]),
      trigger("hr_audit_event_sources", "reject_hr_audit_event_source_mutation", "reject_hrms_append_only_mutation", 27),
      trigger("hr_audit_events", "reject_hr_audit_event_mutation", "reject_hrms_append_only_mutation", 27),
    ],
    exactTriggerRelations: ["app.hrms_partition_operations"],
    constraints: [
      deferrable("hr_audit_events", "fk_hr_audit_events_source"),
      deferrable("hr_audit_event_sources", "fk_hr_audit_event_sources_fact"),
    ],
    sequences: ["hr_audit_event_sources_audit_event_id_seq"],
    migrationSequencePrivileges: [],
  },
};
