import {
  check,
  column as c,
  foreignKey,
  index as i,
  key,
  triggerFunction as f,
  type FileDefinitionRequirement,
} from "./bundle-definition-types";
import {
  columns0002,
  exactColumnRelations0002,
} from "./bundle-columns-0002";
import { leaveRejectFunctionHash } from "./bundle-function-hashes";

export const definitions0002: FileDefinitionRequirement = {
  columns: [
    ...columns0002,
    c("leave_requests", "worker_id", "text"),
    c("leave_requests", "worker_engagement_id", "text"),
    c("leave_requests", "row_version", "integer", true, "1"),
    c("leave_requests", "created_by_membership_id", "integer"),
    c("leave_requests", "updated_by_membership_id", "integer"),
    c("leave_requests", "updated_at", "timestamp with time zone", true, "now()"),
  ],
  exactColumnRelations: exactColumnRelations0002,
  ownerOnlyRelations: [],
  constraints: [
    key("worker_leave_entry_locators", "pk_worker_leave_entry_locators", "primary", ["organization_id", "entry_id"]),
    key("worker_leave_entry_locators", "uniq_worker_leave_locators_entry_date", "unique", ["organization_id", "entry_id", "effective_date"]),
    key("worker_leave_entry_locators", "uniq_worker_leave_locators_command", "unique", ["organization_id", "command_scope", "command_id", "effect_ordinal"]),
    key("worker_leave_entry_locators", "uniq_worker_leave_locators_source", "unique", ["organization_id", "source_type", "source_id", "source_ordinal"]),
    foreignKey("worker_leave_entry_locators", "fk_worker_leave_locators_organization", ["organization_id"], "organizations", ["id"]),
    check("worker_leave_entry_locators", "chk_worker_leave_locators_command_key", "btrim(command_scope) <> '' AND btrim(command_id) <> '' AND effect_ordinal >= 0"),
    check("worker_leave_entry_locators", "chk_worker_leave_locators_source_key", "btrim(source_type) <> '' AND btrim(source_id) <> '' AND source_ordinal >= 0"),
    key("worker_leave_ledger_entries", "pk_worker_leave_ledger_entries", "primary", ["organization_id", "effective_date", "entry_id"]),
    foreignKey("worker_leave_ledger_entries", "fk_worker_leave_entries_organization", ["organization_id"], "organizations", ["id"]),
    foreignKey("worker_leave_ledger_entries", "fk_worker_leave_entries_locator", ["organization_id", "entry_id", "effective_date"], "worker_leave_entry_locators", ["organization_id", "entry_id", "effective_date"], { deferrable: true }),
    foreignKey("worker_leave_ledger_entries", "fk_worker_leave_entries_org_worker", ["organization_id", "worker_id"], "workers", ["organization_id", "worker_id"]),
    foreignKey("worker_leave_ledger_entries", "fk_worker_leave_entries_worker_engagement", ["organization_id", "worker_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"]),
    foreignKey("worker_leave_ledger_entries", "fk_worker_leave_entries_org_leave_type", ["organization_id", "leave_type_id"], "leave_types", ["org_id", "id"]),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_entry_type", "entry_type IN ( 'ACCRUAL', 'CONSUMPTION', 'CARRY_FORWARD', 'ENCASHMENT', 'EXPIRY', 'ADJUSTMENT', 'COMP_OFF_EARN', 'COMP_OFF_USE', 'REVERSAL', 'LEGACY_OPENING_BALANCE' )"),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_provenance", "provenance_status IN ('VERIFIED_SOURCE', 'UNVERIFIED_LEGACY')"),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_legacy_pair", "(provenance_status = 'UNVERIFIED_LEGACY') = (entry_type = 'LEGACY_OPENING_BALANCE')"),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_migration_batch", "migration_batch_id IS NULL OR btrim(migration_batch_id) <> ''"),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_legacy_batch", "provenance_status <> 'UNVERIFIED_LEGACY' OR migration_batch_id IS NOT NULL"),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_command_key", "btrim(command_scope) <> '' AND btrim(command_id) <> '' AND effect_ordinal >= 0"),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_source_key", "btrim(source_type) <> '' AND btrim(source_id) <> '' AND source_ordinal >= 0"),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_period_key", "btrim(period_key) <> ''"),
    check("worker_leave_ledger_entries", "chk_worker_leave_entries_delta_days", "delta_days BETWEEN -1000000::numeric AND 1000000::numeric AND delta_days <> 0"),
    key("worker_leave_reversal_links", "pk_worker_leave_reversal_links", "primary", ["organization_id", "original_entry_id"]),
    key("worker_leave_reversal_links", "uniq_worker_leave_reversal_links_reversal", "unique", ["organization_id", "reversal_entry_id"]),
    foreignKey("worker_leave_reversal_links", "fk_worker_leave_reversal_organization", ["organization_id"], "organizations", ["id"]),
    foreignKey("worker_leave_reversal_links", "fk_worker_leave_reversal_original_fact", ["organization_id", "original_effective_date", "original_entry_id"], "worker_leave_ledger_entries", ["organization_id", "effective_date", "entry_id"], { deferrable: true }),
    foreignKey("worker_leave_reversal_links", "fk_worker_leave_reversal_original_locator", ["organization_id", "original_entry_id"], "worker_leave_entry_locators", ["organization_id", "entry_id"], { deferrable: true }),
    foreignKey("worker_leave_reversal_links", "fk_worker_leave_reversal_reversal_fact", ["organization_id", "reversal_effective_date", "reversal_entry_id"], "worker_leave_ledger_entries", ["organization_id", "effective_date", "entry_id"], { deferrable: true }),
    foreignKey("worker_leave_reversal_links", "fk_worker_leave_reversal_reversal_locator", ["organization_id", "reversal_entry_id"], "worker_leave_entry_locators", ["organization_id", "entry_id"], { deferrable: true }),
    check("worker_leave_reversal_links", "chk_worker_leave_reversal_not_self", "original_entry_id <> reversal_entry_id"),
    key("worker_leave_balance_projections", "pk_worker_leave_balance_projections", "primary", ["organization_id", "worker_id", "leave_type_id", "period_key"]),
    foreignKey("worker_leave_balance_projections", "fk_worker_leave_balances_organization", ["organization_id"], "organizations", ["id"]),
    foreignKey("worker_leave_balance_projections", "fk_worker_leave_balances_org_worker", ["organization_id", "worker_id"], "workers", ["organization_id", "worker_id"]),
    foreignKey("worker_leave_balance_projections", "fk_worker_leave_balances_org_leave_type", ["organization_id", "leave_type_id"], "leave_types", ["org_id", "id"]),
    foreignKey("worker_leave_balance_projections", "fk_worker_leave_balances_last_entry", ["organization_id", "last_processed_effective_date", "last_processed_entry_id"], "worker_leave_ledger_entries", ["organization_id", "effective_date", "entry_id"]),
    check("worker_leave_balance_projections", "chk_worker_leave_balances_last_entry_pair", "(last_processed_entry_id IS NULL) = (last_processed_effective_date IS NULL)"),
    check("worker_leave_balance_projections", "chk_worker_leave_balances_projection_version", "projection_version > 0"),
    check("worker_leave_balance_projections", "chk_worker_leave_balances_period_key", "btrim(period_key) <> ''"),
    check("worker_leave_balance_projections", "chk_worker_leave_balances_balance_days", "balance_days BETWEEN -1000000::numeric AND 1000000::numeric"),
    check("leave_requests", "chk_leave_requests_row_version", "row_version > 0", false),
    check("leave_requests", "chk_leave_requests_canonical_subject_pair", "(worker_id IS NULL) = (worker_engagement_id IS NULL)", false),
    foreignKey("leave_requests", "fk_leave_requests_org_worker", ["org_id", "worker_id"], "workers", ["organization_id", "worker_id"], { validated: false }),
    foreignKey("leave_requests", "fk_leave_requests_worker_engagement", ["org_id", "worker_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"], { validated: false }),
    foreignKey("leave_requests", "fk_leave_requests_created_actor", ["org_id", "created_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("leave_requests", "fk_leave_requests_updated_actor", ["org_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"], { validated: false }),
    foreignKey("worker_leave_entry_locators", "fk_worker_leave_locators_fact", ["organization_id", "effective_date", "entry_id"], "worker_leave_ledger_entries", ["organization_id", "effective_date", "entry_id"], { deferrable: true }),
  ],
  indexes: [
    i("leave_requests", "idx_leave_requests_org_worker", ["org_id", "worker_id"]),
    i("leave_requests", "idx_leave_requests_org_engagement", ["org_id", "worker_engagement_id"]),
    i("worker_leave_entry_locators", "idx_worker_leave_locators_org_date", ["organization_id", "effective_date"]),
    i("worker_leave_ledger_entries", "idx_worker_leave_entries_balance_rebuild", ["organization_id", "worker_id", "leave_type_id", "period_key", "effective_date", "entry_id"]),
    i("worker_leave_ledger_entries", "idx_worker_leave_entries_locator", ["organization_id", "entry_id", "effective_date"]),
    i("worker_leave_ledger_entries", "idx_worker_leave_entries_org_engagement", ["organization_id", "worker_engagement_id"]),
    i("worker_leave_ledger_entries", "idx_worker_leave_entries_org_leave_type", ["organization_id", "leave_type_id"]),
    i("worker_leave_reversal_links", "idx_worker_leave_reversal_original_fact", ["organization_id", "original_effective_date", "original_entry_id"]),
    i("worker_leave_reversal_links", "idx_worker_leave_reversal_reversal_fact", ["organization_id", "reversal_effective_date", "reversal_entry_id"]),
    i("worker_leave_balance_projections", "idx_worker_leave_balances_org_leave_type", ["organization_id", "leave_type_id"]),
    i("worker_leave_balance_projections", "idx_worker_leave_balances_last_entry", ["organization_id", "last_processed_effective_date", "last_processed_entry_id"]),
  ],
  functions: [
    {
      ...f("reject_hrms_append_only_mutation"),
      bodySha256: [leaveRejectFunctionHash],
    },
    f("verify_worker_leave_locator_fact", true),
    f("verify_worker_leave_reversal", true),
    f("verify_worker_leave_balance_projection", true),
  ],
  enums: [],
};
