import {
  check,
  column as c,
  exclusion,
  foreignKey,
  index as i,
  key,
  triggerFunction as f,
  type FileDefinitionRequirement,
} from "./bundle-definition-types";
import {
  columns0001,
  exactColumnRelations0001,
} from "./bundle-columns-0001";

export const definitions0001: FileDefinitionRequirement = {
  columns: [
    ...columns0001,
    c("worker_engagements", "state_reason", "text"),
    c("worker_engagements", "last_state_event_id", "bigint"),
  ],
  exactColumnRelations: exactColumnRelations0001,
  ownerOnlyRelations: [],
  constraints: [
    key("worker_assignment_periods", "worker_assignment_periods_pkey", "primary", ["assignment_period_id"]),
    foreignKey("worker_assignment_periods", "worker_assignment_periods_organization_id_fkey", ["organization_id"], "organizations", ["id"]),
    key("worker_reporting_lines", "worker_reporting_lines_pkey", "primary", ["reporting_line_id"]),
    foreignKey("worker_reporting_lines", "worker_reporting_lines_organization_id_fkey", ["organization_id"], "organizations", ["id"]),
    foreignKey("worker_engagement_state_events", "worker_engagement_state_events_organization_id_fkey", ["organization_id"], "organizations", ["id"]),
    key("org_units", "uniq_org_units_org_id", "unique", ["org_id", "id"]),
    key("hr_job_roles", "uniq_hr_job_roles_org_id", "unique", ["org_id", "id"]),
    key("hr_job_levels", "uniq_hr_job_levels_org_id", "unique", ["org_id", "id"]),
    key("shift_templates", "uniq_shift_templates_org_id", "unique", ["org_id", "id"]),
    key("worker_assignment_periods", "uniq_worker_assignment_periods_org_id", "unique", ["organization_id", "assignment_period_id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_engagement", ["organization_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_engagement_id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_business_unit", ["organization_id", "business_unit_id"], "org_units", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_branch", ["organization_id", "branch_id"], "org_units", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_department", ["organization_id", "department_id"], "org_units", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_team", ["organization_id", "team_id"], "org_units", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_location", ["organization_id", "location_id"], "org_units", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_cost_center", ["organization_id", "cost_center_id"], "org_units", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_job_role", ["organization_id", "job_role_id"], "hr_job_roles", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_job_level", ["organization_id", "job_level_id"], "hr_job_levels", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_schedule", ["organization_id", "schedule_id"], "shift_templates", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_created_actor", ["organization_id", "created_by_membership_id"], "organization_members", ["org_id", "id"]),
    foreignKey("worker_assignment_periods", "fk_worker_assignment_periods_updated_actor", ["organization_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"]),
    check("worker_assignment_periods", "chk_worker_assignment_periods_dates", "valid_from < valid_to"),
    check("worker_assignment_periods", "chk_worker_assignment_periods_employment_type", "employment_type IS NULL OR employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACTOR', 'CONSULTANT', 'INTERN', 'TEMPORARY', 'AGENCY', 'FREELANCER')"),
    check("worker_assignment_periods", "chk_worker_assignment_periods_row_version", "row_version > 0"),
    exclusion(
      "worker_assignment_periods",
      "excl_worker_assignment_periods_primary_overlap",
      [
        { expression: "organization_id", operator: "=" },
        { expression: "worker_engagement_id", operator: "=" },
        { expression: "daterange(valid_from, valid_to, '[)')", operator: "&&" },
      ],
      "is_primary = true",
    ),
    key("worker_reporting_lines", "uniq_worker_reporting_lines_org_id", "unique", ["organization_id", "reporting_line_id"]),
    foreignKey("worker_reporting_lines", "fk_worker_reporting_lines_subject", ["organization_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_engagement_id"]),
    foreignKey("worker_reporting_lines", "fk_worker_reporting_lines_manager", ["organization_id", "manager_worker_engagement_id"], "worker_engagements", ["organization_id", "worker_engagement_id"]),
    foreignKey("worker_reporting_lines", "fk_worker_reporting_lines_created_actor", ["organization_id", "created_by_membership_id"], "organization_members", ["org_id", "id"]),
    foreignKey("worker_reporting_lines", "fk_worker_reporting_lines_updated_actor", ["organization_id", "updated_by_membership_id"], "organization_members", ["org_id", "id"]),
    check("worker_reporting_lines", "chk_worker_reporting_lines_no_self_manager", "worker_engagement_id <> manager_worker_engagement_id"),
    check("worker_reporting_lines", "chk_worker_reporting_lines_dates", "valid_from < valid_to"),
    check("worker_reporting_lines", "chk_worker_reporting_lines_type", "line_type IN ('PRIMARY', 'DOTTED', 'MATRIX', 'FUNCTIONAL')"),
    check("worker_reporting_lines", "chk_worker_reporting_lines_row_version", "row_version > 0"),
    exclusion(
      "worker_reporting_lines",
      "excl_worker_reporting_lines_overlap",
      [
        { expression: "organization_id", operator: "=" },
        { expression: "worker_engagement_id", operator: "=" },
        { expression: "line_type", operator: "=" },
        { expression: "daterange(valid_from, valid_to, '[)')", operator: "&&" },
      ],
    ),
    key("worker_engagement_state_events", "pk_worker_engagement_state_events", "primary", ["organization_id", "event_id"]),
    key("worker_engagement_state_events", "uniq_worker_engagement_state_events_projection", "unique", ["organization_id", "event_id", "worker_engagement_id", "to_status"]),
    key("worker_engagement_state_events", "uniq_worker_engagement_state_events_command", "unique", ["organization_id", "command_scope", "command_id", "effect_ordinal"]),
    key("worker_engagement_state_events", "uniq_worker_engagement_state_events_source", "unique", ["organization_id", "source_type", "source_id", "source_ordinal"]),
    foreignKey("worker_engagement_state_events", "fk_worker_engagement_state_events_engagement", ["organization_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_engagement_id"], { deferrable: true }),
    check("worker_engagement_state_events", "chk_worker_engagement_state_events_ordinals", "effect_ordinal >= 0 AND source_ordinal >= 0"),
    check("worker_engagement_state_events", "chk_worker_engagement_state_events_snapshots", "(command_fence_id IS NULL OR command_fence_id > 0) AND (actor_membership_id IS NULL OR actor_membership_id > 0) AND (actor_user_id IS NULL OR btrim(actor_user_id) <> '')"),
    check("worker_engagement_state_events", "chk_worker_engagement_state_events_nonblank_keys", "btrim(command_scope) <> '' AND btrim(command_id) <> '' AND btrim(source_type) <> '' AND btrim(source_id) <> '' AND btrim(reason_code) <> ''"),
    check("worker_engagement_state_events", "chk_worker_engagement_state_events_kind", "event_kind IN ('LEGACY_SNAPSHOT', 'ENGAGEMENT_CREATED', 'STATUS_CHANGED')"),
    check("worker_engagement_state_events", "chk_worker_engagement_state_events_transition", "(event_kind = 'LEGACY_SNAPSHOT' AND from_status IS NULL) OR (event_kind = 'ENGAGEMENT_CREATED' AND from_status IS NULL AND to_status IN ('PLANNED', 'ACTIVE')) OR (event_kind = 'STATUS_CHANGED' AND ((from_status = 'PLANNED' AND to_status IN ('ACTIVE', 'CANCELLED')) OR (from_status = 'ACTIVE' AND to_status IN ('COMPLETED', 'TERMINATED'))))"),
    check("worker_engagement_state_events", "chk_worker_engagement_state_events_legacy_batch", "(migration_batch_id IS NULL OR btrim(migration_batch_id) <> '') AND (event_kind <> 'LEGACY_SNAPSHOT' OR migration_batch_id IS NOT NULL)"),
    check("worker_engagements", "chk_worker_engagements_dates", "ends_on IS NULL OR ends_on > starts_on", false),
    check("worker_engagements", "chk_worker_engagements_worker_type", "worker_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACTOR', 'CONSULTANT', 'INTERN', 'TEMPORARY', 'AGENCY', 'FREELANCER')", false),
    check("worker_engagements", "chk_worker_engagements_state_reason", "state_reason IS NULL OR btrim(state_reason) <> ''", false),
    foreignKey("worker_engagements", "fk_worker_engagements_org_worker_restrict_p1", ["organization_id", "worker_id"], "workers", ["organization_id", "worker_id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_org_manager", ["organization_id", "manager_engagement_id"], "worker_engagements", ["organization_id", "worker_engagement_id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_org_business_unit", ["organization_id", "business_unit_id"], "org_units", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_org_branch", ["organization_id", "branch_id"], "org_units", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_org_department", ["organization_id", "department_id"], "org_units", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_org_team", ["organization_id", "team_id"], "org_units", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_org_location", ["organization_id", "location_id"], "org_units", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_org_job_role", ["organization_id", "job_role_id"], "hr_job_roles", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_org_job_level", ["organization_id", "job_level_id"], "hr_job_levels", ["org_id", "id"], { validated: false }),
    foreignKey("worker_engagements", "fk_worker_engagements_last_state_projection", ["organization_id", "last_state_event_id", "worker_engagement_id", "status"], "worker_engagement_state_events", ["organization_id", "event_id", "worker_engagement_id", "to_status"], { validated: false, deferrable: true }),
  ],
  indexes: [
    i("org_units", "uniq_org_units_org_id", ["org_id", "id"], true),
    i("hr_job_roles", "uniq_hr_job_roles_org_id", ["org_id", "id"], true),
    i("hr_job_levels", "uniq_hr_job_levels_org_id", ["org_id", "id"], true),
    i("shift_templates", "uniq_shift_templates_org_id", ["org_id", "id"], true),
    i("worker_engagements", "idx_worker_engagements_org_manager", ["organization_id", "manager_engagement_id"]),
    i("worker_engagements", "idx_worker_engagements_org_business_unit", ["organization_id", "business_unit_id"]),
    i("worker_engagements", "idx_worker_engagements_org_branch", ["organization_id", "branch_id"]),
    i("worker_engagements", "idx_worker_engagements_org_department", ["organization_id", "department_id"]),
    i("worker_engagements", "idx_worker_engagements_org_team", ["organization_id", "team_id"]),
    i("worker_engagements", "idx_worker_engagements_org_location", ["organization_id", "location_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_engagement", ["organization_id", "worker_engagement_id", "valid_from"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_business_unit", ["organization_id", "business_unit_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_branch", ["organization_id", "branch_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_department", ["organization_id", "department_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_team", ["organization_id", "team_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_location", ["organization_id", "location_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_cost_center", ["organization_id", "cost_center_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_job_role", ["organization_id", "job_role_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_job_level", ["organization_id", "job_level_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_schedule", ["organization_id", "schedule_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_created_actor", ["organization_id", "created_by_membership_id"]),
    i("worker_assignment_periods", "idx_worker_assignment_periods_updated_actor", ["organization_id", "updated_by_membership_id"]),
    i("worker_reporting_lines", "idx_worker_reporting_lines_subject", ["organization_id", "worker_engagement_id", "line_type", "valid_from"]),
    i("worker_reporting_lines", "idx_worker_reporting_lines_manager", ["organization_id", "manager_worker_engagement_id", "valid_from"]),
    i("worker_reporting_lines", "idx_worker_reporting_lines_created_actor", ["organization_id", "created_by_membership_id"]),
    i("worker_reporting_lines", "idx_worker_reporting_lines_updated_actor", ["organization_id", "updated_by_membership_id"]),
    i("worker_engagement_state_events", "uniq_worker_engagement_state_events_legacy_snapshot", ["organization_id", "worker_engagement_id", "event_kind"], true, "event_kind = 'LEGACY_SNAPSHOT'"),
    i("worker_engagement_state_events", "idx_worker_engagement_state_events_engagement", ["organization_id", "worker_engagement_id", "effective_date", "event_id"]),
    i("worker_engagement_state_events", "idx_worker_engagement_state_events_fence", ["command_fence_id"]),
    i("worker_engagement_state_events", "idx_worker_engagement_state_events_actor", ["organization_id", "actor_membership_id"]),
  ],
  functions: [
    f("reject_hrms_append_only_mutation"),
    f("verify_workforce_org_unit_kinds", true, false),
    f("enforce_workforce_period_revision"),
    f("lock_worker_reporting_line_tenant"),
    f("lock_worker_engagement_state_transition"),
    f("verify_worker_reporting_line_cycles", true, false),
    f("verify_worker_engagement_state_chain", true, false),
    f("verify_worker_engagement_state_projection", true, false),
  ],
  enums: [],
};
