import {
  column as c,
  type ColumnRequirement,
} from "./bundle-definition-types";

export const exactColumnRelations0000 = [
  "app.hrms_sql_bundle_operations",
  "hrms_migration_profiles",
  "hrms_migration_profile_events",
  "hrms_scope_versions",
  "hr_person_legacy_map",
  "hr_employment_legacy_map",
  "hr_workforce_reconciliation_items",
];

export const columns0000: ColumnRequirement[] = [
  c("app.hrms_sql_bundle_operations", "operation_id", "text", true),
  c("app.hrms_sql_bundle_operations", "bundle_id", "text", true),
  c("app.hrms_sql_bundle_operations", "file_name", "text", true),
  c("app.hrms_sql_bundle_operations", "sql_hash", "text", true),
  c("app.hrms_sql_bundle_operations", "manifest_hash", "text", true),
  c("app.hrms_sql_bundle_operations", "root_migration_hash", "text", true),
  c("app.hrms_sql_bundle_operations", "state", "text", true),
  c("app.hrms_sql_bundle_operations", "attempts", "integer", true, "1"),
  c("app.hrms_sql_bundle_operations", "database_name", "text", true),
  c("app.hrms_sql_bundle_operations", "database_role", "text", true),
  c("app.hrms_sql_bundle_operations", "server_version_num", "integer", true),
  c("app.hrms_sql_bundle_operations", "started_at", "timestamp with time zone", true),
  c("app.hrms_sql_bundle_operations", "completed_at", "timestamp with time zone"),
  c("app.hrms_sql_bundle_operations", "last_error", "text"),
  c("hrms_migration_profiles", "organization_id", "text", true),
  c("hrms_migration_profiles", "workforce_read_mode", "text", true, "'LEGACY'"),
  c("hrms_migration_profiles", "workforce_write_mode", "text", true, "'LEGACY'"),
  c("hrms_migration_profiles", "history_mode", "text", true, "'LEGACY'"),
  c("hrms_migration_profiles", "hierarchy_read_mode", "text", true, "'ADJACENCY'"),
  c("hrms_migration_profiles", "hierarchy_write_mode", "text", true, "'LEGACY_ADAPTER'"),
  c("hrms_migration_profiles", "attendance_read_mode", "text", true, "'LEGACY'"),
  c("hrms_migration_profiles", "attendance_write_mode", "text", true, "'LEGACY'"),
  c("hrms_migration_profiles", "leave_read_mode", "text", true, "'LEGACY'"),
  c("hrms_migration_profiles", "leave_write_mode", "text", true, "'LEGACY'"),
  c("hrms_migration_profiles", "sensitive_read_mode", "text", true, "'LEGACY_ADAPTER'"),
  c("hrms_migration_profiles", "sensitive_write_mode", "text", true, "'LEGACY'"),
  c("hrms_migration_profiles", "minimum_sensitive_adapter_version", "integer", true, "1"),
  c("hrms_migration_profiles", "sensitive_plaintext_writes_retired_at", "timestamp with time zone"),
  c("hrms_migration_profiles", "profile_revision", "bigint", true, "1"),
  c("hrms_migration_profiles", "changed_at", "timestamp with time zone", true, "now()"),
  c("hrms_migration_profiles", "changed_by_platform_user_id", "text"),
  c("hrms_migration_profiles", "change_ticket", "text"),
  c("hrms_migration_profiles", "change_reason", "text"),
  c("hrms_migration_profiles", "rollback_deadline", "timestamp with time zone"),
  c("hrms_migration_profile_events", "organization_id", "text", true),
  c("hrms_migration_profile_events", "profile_revision", "bigint", true),
  c("hrms_migration_profile_events", "before_modes", "jsonb", true),
  c("hrms_migration_profile_events", "after_modes", "jsonb", true),
  c("hrms_migration_profile_events", "manifest_hash", "text", true),
  c("hrms_migration_profile_events", "proposed_by_platform_user_id", "text", true),
  c("hrms_migration_profile_events", "approved_by_platform_user_id", "text", true),
  c("hrms_migration_profile_events", "occurred_at", "timestamp with time zone", true, "now()"),
  c("hrms_scope_versions", "organization_id", "text", true),
  c("hrms_scope_versions", "scope_revision", "bigint", true, "1"),
  c("hrms_scope_versions", "updated_at", "timestamp with time zone", true, "now()"),
  c("hr_person_legacy_map", "org_id", "text", true),
  c("hr_person_legacy_map", "hr_person_id", "integer", true),
  c("hr_person_legacy_map", "organization_person_id", "text", true),
  c("hr_person_legacy_map", "row_version", "integer", true, "1"),
  c("hr_person_legacy_map", "created_by_membership_id", "integer", true),
  c("hr_person_legacy_map", "updated_by_membership_id", "integer", true),
  c("hr_person_legacy_map", "created_at", "timestamp with time zone", true, "now()"),
  c("hr_person_legacy_map", "updated_at", "timestamp with time zone", true, "now()"),
  c("hr_employment_legacy_map", "org_id", "text", true),
  c("hr_employment_legacy_map", "hr_employment_id", "integer", true),
  c("hr_employment_legacy_map", "hr_person_id", "integer", true),
  c("hr_employment_legacy_map", "organization_person_id", "text", true),
  c("hr_employment_legacy_map", "worker_id", "text", true),
  c("hr_employment_legacy_map", "worker_engagement_id", "text", true),
  c("hr_employment_legacy_map", "row_version", "integer", true, "1"),
  c("hr_employment_legacy_map", "created_by_membership_id", "integer", true),
  c("hr_employment_legacy_map", "updated_by_membership_id", "integer", true),
  c("hr_employment_legacy_map", "created_at", "timestamp with time zone", true, "now()"),
  c("hr_employment_legacy_map", "updated_at", "timestamp with time zone", true, "now()"),
  c("hr_workforce_reconciliation_items", "reconciliation_item_id", "bigint", true, null, "a"),
  c("hr_workforce_reconciliation_items", "org_id", "text", true),
  c("hr_workforce_reconciliation_items", "batch_id", "text", true),
  c("hr_workforce_reconciliation_items", "source_fingerprint", "text", true),
  c("hr_workforce_reconciliation_items", "issue_kind", "text", true),
  c("hr_workforce_reconciliation_items", "field_code", "text"),
  c("hr_workforce_reconciliation_items", "status", "text", true, "'OPEN'"),
  c("hr_workforce_reconciliation_items", "source_membership_id", "integer"),
  c("hr_workforce_reconciliation_items", "source_user_id", "text"),
  c("hr_workforce_reconciliation_items", "source_organization_person_id", "text"),
  c("hr_workforce_reconciliation_items", "source_worker_id", "text"),
  c("hr_workforce_reconciliation_items", "source_worker_engagement_id", "text"),
  c("hr_workforce_reconciliation_items", "source_hr_person_id", "integer"),
  c("hr_workforce_reconciliation_items", "source_hr_employment_id", "integer"),
  c("hr_workforce_reconciliation_items", "resolved_organization_person_id", "text"),
  c("hr_workforce_reconciliation_items", "resolved_worker_id", "text"),
  c("hr_workforce_reconciliation_items", "resolved_worker_engagement_id", "text"),
  c("hr_workforce_reconciliation_items", "classification", "text"),
  c("hr_workforce_reconciliation_items", "reason_code", "text"),
  c("hr_workforce_reconciliation_items", "source_snapshot_hash", "text", true),
  c("hr_workforce_reconciliation_items", "resolution_hash", "text"),
  c("hr_workforce_reconciliation_items", "manifest_hash", "text"),
  c("hr_workforce_reconciliation_items", "prepared_by_membership_id", "integer"),
  c("hr_workforce_reconciliation_items", "prepared_at", "timestamp with time zone"),
  c("hr_workforce_reconciliation_items", "approved_by_membership_id", "integer"),
  c("hr_workforce_reconciliation_items", "approved_at", "timestamp with time zone"),
  c("hr_workforce_reconciliation_items", "row_version", "integer", true, "1"),
  c("hr_workforce_reconciliation_items", "created_at", "timestamp with time zone", true, "now()"),
  c("hr_workforce_reconciliation_items", "updated_at", "timestamp with time zone", true, "now()"),
];
