import {
  check,
  column as c,
  foreignKey,
  index as i,
  key,
  triggerFunction as f,
  type FileDefinitionRequirement,
} from "./bundle-definition-types";
import {
  columns0003,
  exactColumnRelations0003,
} from "./bundle-columns-0003";

export const definitions0003: FileDefinitionRequirement = {
  columns: [
    ...columns0003,
    c("attendance", "worker_id", "text"),
    c("attendance", "worker_engagement_id", "text"),
  ],
  exactColumnRelations: exactColumnRelations0003,
  ownerOnlyRelations: [],
  constraints: [
    key("attendance_event_locators", "pk_attendance_event_locators", "primary", ["organization_id", "event_id"]),
    key("attendance_event_locators", "uniq_attendance_event_locators_org_event_date", "unique", ["organization_id", "event_id", "business_date"]),
    key("attendance_event_locators", "uniq_attendance_event_locators_command", "unique", ["organization_id", "command_scope", "command_id", "effect_ordinal"]),
    key("attendance_event_locators", "uniq_attendance_event_locators_source", "unique", ["organization_id", "source_type", "source_id", "source_ordinal"]),
    foreignKey("attendance_event_locators", "fk_attendance_event_locators_organization", ["organization_id"], "organizations", ["id"]),
    check("attendance_event_locators", "chk_attendance_event_locators_ordinals", "effect_ordinal >= 0 AND source_ordinal >= 0"),
    check("attendance_event_locators", "chk_attendance_event_locators_keys", "btrim(command_scope) <> '' AND btrim(command_id) <> '' AND btrim(source_type) <> '' AND btrim(source_id) <> ''"),
    key("attendance_events", "pk_attendance_events", "primary", ["organization_id", "business_date", "event_id"]),
    foreignKey("attendance_events", "fk_attendance_events_organization", ["organization_id"], "organizations", ["id"]),
    foreignKey("attendance_events", "fk_attendance_events_locator", ["organization_id", "event_id", "business_date"], "attendance_event_locators", ["organization_id", "event_id", "business_date"], { deferrable: true }),
    foreignKey("attendance_events", "fk_attendance_events_worker", ["organization_id", "worker_id"], "workers", ["organization_id", "worker_id"]),
    foreignKey("attendance_events", "fk_attendance_events_worker_engagement", ["organization_id", "worker_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"]),
    foreignKey("attendance_events", "fk_attendance_events_geofence", ["organization_id", "geofence_id"], "geofences", ["org_id", "id"]),
    foreignKey("attendance_events", "fk_attendance_events_correction_target", ["organization_id", "corrects_business_date", "corrects_event_id"], "attendance_events", ["organization_id", "business_date", "event_id"], { deferrable: true }),
    check("attendance_events", "chk_attendance_events_timezone", "btrim(organization_timezone) <> ''"),
    check("attendance_events", "chk_attendance_events_command_source", "btrim(command_scope) <> '' AND btrim(command_id) <> '' AND effect_ordinal >= 0 AND btrim(source_type) <> '' AND btrim(source_id) <> '' AND source_ordinal >= 0 AND (migration_batch_id IS NULL OR btrim(migration_batch_id) <> '')"),
    check("attendance_events", "chk_attendance_events_geofence_pair", "(geofence_id IS NULL) = (geofence_passed IS NULL)"),
    check("attendance_events", "chk_attendance_events_correction_shape", "( event_kind = 'CORRECTION' AND corrects_business_date IS NOT NULL AND corrects_event_id IS NOT NULL AND correction_action IS NOT NULL AND correction_reason_code IS NOT NULL AND btrim(correction_reason_code) <> '' ) OR ( event_kind <> 'CORRECTION' AND corrects_business_date IS NULL AND corrects_event_id IS NULL AND correction_action IS NULL AND replacement_event_kind IS NULL AND replacement_occurred_at IS NULL AND correction_reason_code IS NULL )"),
    check("attendance_events", "chk_attendance_events_replacement_shape", "( correction_action = 'REPLACE' AND replacement_event_kind IS NOT NULL AND replacement_occurred_at IS NOT NULL ) OR ( correction_action = 'VOID' AND replacement_event_kind IS NULL AND replacement_occurred_at IS NULL ) OR ( correction_action IS NULL AND replacement_event_kind IS NULL AND replacement_occurred_at IS NULL )"),
    check("attendance_events", "chk_attendance_events_not_self_correction", "corrects_event_id IS NULL OR corrects_event_id <> event_id OR corrects_business_date <> business_date"),
    key("attendance_correction_links", "pk_attendance_correction_links", "primary", ["organization_id", "original_event_id"]),
    key("attendance_correction_links", "uniq_attendance_correction_links_correction", "unique", ["organization_id", "correction_event_id"]),
    foreignKey("attendance_correction_links", "fk_attendance_correction_links_organization", ["organization_id"], "organizations", ["id"]),
    foreignKey("attendance_correction_links", "fk_attendance_correction_links_original_locator", ["organization_id", "original_event_id"], "attendance_event_locators", ["organization_id", "event_id"], { deferrable: true }),
    foreignKey("attendance_correction_links", "fk_attendance_correction_links_correction_locator", ["organization_id", "correction_event_id"], "attendance_event_locators", ["organization_id", "event_id"], { deferrable: true }),
    foreignKey("attendance_correction_links", "fk_attendance_correction_links_original_fact", ["organization_id", "original_business_date", "original_event_id"], "attendance_events", ["organization_id", "business_date", "event_id"], { deferrable: true }),
    foreignKey("attendance_correction_links", "fk_attendance_correction_links_correction_fact", ["organization_id", "correction_business_date", "correction_event_id"], "attendance_events", ["organization_id", "business_date", "event_id"], { deferrable: true }),
    check("attendance_correction_links", "chk_attendance_correction_links_not_self", "original_event_id <> correction_event_id"),
    key("attendance_event_evidence", "pk_attendance_event_evidence", "primary", ["organization_id", "business_date", "evidence_id"]),
    key("attendance_event_evidence", "uniq_attendance_event_evidence_event", "unique", ["organization_id", "business_date", "event_id"]),
    foreignKey("attendance_event_evidence", "fk_attendance_event_evidence_organization", ["organization_id"], "organizations", ["id"]),
    foreignKey("attendance_event_evidence", "fk_attendance_event_evidence_event", ["organization_id", "business_date", "event_id"], "attendance_events", ["organization_id", "business_date", "event_id"]),
    check("attendance_event_evidence", "chk_attendance_event_evidence_encryption", "encryption_version > 0 AND btrim(encrypted_coordinates) <> '' AND btrim(wrapped_data_key) <> '' AND btrim(kms_key_id) <> '' AND btrim(kms_key_version) <> ''"),
    check("attendance_event_evidence", "chk_attendance_event_evidence_precision", "coordinate_decimal_places BETWEEN 0 AND 4"),
    check("attendance_event_evidence", "chk_attendance_event_evidence_retention", "retention_expires_at > captured_at AND retention_expires_at <= captured_at + interval '30 days'"),
    key("attendance_evidence_legal_holds", "pk_attendance_evidence_legal_holds", "primary", ["organization_id", "business_date", "evidence_id"]),
    foreignKey("attendance_evidence_legal_holds", "fk_attendance_evidence_legal_holds_evidence", ["organization_id", "business_date", "evidence_id"], "attendance_event_evidence", ["organization_id", "business_date", "evidence_id"], { deleteAction: "c" }),
    check("attendance_evidence_legal_holds", "chk_attendance_evidence_legal_holds_approvers", "approved_by_membership_id <> second_approver_membership_id"),
    check("attendance_evidence_legal_holds", "chk_attendance_evidence_legal_holds_text", "btrim(case_id) <> '' AND btrim(reason_code) <> ''"),
    check("attendance_evidence_legal_holds", "chk_attendance_evidence_legal_holds_window", "review_due_at > approved_at AND review_due_at <= approved_at + interval '90 days' AND expires_at >= review_due_at"),
    check("attendance_evidence_legal_holds", "chk_attendance_evidence_legal_holds_version", "row_version > 0"),
    key("attendance_session_projections", "pk_attendance_session_projections", "primary", ["organization_id", "session_id"]),
    foreignKey("attendance_session_projections", "fk_attendance_session_projections_organization", ["organization_id"], "organizations", ["id"]),
    foreignKey("attendance_session_projections", "fk_attendance_session_projections_worker", ["organization_id", "worker_id"], "workers", ["organization_id", "worker_id"]),
    foreignKey("attendance_session_projections", "fk_attendance_session_worker_engagement", ["organization_id", "worker_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"]),
    foreignKey("attendance_session_projections", "fk_attendance_session_projections_opened_event", ["organization_id", "opened_event_business_date", "opened_event_id"], "attendance_events", ["organization_id", "business_date", "event_id"]),
    foreignKey("attendance_session_projections", "fk_attendance_session_projections_last_event", ["organization_id", "last_event_business_date", "last_event_id"], "attendance_events", ["organization_id", "business_date", "event_id"]),
    check("attendance_session_projections", "chk_attendance_session_projections_state", "(state = 'CLOSED' AND closed_at IS NOT NULL) OR (state <> 'CLOSED' AND closed_at IS NULL)"),
    check("attendance_session_projections", "chk_attendance_session_projections_break", "(state = 'ON_BREAK' AND break_started_at IS NOT NULL) OR (state <> 'ON_BREAK' AND break_started_at IS NULL)"),
    check("attendance_session_projections", "chk_attendance_session_projections_times", "closed_at IS NULL OR closed_at >= opened_at"),
    check("attendance_session_projections", "chk_attendance_session_projections_totals", "worked_minutes >= 0 AND break_minutes >= 0 AND projection_version > 0"),
    check("attendance_session_projections", "chk_attendance_session_projections_event_dates", "opened_event_business_date = business_date AND last_event_business_date = business_date"),
    key("attendance_daily_projections", "pk_attendance_daily_projections", "primary", ["organization_id", "business_date", "worker_id"]),
    foreignKey("attendance_daily_projections", "fk_attendance_daily_projections_organization", ["organization_id"], "organizations", ["id"]),
    foreignKey("attendance_daily_projections", "fk_attendance_daily_projections_worker", ["organization_id", "worker_id"], "workers", ["organization_id", "worker_id"]),
    foreignKey("attendance_daily_projections", "fk_attendance_daily_worker_engagement", ["organization_id", "worker_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"]),
    foreignKey("attendance_daily_projections", "fk_attendance_daily_projections_last_event", ["organization_id", "last_event_business_date", "last_event_id"], "attendance_events", ["organization_id", "business_date", "event_id"]),
    check("attendance_daily_projections", "chk_attendance_daily_projections_totals", "worked_minutes >= 0 AND break_minutes >= 0 AND overtime_minutes >= 0 AND session_count >= 0 AND projection_version > 0"),
    check("attendance_daily_projections", "chk_attendance_daily_projections_times", "first_check_in_at IS NULL OR last_check_out_at IS NULL OR last_check_out_at >= first_check_in_at"),
    check("attendance_daily_projections", "chk_attendance_daily_projections_event_date", "last_event_business_date = business_date"),
    check("attendance", "chk_attendance_canonical_subject_pair", "(worker_id IS NULL) = (worker_engagement_id IS NULL)", false),
    foreignKey("attendance", "fk_attendance_org_worker", ["org_id", "worker_id"], "workers", ["organization_id", "worker_id"], { validated: false }),
    foreignKey("attendance", "fk_attendance_worker_engagement", ["org_id", "worker_id", "worker_engagement_id"], "worker_engagements", ["organization_id", "worker_id", "worker_engagement_id"], { validated: false }),
    foreignKey("attendance_event_locators", "fk_attendance_event_locators_fact", ["organization_id", "business_date", "event_id"], "attendance_events", ["organization_id", "business_date", "event_id"], { deferrable: true }),
  ],
  indexes: [
    i("attendance", "idx_attendance_org_worker_date", ["org_id", "worker_id", "date"]),
    i("attendance", "idx_attendance_org_engagement_date", ["org_id", "worker_engagement_id", "date"]),
    i("attendance_event_locators", "idx_attendance_event_locators_org_date", ["organization_id", "business_date"]),
    i("attendance_events", "idx_attendance_events_org_worker_date", ["organization_id", "worker_id", "business_date"]),
    i("attendance_events", "idx_attendance_events_org_engagement_date", ["organization_id", "worker_engagement_id", "business_date"]),
    i("attendance_events", "idx_attendance_events_org_kind_date", ["organization_id", "event_kind", "business_date"]),
    i("attendance_events", "idx_attendance_events_correction_target", ["organization_id", "corrects_business_date", "corrects_event_id"]),
    i("attendance_correction_links", "idx_attendance_correction_links_original_fact", ["organization_id", "original_business_date", "original_event_id"]),
    i("attendance_correction_links", "idx_attendance_correction_links_correction_fact", ["organization_id", "correction_business_date", "correction_event_id"]),
    i("attendance_event_evidence", "idx_attendance_event_evidence_expiry", ["organization_id", "retention_expires_at"]),
    i("attendance_evidence_legal_holds", "idx_attendance_evidence_legal_holds_review", ["organization_id", "review_due_at"]),
    i("attendance_session_projections", "uniq_attendance_session_projections_open_worker", ["organization_id", "worker_id"], true, "closed_at IS NULL"),
    i("attendance_session_projections", "idx_attendance_session_projections_worker_date", ["organization_id", "worker_id", "business_date"]),
    i("attendance_session_projections", "idx_attendance_session_projections_state", ["organization_id", "state"]),
    i("attendance_daily_projections", "idx_attendance_daily_projections_worker_date", ["organization_id", "worker_id", "business_date"]),
    i("attendance_daily_projections", "idx_attendance_daily_projections_date", ["organization_id", "business_date"]),
  ],
  functions: [
    f("verify_attendance_locator_fact", true),
    f("verify_attendance_correction", true),
    f("verify_attendance_correction_link", true),
    f("verify_attendance_projection_events", true),
    f("reject_attendance_evidence_mutation"),
  ],
  enums: [
    { name: "attendance_event_kind", labels: ["CHECK_IN", "CHECK_OUT", "BREAK_START", "BREAK_END", "AUTO_CHECKOUT", "CORRECTION"] },
    { name: "attendance_event_source", labels: ["SELF_SERVICE", "HR_ADMIN", "BIOMETRIC_DEVICE", "REGULARIZATION", "IMPORT", "MIGRATION", "SYSTEM"] },
    { name: "attendance_correction_action", labels: ["VOID", "REPLACE"] },
    { name: "attendance_correction_replacement_kind", labels: ["CHECK_IN", "CHECK_OUT", "BREAK_START", "BREAK_END", "AUTO_CHECKOUT"] },
    { name: "attendance_accuracy_bucket", labels: ["LE_10_M", "GT_10_LE_50_M", "GT_50_LE_100_M", "GT_100_M", "UNKNOWN"] },
    { name: "attendance_distance_bucket", labels: ["INSIDE_RADIUS", "OUTSIDE_LE_50_M", "OUTSIDE_GT_50_M", "UNKNOWN"] },
    { name: "attendance_session_state", labels: ["WORKING", "ON_BREAK", "CLOSED"] },
  ],
};
