import {
  column as c,
  type ColumnRequirement,
} from "./bundle-definition-types";

export const exactColumnRelations0001 = [
  "worker_assignment_periods",
  "worker_reporting_lines",
  "worker_engagement_state_events",
];

export const columns0001: ColumnRequirement[] = [
  c("worker_assignment_periods", "assignment_period_id", "text", true),
  c("worker_assignment_periods", "organization_id", "text", true),
  c("worker_assignment_periods", "worker_engagement_id", "text", true),
  c("worker_assignment_periods", "valid_from", "date", true),
  c("worker_assignment_periods", "valid_to", "date", true, "'infinity'::date"),
  c("worker_assignment_periods", "is_primary", "boolean", true, "true"),
  c("worker_assignment_periods", "business_unit_id", "text"),
  c("worker_assignment_periods", "branch_id", "text"),
  c("worker_assignment_periods", "department_id", "text"),
  c("worker_assignment_periods", "team_id", "text"),
  c("worker_assignment_periods", "location_id", "text"),
  c("worker_assignment_periods", "cost_center_id", "text"),
  c("worker_assignment_periods", "job_role_id", "integer"),
  c("worker_assignment_periods", "job_level_id", "integer"),
  c("worker_assignment_periods", "employment_type", "text"),
  c("worker_assignment_periods", "designation", "text"),
  c("worker_assignment_periods", "schedule_id", "integer"),
  c("worker_assignment_periods", "row_version", "integer", true, "1"),
  c("worker_assignment_periods", "created_by_membership_id", "integer"),
  c("worker_assignment_periods", "updated_by_membership_id", "integer"),
  c("worker_assignment_periods", "created_at", "timestamp with time zone", true, "now()"),
  c("worker_assignment_periods", "updated_at", "timestamp with time zone", true, "now()"),
  c("worker_reporting_lines", "reporting_line_id", "text", true),
  c("worker_reporting_lines", "organization_id", "text", true),
  c("worker_reporting_lines", "worker_engagement_id", "text", true),
  c("worker_reporting_lines", "manager_worker_engagement_id", "text", true),
  c("worker_reporting_lines", "line_type", "text", true),
  c("worker_reporting_lines", "valid_from", "date", true),
  c("worker_reporting_lines", "valid_to", "date", true, "'infinity'::date"),
  c("worker_reporting_lines", "row_version", "integer", true, "1"),
  c("worker_reporting_lines", "created_by_membership_id", "integer"),
  c("worker_reporting_lines", "updated_by_membership_id", "integer"),
  c("worker_reporting_lines", "created_at", "timestamp with time zone", true, "now()"),
  c("worker_reporting_lines", "updated_at", "timestamp with time zone", true, "now()"),
  c("worker_engagement_state_events", "organization_id", "text", true),
  c("worker_engagement_state_events", "event_id", "bigint", true, null, "a"),
  c("worker_engagement_state_events", "worker_engagement_id", "text", true),
  c("worker_engagement_state_events", "event_kind", "text", true),
  c("worker_engagement_state_events", "from_status", "worker_engagement_status"),
  c("worker_engagement_state_events", "to_status", "worker_engagement_status", true),
  c("worker_engagement_state_events", "effective_date", "date", true),
  c("worker_engagement_state_events", "reason_code", "text", true),
  c("worker_engagement_state_events", "command_scope", "text", true),
  c("worker_engagement_state_events", "command_id", "text", true),
  c("worker_engagement_state_events", "effect_ordinal", "integer", true),
  c("worker_engagement_state_events", "source_type", "text", true),
  c("worker_engagement_state_events", "source_id", "text", true),
  c("worker_engagement_state_events", "source_ordinal", "integer", true),
  c("worker_engagement_state_events", "command_fence_id", "bigint"),
  c("worker_engagement_state_events", "migration_batch_id", "text"),
  c("worker_engagement_state_events", "actor_membership_id", "integer"),
  c("worker_engagement_state_events", "actor_user_id", "text"),
  c("worker_engagement_state_events", "recorded_at", "timestamp with time zone", true, "now()"),
];
