import {
  column as c,
  type ColumnRequirement,
} from "./bundle-definition-types";

export const exactColumnRelations0002 = [
  "worker_leave_entry_locators",
  "worker_leave_ledger_entries",
  "worker_leave_reversal_links",
  "worker_leave_balance_projections",
];

export const columns0002: ColumnRequirement[] = [
  c("worker_leave_entry_locators", "organization_id", "text", true),
  c("worker_leave_entry_locators", "entry_id", "bigint", true, null, "a"),
  c("worker_leave_entry_locators", "effective_date", "date", true),
  c("worker_leave_entry_locators", "command_scope", "text", true),
  c("worker_leave_entry_locators", "command_id", "text", true),
  c("worker_leave_entry_locators", "effect_ordinal", "integer", true),
  c("worker_leave_entry_locators", "source_type", "text", true),
  c("worker_leave_entry_locators", "source_id", "text", true),
  c("worker_leave_entry_locators", "source_ordinal", "integer", true),
  c("worker_leave_ledger_entries", "organization_id", "text", true),
  c("worker_leave_ledger_entries", "effective_date", "date", true),
  c("worker_leave_ledger_entries", "entry_id", "bigint", true),
  c("worker_leave_ledger_entries", "worker_id", "text", true),
  c("worker_leave_ledger_entries", "worker_engagement_id", "text", true),
  c("worker_leave_ledger_entries", "leave_type_id", "integer", true),
  c("worker_leave_ledger_entries", "period_key", "text", true),
  c("worker_leave_ledger_entries", "delta_days", "numeric(12,4)", true),
  c("worker_leave_ledger_entries", "entry_type", "text", true),
  c("worker_leave_ledger_entries", "provenance_status", "text", true),
  c("worker_leave_ledger_entries", "recorded_at", "timestamp with time zone", true, "now()"),
  c("worker_leave_ledger_entries", "command_scope", "text", true),
  c("worker_leave_ledger_entries", "command_id", "text", true),
  c("worker_leave_ledger_entries", "effect_ordinal", "integer", true),
  c("worker_leave_ledger_entries", "source_type", "text", true),
  c("worker_leave_ledger_entries", "source_id", "text", true),
  c("worker_leave_ledger_entries", "source_ordinal", "integer", true),
  c("worker_leave_ledger_entries", "actor_membership_id", "integer"),
  c("worker_leave_ledger_entries", "actor_user_id", "text"),
  c("worker_leave_ledger_entries", "migration_batch_id", "text"),
  c("worker_leave_reversal_links", "organization_id", "text", true),
  c("worker_leave_reversal_links", "original_entry_id", "bigint", true),
  c("worker_leave_reversal_links", "original_effective_date", "date", true),
  c("worker_leave_reversal_links", "reversal_entry_id", "bigint", true),
  c("worker_leave_reversal_links", "reversal_effective_date", "date", true),
  c("worker_leave_balance_projections", "organization_id", "text", true),
  c("worker_leave_balance_projections", "worker_id", "text", true),
  c("worker_leave_balance_projections", "leave_type_id", "integer", true),
  c("worker_leave_balance_projections", "period_key", "text", true),
  c("worker_leave_balance_projections", "balance_days", "numeric(12,4)", true, "0"),
  c("worker_leave_balance_projections", "last_processed_entry_id", "bigint"),
  c("worker_leave_balance_projections", "last_processed_effective_date", "date"),
  c("worker_leave_balance_projections", "projection_version", "integer", true, "1"),
  c("worker_leave_balance_projections", "updated_at", "timestamp with time zone", true, "now()"),
];
