import type { NotificationEventKey } from "./notification-events.catalog";
export * from "./notification-event-definition.types";
import type {
  NotificationChannel,
  NotificationPriority,
  NotificationLevel,
  SuppressionReason,
} from "./notification-event-definition.types";

export interface DispatchEventInput {
  /** REG-005: only keys declared in the catalog compile. */
  eventKey: NotificationEventKey;
  orgId: string;
  actorUserId?: string | null;
  targetUserIds: string[];
  /**
   * PIPE-011. The actor is excluded from `targetUserIds` by default — nobody wants
   * to be told about their own action. Set true only where self-notification is the
   * point, e.g. a security alert about your own session.
   */
  notifySelf?: boolean;
  /**
   * Collapses repeat emissions of the same intent onto one outbox row. Supply it only
   * where a replay is possible and must not double-notify — a bus consumer passes the
   * producer event id. Left unset, every emission is distinct, because the key carries
   * no timestamp and outbox rows are never deleted: a stable default would silently
   * swallow the second comment on a ticket forever.
   */
  dedupeKey?: string;
  /**
   * The outbox row's own key, set ONLY by the two replay paths — the after-commit
   * drain and `NotificationOutboxRelayService`. Never set by a caller.
   *
   * It exists because those paths used to pass the outbox key as `dedupeKey`, where
   * `buildNotifIdempotencyKey` reads it as the delivery discriminator and it WON
   * over the event's declared time window. Since the outbox key is a random UUID for
   * any emission without an explicit key (which is 84 of 111 emit sites), the
   * declared `dedupeWindowSeconds` could never apply: two identical emits seconds
   * apart built two idempotency keys and produced two notifications. Separating the
   * two lets the outbox key keep doing its job — making a REPLAY idempotent, which
   * is the only thing that works for the 9 events declaring a zero window — without
   * standing in for the window on every other event.
   */
  replayKey?: string;
  entityType?: string;
  entityId?: string;
  title?: string;
  message?: string;
  link?: string;
  priority?: NotificationPriority;
  category?: string;
  variables?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  /** Optional channel restriction for callers with an explicit delivery toggle. */
  channels?: NotificationChannel[];
  /** Durable HTML override for email templates generated by a domain module. */
  emailHtml?: string;
  /** Durable, base64-encoded email attachments. */
  attachments?: Array<{ filename: string; contentBase64: string; type: string }>;
}

export interface ChannelDecision {
  channel: NotificationChannel;
  action: "SEND" | "SUPPRESS";
  reason?: SuppressionReason;
  detail?: string;
}

export interface RoutingResult {
  userId: string;
  createInApp: boolean;
  channels: ChannelDecision[];
  priority: NotificationPriority;
  deferredUntil: Date | null;
  reasonText: string;
}

export interface ProviderSendInput {
  orgId: string;
  userId: string;
  /** COMP-002: mandatory mail must not advertise an unsubscribe it will not honour. */
  mandatory?: boolean;
  channel: NotificationChannel;
  recipientAddress?: string | null;
  title: string;
  message: string;
  link?: string | null;
  priority: NotificationPriority;
  metadata?: Record<string, unknown>;
  sandbox: boolean;
}

export interface ProviderSendResult {
  status: "SENT" | "FAILED";
  providerMessageId?: string;
  providerResponse?: Record<string, unknown>;
  costAmount?: number;
  costCurrency?: string;
  failureCode?: string;
  failureMessage?: string;
  retryable?: boolean;
}

export interface ProviderValidationResult {
  valid: boolean;
  message?: string;
}
