import { namespacesForModule } from "../../../common/rbac/module-vocabulary";
import type { Permission } from "./types";
import { MODULE_ACCESS_PERMISSIONS } from "./module-access";
import { SIGN_PERMISSIONS } from "./sign";
import { NOTIFICATIONS_PERMISSIONS } from "./notifications";
import { HR_PERMISSIONS } from "./hr";
import { CRM_PERMISSIONS } from "./crm";
import { ACCOUNTING_PERMISSIONS } from "./accounting";
import { INVENTORY_PERMISSIONS } from "./inventory";
import { KB_PERMISSIONS } from "./kb";
import { PAYROLL_PERMISSIONS } from "./payroll";
import { BLOG_PERMISSIONS } from "./blog";
import { SALES_PERMISSIONS } from "./sales";
import { SHARED_PERMISSIONS } from "./shared";
import { SUPPORT_PERMISSIONS } from "./support";
import { CHAT_PERMISSIONS } from "./chat";
import { CALENDAR_PERMISSIONS } from "./calendar";
import { API_TOKEN_PERMISSIONS } from "./api-tokens";
import { BILLING_PERMISSIONS } from "./billing";
import { WORKFLOW_PERMISSIONS } from "./workflows";
import { TIMESHEETS_PERMISSIONS } from "./timesheets";
import { ONBOARDING_PERMISSIONS } from "./onboarding";
import { PAYMENTS_PERMISSIONS } from "./payments";
import { SURVEYS_PERMISSIONS } from "./surveys";
import {
  QA_BUGS_PERMISSIONS,
  CLIENT_PORTAL_PERMISSIONS,
  PROJECT_APPROVALS_PERMISSIONS,
  PROJECTS_AI_PERMISSIONS,
  PROJECT_GOVERNANCE_PERMISSIONS,
  PROJECT_MEETINGS_PERMISSIONS,
  PROJECT_INCIDENTS_PERMISSIONS,
  PROJECT_FORMS_PERMISSIONS,
  PROJECT_PORTFOLIO_PERMISSIONS,
  PROJECT_MANAGED_PRODUCTS_PERMISSIONS,
  PROJECT_WORKSPACES_PERMISSIONS,
  PROJECT_TEAMS_PERMISSIONS,
  PROJECT_MEMBERS_PERMISSIONS,
  PROJECT_CUSTOMERS_PERMISSIONS,
  PROJECT_WORKFLOW_PERMISSIONS,
} from "./build";
import { FEEDBUCKET_PERMISSIONS } from "./feedbucket";
import { AI_SUMMARIES_PERMISSIONS, AI_USAGE_PERMISSIONS, EXECUTIVE_BRIEF_PERMISSIONS } from "./ai";
import { DIRECTORY_PERMISSIONS } from "./directory";
import { PARTY_PERMISSIONS } from "./party";
import { MAIL_PERMISSIONS } from "./mail";
import { STORAGE_PERMISSIONS } from "./storage";

export const PERMISSIONS: Permission[] = [
  ...MODULE_ACCESS_PERMISSIONS,
  ...SIGN_PERMISSIONS,
  ...NOTIFICATIONS_PERMISSIONS,
  ...HR_PERMISSIONS,
  ...CRM_PERMISSIONS,
  ...ACCOUNTING_PERMISSIONS,
  ...INVENTORY_PERMISSIONS,
  ...KB_PERMISSIONS,
  ...PAYROLL_PERMISSIONS,
  ...BLOG_PERMISSIONS,
  ...SALES_PERMISSIONS,
  ...SHARED_PERMISSIONS,
  ...SUPPORT_PERMISSIONS,
  ...CHAT_PERMISSIONS,
  ...CALENDAR_PERMISSIONS,
  ...API_TOKEN_PERMISSIONS,
  ...BILLING_PERMISSIONS,
  ...WORKFLOW_PERMISSIONS,
  ...TIMESHEETS_PERMISSIONS,
  ...ONBOARDING_PERMISSIONS,
  ...PAYMENTS_PERMISSIONS,
  ...SURVEYS_PERMISSIONS,
  ...QA_BUGS_PERMISSIONS,
  ...CLIENT_PORTAL_PERMISSIONS,
  ...PROJECT_APPROVALS_PERMISSIONS,
  ...PROJECTS_AI_PERMISSIONS,
  ...PROJECT_GOVERNANCE_PERMISSIONS,
  ...PROJECT_MEETINGS_PERMISSIONS,
  ...PROJECT_INCIDENTS_PERMISSIONS,
  ...PROJECT_FORMS_PERMISSIONS,
  ...PROJECT_PORTFOLIO_PERMISSIONS,
  ...PROJECT_MANAGED_PRODUCTS_PERMISSIONS,
  ...PROJECT_WORKSPACES_PERMISSIONS,
  ...PROJECT_TEAMS_PERMISSIONS,
  ...PROJECT_MEMBERS_PERMISSIONS,
  ...PROJECT_CUSTOMERS_PERMISSIONS,
  ...PROJECT_WORKFLOW_PERMISSIONS,
  ...FEEDBUCKET_PERMISSIONS,
  ...AI_SUMMARIES_PERMISSIONS,
  ...AI_USAGE_PERMISSIONS,
  ...EXECUTIVE_BRIEF_PERMISSIONS,
  ...DIRECTORY_PERMISSIONS,
  ...PARTY_PERMISSIONS,
  ...MAIL_PERMISSIONS,
  ...STORAGE_PERMISSIONS,
];

export const ALL_PERMISSION_NAMES: string[] = PERMISSIONS.map((p) => p.name);

export const moduleScopedPermissions = (moduleKey: string): string[] => {
  const namespaces = namespacesForModule(moduleKey);
  return ALL_PERMISSION_NAMES.filter((name) =>
    namespaces.includes(name.split(":")[0] ?? ""),
  );
};
