import type { Permission } from "./types";

export const CRM_PERMISSIONS: Permission[] = [
  {
    name: "crm:leads:view",
    resource: "crm:leads",
    action: "view",
    description: "View CRM leads",
    scopable: true,
  },
  {
    name: "crm:leads:create",
    resource: "crm:leads",
    action: "create",
    description: "Create CRM leads",
  },
  {
    name: "crm:leads:update",
    resource: "crm:leads",
    action: "update",
    description: "Update CRM leads",
    scopable: true,
  },
  {
    name: "crm:leads:assign",
    resource: "crm:leads",
    action: "assign",
    description: "Assign CRM leads",
  },
  {
    name: "crm:leads:delete",
    resource: "crm:leads",
    action: "delete",
    description: "Delete CRM leads",
    scopable: true,
  },
  {
    name: "crm:targets:view",
    resource: "crm:targets",
    action: "view",
    description: "View targets",
  },
  {
    name: "crm:targets:manage",
    resource: "crm:targets",
    action: "manage",
    description: "Manage targets",
  },
  {
    name: "crm:reports:view",
    resource: "crm:reports",
    action: "view",
    description: "View CRM reports",
  },
  {
    name: "crm:reports:export",
    resource: "crm:reports",
    action: "export",
    description: "Export CRM reports",
  },
  {
    name: "crm:data-quality:view",
    resource: "crm:data-quality",
    action: "view",
    description: "View CRM data quality dashboard",
  },
  {
    name: "crm:clients:read",
    resource: "crm:clients",
    action: "read",
    description: "View client accounts",
    scopable: true,
  },
  {
    name: "crm:clients:update",
    resource: "crm:clients",
    action: "update",
    description: "Update client accounts",
  },
  {
    name: "crm:incentives:read",
    resource: "crm:incentives",
    action: "read",
    description: "View incentives",
  },
  {
    name: "crm:incentives:approve",
    resource: "crm:incentives",
    action: "approve",
    description: "Approve incentives",
  },
  {
    name: "crm:deals:read",
    resource: "crm:deals",
    action: "read",
    description: "View CRM deals",
    scopable: true,
  },
  {
    name: "crm:deals:create",
    resource: "crm:deals",
    action: "create",
    description: "Create CRM deals",
  },
  {
    name: "crm:deals:update",
    resource: "crm:deals",
    action: "update",
    description: "Update CRM deals",
  },
  {
    name: "crm:deals:delete",
    resource: "crm:deals",
    action: "delete",
    description: "Delete CRM deals",
  },
  {
    name: "crm:deals:approve",
    resource: "crm:deals",
    action: "approve",
    description: "Approve or reject deal stage transitions",
  },
  {
    name: "crm:deals:forecast",
    resource: "crm:deals",
    action: "forecast",
    description: "Capture and view forecast snapshots",
  },
  {
    name: "crm:deals:manage",
    resource: "crm:deals",
    action: "manage",
    description: "Manage deal forecasts and overrides",
  },
  {
    name: "crm:contacts:view",
    resource: "crm:contacts",
    action: "view",
    description: "View CRM contacts",
    scopable: true,
  },
  {
    name: "crm:contacts:manage",
    resource: "crm:contacts",
    action: "manage",
    description: "Manage CRM contacts",
  },
  {
    name: "crm:quotes:read",
    resource: "crm:quotes",
    action: "read",
    description: "View CRM quotes",
    scopable: true,
  },
  {
    name: "crm:quotes:create",
    resource: "crm:quotes",
    action: "create",
    description: "Create CRM quotes",
  },
  {
    name: "crm:quotes:update",
    resource: "crm:quotes",
    action: "update",
    description: "Update CRM quotes",
  },
  {
    name: "crm:quotes:delete",
    resource: "crm:quotes",
    action: "delete",
    description: "Delete CRM quotes",
  },
  {
    name: "crm:clients:manage",
    resource: "crm:clients",
    action: "manage",
    description: "Manage client accounts",
  },
  {
    name: "crm:assignment-rules:manage",
    resource: "crm:assignment-rules",
    action: "manage",
    description: "Manage lead assignment rules",
  },
  {
    name: "crm:email-templates:manage",
    resource: "crm:email-templates",
    action: "manage",
    description: "Manage CRM email templates",
  },
  {
    name: "crm:scoring-rules:manage",
    resource: "crm:scoring-rules",
    action: "manage",
    description: "Manage lead scoring rules",
  },
  {
    name: "crm:sla:manage",
    resource: "crm:sla",
    action: "manage",
    description: "Manage CRM SLA policies",
  },
  {
    name: "crm:organizations:view",
    resource: "crm:organizations",
    action: "view",
    description: "View CRM organizations",
  },
  {
    name: "crm:organizations:manage",
    resource: "crm:organizations",
    action: "manage",
    description: "Manage CRM organizations",
  },
  {
    name: "crm:web-forms:manage",
    resource: "crm:web-forms",
    action: "manage",
    description: "Manage CRM web forms",
  },
  {
    name: "crm:territories:manage",
    resource: "crm:territories",
    action: "manage",
    description: "Manage CRM territories",
  },
  {
    name: "crm:automations:manage",
    resource: "crm:automations",
    action: "manage",
    description: "Manage CRM automation rules",
  },
  {
    name: "crm:sequences:manage",
    resource: "crm:sequences",
    action: "manage",
    description: "Manage CRM email/call sequences",
  },
  {
    name: "crm:products:manage",
    resource: "crm:products",
    action: "manage",
    description: "Manage the CRM product catalog",
  },
  {
    name: "crm:pricebooks:manage",
    resource: "crm:pricebooks",
    action: "manage",
    description: "Manage price books and quote settings",
  },
  {
    name: "crm:quotes:approve",
    resource: "crm:quotes",
    action: "approve",
    description: "Approve or reject quotes requiring approval",
  },
  {
    name: "crm:contacts:merge",
    resource: "crm:contacts",
    action: "merge",
    description: "Merge duplicate CRM contacts",
  },
  {
    name: "crm:organizations:merge",
    resource: "crm:organizations",
    action: "merge",
    description: "Merge duplicate CRM organizations/companies",
  },
  {
    name: "crm:customer360:view",
    resource: "crm:customer360",
    action: "view",
    description:
      "View Customer 360 aggregated profile (respects per-module permissions)",
  },
  {
    // The seam every provider adapter posts into. Gated because an open ingress
    // writes parties and activities into any tenant that can be named.
    name: "crm:ingress:submit",
    resource: "crm:ingress",
    action: "submit",
    description: "Deliver a normalised inbound communication event into the CRM",
  },
  {
    name: "crm:activities:view",
    resource: "crm:activities",
    action: "view",
    description: "Read the unified timeline of calls, emails, meetings, notes and tasks",
  },
  {
    name: "crm:activities:manage",
    resource: "crm:activities",
    action: "manage",
    description: "Log, edit, complete and remove activities on the timeline",
  },
  {
    name: "crm:settings:view",
    resource: "crm:settings",
    action: "view",
    description:
      "View CRM configuration (pipelines, stages, options, validation rules, blueprints)",
  },
  {
    name: "crm:settings:manage",
    resource: "crm:settings",
    action: "manage",
    description:
      "Manage CRM configuration (pipelines, stages, options, validation rules, blueprints)",
  },
  {
    name: "crm:ai:use",
    resource: "crm:ai",
    action: "use",
    description:
      "Use CRM AI features (scoring, enrichment, briefs, email generation)",
  },
  {
    name: "crm:tasks:view",
    resource: "crm:tasks",
    action: "view",
    description: "View CRM tasks and inbox",
    scopable: true,
  },
  {
    name: "crm:tasks:update",
    resource: "crm:tasks",
    action: "update",
    description: "Update, complete, and snooze CRM tasks",
    scopable: true,
  },
  {
    name: "crm:campaigns:view",
    resource: "crm:campaigns",
    action: "view",
    description: "View CRM campaigns, attribution reports, and ROI metrics",
  },
  {
    name: "crm:campaigns:manage",
    resource: "crm:campaigns",
    action: "manage",
    description: "Create, update, and delete CRM campaigns",
  },
  {
    name: "crm:offer-fulfillment:view",
    resource: "crm:offer-fulfillment",
    action: "view",
    description: "View CRM offer → Inventory SKU fulfillment mappings",
  },
  {
    name: "crm:offer-fulfillment:create",
    resource: "crm:offer-fulfillment",
    action: "create",
    description: "Create CRM offer → Inventory SKU fulfillment mappings",
  },
  {
    name: "crm:offer-fulfillment:update",
    resource: "crm:offer-fulfillment",
    action: "update",
    description: "Update CRM offer → Inventory SKU fulfillment mappings",
  },
  {
    name: "crm:offer-fulfillment:delete",
    resource: "crm:offer-fulfillment",
    action: "delete",
    description: "Delete CRM offer → Inventory SKU fulfillment mappings",
  },
  {
    name: "crm:autonomy:view",
    resource: "crm:autonomy",
    action: "view",
    description: "Review what the CRM decided and did on its own",
    // Scopable so a rep restricted to their own deals sees only the actions
    // taken on those, matching how the deals list narrows.
    scopable: true,
  },
  {
    name: "crm:autonomy:reverse",
    resource: "crm:autonomy",
    action: "reverse",
    description: "Reverse an autonomous CRM action",
  },
  {
    name: "crm:autonomy:manage",
    resource: "crm:autonomy",
    action: "manage",
    description: "Turn autonomous CRM action types on or off for the organisation",
  },
];
