import { definePermissions } from "./types";

export const HR_FOUNDATION_PERMISSIONS = definePermissions([
  {
    name: "hr:employees:view",
    resource: "hr:employees",
    action: "view",
    description: "View employee records",
    scopable: true,
  },
  {
    name: "hr:employees:create",
    resource: "hr:employees",
    action: "create",
    description: "Create new employees",
  },
  {
    name: "hr:employees:update",
    resource: "hr:employees",
    action: "update",
    description: "Update employee information",
  },
  {
    name: "hr:employees:delete",
    resource: "hr:employees",
    action: "delete",
    description: "Delete employees",
  },
  {
    name: "hr:attendance:view",
    resource: "hr:attendance",
    action: "view",
    description: "View attendance records",
  },
  {
    name: "hr:attendance:manage",
    resource: "hr:attendance",
    action: "manage",
    description: "Manage attendance records",
    scopable: true,
  },
  {
    name: "hr:leaves:view",
    resource: "hr:leaves",
    action: "view",
    description: "View leave requests",
  },
  {
    name: "hr:leaves:create",
    resource: "hr:leaves",
    action: "create",
    description: "Create leave requests",
  },
  {
    name: "hr:leaves:approve",
    resource: "hr:leaves",
    action: "approve",
    description: "Approve/reject leave requests",
    scopable: true,
  },
  {
    name: "hr:payroll:view",
    resource: "hr:payroll",
    action: "view",
    description: "View payroll information",
    scopable: true,
  },
  {
    name: "hr:payroll:generate",
    resource: "hr:payroll",
    action: "generate",
    description: "Generate payroll",
  },
  {
    name: "hr:payroll:approve",
    resource: "hr:payroll",
    action: "approve",
    description: "Approve payroll",
  },
  {
    name: "hr:salary:view",
    resource: "hr:salary",
    action: "view",
    description: "View salary structures",
    scopable: true,
  },
  {
    name: "hr:salary:manage",
    resource: "hr:salary",
    action: "manage",
    description: "Manage salary structures",
  },
  {
    name: "hr:expenses:view",
    resource: "hr:expenses",
    action: "view",
    description: "View expenses",
  },
  {
    name: "hr:expenses:create",
    resource: "hr:expenses",
    action: "create",
    description: "Create expense requests",
  },
  {
    name: "hr:expenses:approve",
    resource: "hr:expenses",
    action: "approve",
    description: "Approve expense requests",
    scopable: true,
  },
  {
    name: "hr:assets:view",
    resource: "hr:assets",
    action: "view",
    description: "View assets",
  },
  {
    name: "hr:assets:manage",
    resource: "hr:assets",
    action: "manage",
    description: "Manage assets",
  },
  {
    name: "hr:documents:view",
    resource: "hr:documents",
    action: "view",
    description: "View documents",
    scopable: true,
  },
  {
    name: "hr:documents:manage",
    resource: "hr:documents",
    action: "manage",
    description: "Manage documents",
    scopable: true,
  },
  {
    // Organisational authority, not a per-record one, so it is deliberately not scopable: a "publish to my team" reading would let a scoped manager decide what the whole company reads.
    name: "hr:documents:publish",
    resource: "hr:documents",
    action: "publish",
    description: "Classify company documents and publish them to the knowledge base",
  },
  {
    name: "hr:performance:view",
    resource: "hr:performance",
    action: "view",
    description: "View performance reviews",
  },
  {
    name: "hr:performance:manage",
    resource: "hr:performance",
    action: "manage",
    description: "Manage performance reviews",
  },
  {
    name: "hr:goals:view",
    resource: "hr:goals",
    action: "view",
    description: "View goals",
  },
  {
    name: "hr:goals:manage",
    resource: "hr:goals",
    action: "manage",
    description: "Manage goals",
  },
  {
    name: "hr:employees:manage",
    resource: "hr:employees",
    action: "manage",
    description: "Manage employees",
    scopable: true,
  },
  {
    name: "hr:reporting-lines:manage",
    resource: "hr:reporting-lines",
    action: "manage",
    description: "Set and schedule reporting managers, run bulk reporting changes, and confirm fallback managers",
  },
  {
    name: "hr:reporting-lines:review",
    resource: "hr:reporting-lines",
    action: "review",
    description: "Review employee requests to correct their reporting manager",
  },
  {
    name: "hr:reporting-lines:override",
    resource: "hr:reporting-lines",
    action: "override",
    description: "Configure the reporting manager policy, exceed the repeated-change threshold, and make emergency reporting changes",
  },
  {
    name: "hr:custom-fields:manage",
    resource: "hr:custom-fields",
    action: "manage",
    description: "Manage HR custom field definitions",
  },
  {
    name: "hr:sensitive:view",
    resource: "hr:sensitive",
    action: "view",
    description:
      "View employee sensitive fields (salary, bank, tax, government ID, medical)",
    sensitive: true,
  },
  {
    name: "hr:sensitive:manage",
    resource: "hr:sensitive",
    action: "manage",
    description: "Manage employee sensitive fields",
    sensitive: true,
  },
  {
    name: "hr:audit:view",
    resource: "hr:audit",
    action: "view",
    description: "View HR audit logs",
  },
]);
