import type { Permission } from "./types";

export const HR_FOUNDATION_PERMISSIONS: Permission[] = [
  {
    name: "hr:employees:view",
    resource: "hr:employees",
    action: "view",
    description: "View employee records",
    scopable: true,
  },
  {
    name: "hr:employees:create",
    resource: "hr:employees",
    action: "create",
    description: "Create new employees",
  },
  {
    name: "hr:employees:update",
    resource: "hr:employees",
    action: "update",
    description: "Update employee information",
  },
  {
    name: "hr:employees:delete",
    resource: "hr:employees",
    action: "delete",
    description: "Delete employees",
  },
  {
    name: "hr:attendance:view",
    resource: "hr:attendance",
    action: "view",
    description: "View attendance records",
  },
  {
    name: "hr:attendance:manage",
    resource: "hr:attendance",
    action: "manage",
    description: "Manage attendance records",
    scopable: true,
  },
  {
    name: "hr:leaves:view",
    resource: "hr:leaves",
    action: "view",
    description: "View leave requests",
  },
  {
    name: "hr:leaves:create",
    resource: "hr:leaves",
    action: "create",
    description: "Create leave requests",
  },
  {
    name: "hr:leaves:approve",
    resource: "hr:leaves",
    action: "approve",
    description: "Approve/reject leave requests",
    scopable: true,
  },
  {
    name: "hr:payroll:view",
    resource: "hr:payroll",
    action: "view",
    description: "View payroll information",
    scopable: true,
  },
  {
    name: "hr:payroll:generate",
    resource: "hr:payroll",
    action: "generate",
    description: "Generate payroll",
  },
  {
    name: "hr:payroll:approve",
    resource: "hr:payroll",
    action: "approve",
    description: "Approve payroll",
  },
  {
    name: "hr:salary:view",
    resource: "hr:salary",
    action: "view",
    description: "View salary structures",
    scopable: true,
  },
  {
    name: "hr:salary:manage",
    resource: "hr:salary",
    action: "manage",
    description: "Manage salary structures",
  },
  {
    name: "hr:expenses:view",
    resource: "hr:expenses",
    action: "view",
    description: "View expenses",
  },
  {
    name: "hr:expenses:create",
    resource: "hr:expenses",
    action: "create",
    description: "Create expense requests",
  },
  {
    name: "hr:expenses:approve",
    resource: "hr:expenses",
    action: "approve",
    description: "Approve expense requests",
    scopable: true,
  },
  {
    name: "hr:assets:view",
    resource: "hr:assets",
    action: "view",
    description: "View assets",
  },
  {
    name: "hr:assets:manage",
    resource: "hr:assets",
    action: "manage",
    description: "Manage assets",
  },
  {
    name: "hr:documents:view",
    resource: "hr:documents",
    action: "view",
    description: "View documents",
    scopable: true,
  },
  {
    name: "hr:documents:manage",
    resource: "hr:documents",
    action: "manage",
    description: "Manage documents",
    scopable: true,
  },
  {
    // Organisational authority, not a per-record one, so it is deliberately not scopable: a "publish to my team" reading would let a scoped manager decide what the whole company reads.
    name: "hr:documents:publish",
    resource: "hr:documents",
    action: "publish",
    description: "Classify company documents and publish them to the knowledge base",
  },
  {
    name: "hr:performance:view",
    resource: "hr:performance",
    action: "view",
    description: "View performance reviews",
  },
  {
    name: "hr:performance:manage",
    resource: "hr:performance",
    action: "manage",
    description: "Manage performance reviews",
  },
  {
    name: "hr:goals:view",
    resource: "hr:goals",
    action: "view",
    description: "View goals",
  },
  {
    name: "hr:goals:manage",
    resource: "hr:goals",
    action: "manage",
    description: "Manage goals",
  },
  {
    name: "hr:employees:manage",
    resource: "hr:employees",
    action: "manage",
    description: "Manage employees",
    scopable: true,
  },
  {
    name: "hr:custom-fields:manage",
    resource: "hr:custom-fields",
    action: "manage",
    description: "Manage HR custom field definitions",
  },
  {
    name: "hr:sensitive:view",
    resource: "hr:sensitive",
    action: "view",
    description:
      "View employee sensitive fields (salary, bank, tax, government ID, medical)",
  },
  {
    name: "hr:sensitive:manage",
    resource: "hr:sensitive",
    action: "manage",
    description: "Manage employee sensitive fields",
  },
  {
    name: "hr:audit:view",
    resource: "hr:audit",
    action: "view",
    description: "View HR audit logs",
  },
  {
    name: "hr:automations:view",
    resource: "hr:automations",
    action: "view",
    description: "View HR automation rules and run logs",
  },
  {
    name: "hr:automations:manage",
    resource: "hr:automations",
    action: "manage",
    description: "Manage HR automation rules",
  },
  {
    name: "hr:policies:view",
    resource: "hr:policies",
    action: "view",
    description: "View HR policies",
  },
  {
    name: "hr:policies:manage",
    resource: "hr:policies",
    action: "manage",
    description: "Create, update, activate, and archive HR policies",
  },
  {
    name: "hr:workflows:view",
    resource: "hr:workflows",
    action: "view",
    description: "View HR approval workflows and instances",
  },
  {
    name: "hr:workflows:manage",
    resource: "hr:workflows",
    action: "manage",
    description: "Manage HR approval workflow definitions",
  },
  {
    name: "hr:workflows:approve",
    resource: "hr:workflows",
    action: "approve",
    description: "Act on HR workflow approvals",
  },
  {
    name: "hr:templates:view",
    resource: "hr:templates",
    action: "view",
    description: "View HR templates",
  },
  {
    name: "hr:templates:manage",
    resource: "hr:templates",
    action: "manage",
    description: "Create and manage HR templates",
  },
  {
    name: "hr:interviews:view",
    resource: "hr:interviews",
    action: "view",
    description: "View interviews and scorecards",
  },
  {
    name: "hr:interviews:manage",
    resource: "hr:interviews",
    action: "manage",
    description: "Schedule interviews and submit scorecards",
  },
  {
    name: "hr:offers:view",
    resource: "hr:offers",
    action: "view",
    description: "View candidate offers",
  },
  {
    name: "hr:offers:manage",
    resource: "hr:offers",
    action: "manage",
    description: "Create, edit, and submit offers for approval",
  },
  {
    name: "hr:offers:approve",
    resource: "hr:offers",
    action: "approve",
    description: "Approve or reject offers submitted for approval",
  },
];
