import type { Permission } from "./types";

export const HR_WORKFORCE_PERMISSIONS: Permission[] = [
  {
    name: "hr:leaves:read",
    resource: "hr:leaves",
    action: "read",
    description: "Read leave requests",
  },
  {
    name: "hr:leaves:manage",
    resource: "hr:leaves",
    action: "manage",
    description: "Manage leave requests",
  },
  {
    name: "hr:expenses:read",
    resource: "hr:expenses",
    action: "read",
    description: "Read expense requests",
  },
  {
    name: "hr:expenses:manage",
    resource: "hr:expenses",
    action: "manage",
    description: "Manage expense requests",
  },
  {
    name: "hr:payrolls:read",
    resource: "hr:payrolls",
    action: "read",
    description: "Read payroll runs",
  },
  {
    name: "hr:payrolls:manage",
    resource: "hr:payrolls",
    action: "manage",
    description: "Manage payroll runs",
  },
  {
    name: "hr:bonuses:manage",
    resource: "hr:bonuses",
    action: "manage",
    description: "Manage bonuses",
  },
  {
    name: "hr:career-ladders:manage",
    resource: "hr:career-ladders",
    action: "manage",
    description: "Manage career ladders",
  },
  {
    name: "hr:compliance:manage",
    resource: "hr:compliance",
    action: "manage",
    description: "Manage compliance records",
  },
  {
    name: "hr:contracts:view",
    resource: "hr:contracts",
    action: "view",
    description: "View contingent contracts",
  },
  {
    name: "hr:contracts:manage",
    resource: "hr:contracts",
    action: "manage",
    description: "Manage contingent contracts",
  },
  {
    name: "hr:email-templates:manage",
    resource: "hr:email-templates",
    action: "manage",
    description: "Manage HR email templates",
  },
  {
    name: "hr:exit:manage",
    resource: "hr:exit",
    action: "manage",
    description: "Manage employee exits and offboarding",
  },
  {
    name: "hr:exit:view",
    resource: "hr:exit",
    action: "view",
    description: "View exits, resignations, and offboarding progress",
  },
  {
    name: "hr:exit:create",
    resource: "hr:exit",
    action: "create",
    description: "Submit resignations and initiate exits",
  },
  {
    name: "hr:exit:approve",
    resource: "hr:exit",
    action: "approve",
    description: "Final approval for resignations and terminations",
  },
  {
    name: "hr:helpdesk:view",
    resource: "hr:helpdesk",
    action: "view",
    description: "Open the employee support agent view",
  },
  {
    name: "hr:helpdesk:create",
    resource: "hr:helpdesk",
    action: "create",
    description: "Create HR helpdesk tickets",
  },
  {
    name: "hr:helpdesk:manage",
    resource: "hr:helpdesk",
    action: "manage",
    description: "Administer employee support: every queue, routing and SLA configuration",
  },
  {
    name: "hr:helpdesk:queue-hr",
    resource: "hr:helpdesk",
    action: "queue-hr",
    description: "Work the HR employee support queue",
  },
  {
    name: "hr:helpdesk:queue-it",
    resource: "hr:helpdesk",
    action: "queue-it",
    description: "Work the IT employee support queue",
  },
  {
    name: "hr:helpdesk:queue-finance",
    resource: "hr:helpdesk",
    action: "queue-finance",
    description: "Work the Finance employee support queue",
  },
  {
    name: "hr:helpdesk:queue-admin",
    resource: "hr:helpdesk",
    action: "queue-admin",
    description: "Work the Admin employee support queue",
  },
  {
    name: "hr:helpdesk:queue-legal",
    resource: "hr:helpdesk",
    action: "queue-legal",
    description: "Work the Legal employee support queue",
  },
  {
    name: "hr:communications:send",
    resource: "hr:communications",
    action: "manage",
    description: "Send bulk HR emails and communications",
  },
  {
    name: "hr:attendance:regularize",
    resource: "hr:attendance",
    action: "create",
    description: "Submit attendance regularization requests",
  },
  {
    name: "hr:probation:view",
    resource: "hr:probation",
    action: "view",
    description: "View probation reviews and due confirmations",
  },
  {
    name: "hr:probation:manage",
    resource: "hr:probation",
    action: "manage",
    description: "Manage probation reviews, extensions, and confirmations",
  },
  {
    name: "hr:succession:view",
    resource: "hr:succession",
    action: "view",
    description: "View succession plans (sensitive)",
    sensitive: true,
  },
  {
    name: "hr:succession:manage",
    resource: "hr:succession",
    action: "manage",
    description: "Manage succession plans (sensitive)",
    sensitive: true,
  },
  {
    name: "hr:engagement:view",
    resource: "hr:engagement",
    action: "view",
    description: "View engagement hub (mood, recognition, polls, communities)",
  },
  {
    name: "hr:engagement:manage",
    resource: "hr:engagement",
    action: "manage",
    description: "Manage engagement features and view aggregated analytics",
  },
  {
    name: "hr:cases:view",
    resource: "hr:cases",
    action: "view",
    description: "View HR cases and disciplinary actions",
  },
  {
    name: "hr:cases:manage",
    resource: "hr:cases",
    action: "manage",
    description:
      "Create and manage HR cases, investigations, and disciplinary actions",
  },
  {
    name: "hr:cases:confidential",
    resource: "hr:cases",
    action: "manage",
    description: "Access confidential case data and notes",
  },
  {
    name: "hr:safety:view",
    resource: "hr:safety",
    action: "view",
    description: "View safety incidents and submit wellness check-ins",
  },
  {
    name: "hr:safety:manage",
    resource: "hr:safety",
    action: "manage",
    description: "Manage safety incidents and view wellness analytics",
  },
  {
    name: "hr:benefits:view",
    resource: "hr:benefits",
    action: "view",
    description: "View employee benefit plans and enrollments",
  },
  {
    name: "hr:benefits:manage",
    resource: "hr:benefits",
    action: "manage",
    description: "Manage benefit plans, enrollment windows, and review claims",
  },
  {
    name: "hr:feedback:manage",
    resource: "hr:feedback",
    action: "manage",
    description: "Manage feedback",
  },
  {
    name: "hr:handbook:manage",
    resource: "hr:handbook",
    action: "manage",
    description: "Manage the employee handbook",
  },
  {
    name: "hr:integrations:manage",
    resource: "hr:integrations",
    action: "manage",
    description: "Manage HR integrations",
  },
  {
    name: "hr:onboarding:manage",
    resource: "hr:onboarding",
    action: "manage",
    description: "Manage onboarding",
    scopable: true,
  },
  {
    name: "hr:alumni:read",
    resource: "hr:alumni",
    action: "read",
    description: "Read alumni records",
  },
  {
    name: "hr:alumni:write",
    resource: "hr:alumni",
    action: "write",
    description: "Write alumni records",
  },
  {
    name: "hr:analytics:read",
    resource: "hr:analytics",
    action: "read",
    description: "Read HR analytics",
  },
  {
    name: "hr:headcount:read",
    resource: "hr:headcount",
    action: "read",
    description: "Read headcount planning",
  },
  {
    name: "hr:workforce:manage",
    resource: "hr:workforce",
    action: "manage",
    description: "Manage workforce plans, hiring plans, and headcount budgets",
  },
];
