import type { Permission } from "./types";

export const HR_PERMISSIONS: Permission[] = [
  {
    name: "hr:employees:view",
    resource: "hr:employees",
    action: "view",
    description: "View employees list",
  },
  {
    name: "hr:employees:create",
    resource: "hr:employees",
    action: "create",
    description: "Create new employees",
  },
  {
    name: "hr:employees:update",
    resource: "hr:employees",
    action: "update",
    description: "Update employee information",
  },
  {
    name: "hr:employees:delete",
    resource: "hr:employees",
    action: "delete",
    description: "Delete employees",
  },
  {
    name: "hr:attendance:view",
    resource: "hr:attendance",
    action: "view",
    description: "View attendance records",
  },
  {
    name: "hr:attendance:manage",
    resource: "hr:attendance",
    action: "manage",
    description: "Manage attendance records",
    scopable: true,
  },
  {
    name: "hr:leaves:view",
    resource: "hr:leaves",
    action: "view",
    description: "View leave requests",
  },
  {
    name: "hr:leaves:create",
    resource: "hr:leaves",
    action: "create",
    description: "Create leave requests",
  },
  {
    name: "hr:leaves:approve",
    resource: "hr:leaves",
    action: "approve",
    description: "Approve/reject leave requests",
    scopable: true,
  },
  {
    name: "hr:payroll:view",
    resource: "hr:payroll",
    action: "view",
    description: "View payroll information",
    scopable: true,
  },
  {
    name: "hr:payroll:generate",
    resource: "hr:payroll",
    action: "generate",
    description: "Generate payroll",
  },
  {
    name: "hr:payroll:approve",
    resource: "hr:payroll",
    action: "approve",
    description: "Approve payroll",
  },
  {
    name: "hr:salary:view",
    resource: "hr:salary",
    action: "view",
    description: "View salary structures",
  },
  {
    name: "hr:salary:manage",
    resource: "hr:salary",
    action: "manage",
    description: "Manage salary structures",
  },
  {
    name: "hr:expenses:view",
    resource: "hr:expenses",
    action: "view",
    description: "View expenses",
  },
  {
    name: "hr:expenses:create",
    resource: "hr:expenses",
    action: "create",
    description: "Create expense requests",
  },
  {
    name: "hr:expenses:approve",
    resource: "hr:expenses",
    action: "approve",
    description: "Approve expense requests",
    scopable: true,
  },
  {
    name: "hr:assets:view",
    resource: "hr:assets",
    action: "view",
    description: "View assets",
  },
  {
    name: "hr:assets:manage",
    resource: "hr:assets",
    action: "manage",
    description: "Manage assets",
  },
  {
    name: "hr:documents:view",
    resource: "hr:documents",
    action: "view",
    description: "View documents",
  },
  {
    name: "hr:documents:manage",
    resource: "hr:documents",
    action: "manage",
    description: "Manage documents",
  },
  {
    name: "hr:performance:view",
    resource: "hr:performance",
    action: "view",
    description: "View performance reviews",
  },
  {
    name: "hr:performance:manage",
    resource: "hr:performance",
    action: "manage",
    description: "Manage performance reviews",
  },
  {
    name: "hr:goals:view",
    resource: "hr:goals",
    action: "view",
    description: "View goals",
  },
  {
    name: "hr:goals:manage",
    resource: "hr:goals",
    action: "manage",
    description: "Manage goals",
  },
  {
    name: "hr:employees:read",
    resource: "hr:employees",
    action: "read",
    description: "Read employee records",
    scopable: true,
  },
  {
    name: "hr:employees:manage",
    resource: "hr:employees",
    action: "manage",
    description: "Manage employees",
    scopable: true,
  },
  {
    name: "hr:sensitive:view",
    resource: "hr:sensitive",
    action: "view",
    description:
      "View employee sensitive fields (salary, bank, tax, government ID, medical)",
  },
  {
    name: "hr:sensitive:manage",
    resource: "hr:sensitive",
    action: "manage",
    description: "Manage employee sensitive fields",
  },
  {
    name: "hr:audit:view",
    resource: "hr:audit",
    action: "view",
    description: "View HR audit logs",
  },
  {
    name: "hr:automations:view",
    resource: "hr:automations",
    action: "view",
    description: "View HR automation rules and run logs",
  },
  {
    name: "hr:automations:manage",
    resource: "hr:automations",
    action: "manage",
    description: "Manage HR automation rules",
  },
  {
    name: "hr:policies:view",
    resource: "hr:policies",
    action: "view",
    description: "View HR policies",
  },
  {
    name: "hr:policies:manage",
    resource: "hr:policies",
    action: "manage",
    description: "Create, update, activate, and archive HR policies",
  },
  {
    name: "hr:workflows:view",
    resource: "hr:workflows",
    action: "view",
    description: "View HR approval workflows and instances",
  },
  {
    name: "hr:workflows:manage",
    resource: "hr:workflows",
    action: "manage",
    description: "Manage HR approval workflow definitions",
  },
  {
    name: "hr:workflows:approve",
    resource: "hr:workflows",
    action: "approve",
    description: "Act on HR workflow approvals",
  },
  {
    name: "hr:templates:view",
    resource: "hr:templates",
    action: "view",
    description: "View HR templates",
  },
  {
    name: "hr:templates:manage",
    resource: "hr:templates",
    action: "manage",
    description: "Create and manage HR templates",
  },
  {
    name: "hr:interviews:view",
    resource: "hr:interviews",
    action: "view",
    description: "View interviews and scorecards",
  },
  {
    name: "hr:interviews:manage",
    resource: "hr:interviews",
    action: "manage",
    description: "Schedule interviews and submit scorecards",
  },
  {
    name: "hr:offers:view",
    resource: "hr:offers",
    action: "view",
    description: "View candidate offers",
  },
  {
    name: "hr:offers:manage",
    resource: "hr:offers",
    action: "manage",
    description: "Create, edit, and submit offers for approval",
  },
  {
    name: "hr:offers:approve",
    resource: "hr:offers",
    action: "approve",
    description: "Approve or reject offers submitted for approval",
  },
  {
    name: "hr:leaves:read",
    resource: "hr:leaves",
    action: "read",
    description: "Read leave requests",
  },
  {
    name: "hr:leaves:manage",
    resource: "hr:leaves",
    action: "manage",
    description: "Manage leave requests",
  },
  {
    name: "hr:expenses:read",
    resource: "hr:expenses",
    action: "read",
    description: "Read expense requests",
  },
  {
    name: "hr:expenses:manage",
    resource: "hr:expenses",
    action: "manage",
    description: "Manage expense requests",
  },
  {
    name: "hr:payrolls:read",
    resource: "hr:payrolls",
    action: "read",
    description: "Read payroll runs",
  },
  {
    name: "hr:payrolls:manage",
    resource: "hr:payrolls",
    action: "manage",
    description: "Manage payroll runs",
  },
  {
    name: "hr:bonuses:manage",
    resource: "hr:bonuses",
    action: "manage",
    description: "Manage bonuses",
  },
  {
    name: "hr:career-ladders:manage",
    resource: "hr:career-ladders",
    action: "manage",
    description: "Manage career ladders",
  },
  {
    name: "hr:compliance:manage",
    resource: "hr:compliance",
    action: "manage",
    description: "Manage compliance records",
  },
  {
    name: "hr:contracts:view",
    resource: "hr:contracts",
    action: "view",
    description: "View contingent contracts",
  },
  {
    name: "hr:contracts:manage",
    resource: "hr:contracts",
    action: "manage",
    description: "Manage contingent contracts",
  },
  {
    name: "hr:email-templates:manage",
    resource: "hr:email-templates",
    action: "manage",
    description: "Manage HR email templates",
  },
  {
    name: "hr:exit:manage",
    resource: "hr:exit",
    action: "manage",
    description: "Manage employee exits and offboarding",
  },
  {
    name: "hr:exit:view",
    resource: "hr:exit",
    action: "view",
    description: "View exits, resignations, and offboarding progress",
  },
  {
    name: "hr:exit:create",
    resource: "hr:exit",
    action: "create",
    description: "Submit resignations and initiate exits",
  },
  {
    name: "hr:exit:approve",
    resource: "hr:exit",
    action: "approve",
    description: "Final approval for resignations and terminations",
  },
  {
    name: "hr:helpdesk:view",
    resource: "hr:helpdesk",
    action: "view",
    description: "View own HR helpdesk tickets",
  },
  {
    name: "hr:helpdesk:create",
    resource: "hr:helpdesk",
    action: "create",
    description: "Create HR helpdesk tickets",
  },
  {
    name: "hr:helpdesk:manage",
    resource: "hr:helpdesk",
    action: "manage",
    description: "Manage all HR helpdesk tickets",
  },
  {
    name: "hr:communications:send",
    resource: "hr:communications",
    action: "manage",
    description: "Send bulk HR emails and communications",
  },
  {
    name: "hr:attendance:regularize",
    resource: "hr:attendance",
    action: "create",
    description: "Submit attendance regularization requests",
  },
  {
    name: "hr:probation:view",
    resource: "hr:probation",
    action: "view",
    description: "View probation reviews and due confirmations",
  },
  {
    name: "hr:probation:manage",
    resource: "hr:probation",
    action: "manage",
    description: "Manage probation reviews, extensions, and confirmations",
  },
  {
    name: "hr:succession:view",
    resource: "hr:succession",
    action: "view",
    description: "View succession plans (sensitive)",
  },
  {
    name: "hr:succession:manage",
    resource: "hr:succession",
    action: "manage",
    description: "Manage succession plans (sensitive)",
  },
  {
    name: "hr:engagement:view",
    resource: "hr:engagement",
    action: "view",
    description: "View engagement hub (mood, recognition, polls, communities)",
  },
  {
    name: "hr:engagement:manage",
    resource: "hr:engagement",
    action: "manage",
    description: "Manage engagement features and view aggregated analytics",
  },
  {
    name: "hr:cases:view",
    resource: "hr:cases",
    action: "view",
    description: "View HR cases and disciplinary actions",
  },
  {
    name: "hr:cases:manage",
    resource: "hr:cases",
    action: "manage",
    description:
      "Create and manage HR cases, investigations, and disciplinary actions",
  },
  {
    name: "hr:cases:confidential",
    resource: "hr:cases",
    action: "manage",
    description: "Access confidential case data and notes",
  },
  {
    name: "hr:safety:view",
    resource: "hr:safety",
    action: "view",
    description: "View safety incidents and submit wellness check-ins",
  },
  {
    name: "hr:safety:manage",
    resource: "hr:safety",
    action: "manage",
    description: "Manage safety incidents and view wellness analytics",
  },
  {
    name: "hr:benefits:view",
    resource: "hr:benefits",
    action: "view",
    description: "View employee benefit plans and enrollments",
  },
  {
    name: "hr:benefits:manage",
    resource: "hr:benefits",
    action: "manage",
    description: "Manage benefit plans, enrollment windows, and review claims",
  },
  {
    name: "hr:feedback:manage",
    resource: "hr:feedback",
    action: "manage",
    description: "Manage feedback",
  },
  {
    name: "hr:handbook:manage",
    resource: "hr:handbook",
    action: "manage",
    description: "Manage the employee handbook",
  },
  {
    name: "hr:integrations:manage",
    resource: "hr:integrations",
    action: "manage",
    description: "Manage HR integrations",
  },
  {
    name: "hr:onboarding:manage",
    resource: "hr:onboarding",
    action: "manage",
    description: "Manage onboarding",
  },
  {
    name: "hr:alumni:read",
    resource: "hr:alumni",
    action: "read",
    description: "Read alumni records",
  },
  {
    name: "hr:alumni:write",
    resource: "hr:alumni",
    action: "write",
    description: "Write alumni records",
  },
  {
    name: "hr:analytics:read",
    resource: "hr:analytics",
    action: "read",
    description: "Read HR analytics",
  },
  {
    name: "hr:headcount:read",
    resource: "hr:headcount",
    action: "read",
    description: "Read headcount planning",
  },
  {
    name: "hr:workforce:view",
    resource: "hr:workforce",
    action: "view",
    description: "View workforce plans and headcount forecasts",
  },
  {
    name: "hr:workforce:manage",
    resource: "hr:workforce",
    action: "manage",
    description: "Manage workforce plans, hiring plans, and headcount budgets",
  },
  {
    name: "hr:forms:view",
    resource: "hr:forms",
    action: "view",
    description: "View HR forms and submissions",
  },
  {
    name: "hr:forms:manage",
    resource: "hr:forms",
    action: "manage",
    description: "Build and manage HR forms and review submissions",
  },
  {
    name: "hr:legalhold:view",
    resource: "hr:legalhold",
    action: "view",
    description: "View legal holds and investigation locks",
  },
  {
    name: "hr:legalhold:manage",
    resource: "hr:legalhold",
    action: "manage",
    description: "Place and release legal holds (sensitive)",
  },
  {
    name: "hr:retention:manage",
    resource: "hr:retention",
    action: "manage",
    description:
      "Manage data retention policies and deletion/anonymization requests",
  },
  {
    name: "hr:positions:view",
    resource: "hr:positions",
    action: "view",
    description: "View positions and reorg scenarios",
  },
  {
    name: "hr:positions:manage",
    resource: "hr:positions",
    action: "manage",
    description: "Manage positions, headcount, and reorg simulations",
  },
  {
    name: "hr:labor:view",
    resource: "hr:labor",
    action: "view",
    description: "View union memberships, agreements, and labor cases",
  },
  {
    name: "hr:labor:manage",
    resource: "hr:labor",
    action: "manage",
    description: "Manage union relations and collective agreements",
  },
  {
    name: "hr:compensation:manage",
    resource: "hr:compensation",
    action: "manage",
    description:
      "Manage compensation planning cycles, calibration, and budgets",
  },
  {
    name: "hr:equity:view",
    resource: "hr:equity",
    action: "view",
    description: "View equity grants and vesting (sensitive)",
  },
  {
    name: "hr:equity:manage",
    resource: "hr:equity",
    action: "manage",
    description:
      "Manage ESOP/equity grants, vesting, and exercises (sensitive)",
  },
  {
    name: "hr:accommodations:view",
    resource: "hr:accommodations",
    action: "view",
    description: "View workplace accommodation requests",
  },
  {
    name: "hr:accommodations:manage",
    resource: "hr:accommodations",
    action: "manage",
    description: "Manage accommodation requests and adjustment tasks",
  },
  {
    name: "hr:emergency:manage",
    resource: "hr:emergency",
    action: "manage",
    description: "Manage emergency events and safety check-ins",
  },
  {
    name: "hr:identity:view",
    resource: "hr:identity",
    action: "view",
    description: "View identity provisioning and access lifecycle",
  },
  {
    name: "hr:identity:manage",
    resource: "hr:identity",
    action: "manage",
    description: "Manage joiner/mover/leaver access provisioning",
  },
  {
    name: "hr:eventstream:view",
    resource: "hr:eventstream",
    action: "view",
    description: "View the immutable HR event stream and BI exports",
  },
  {
    name: "hr:shifts:view",
    resource: "hr:shifts",
    action: "view",
    description: "View shift templates and assignments",
  },
  {
    name: "hr:shifts:manage",
    resource: "hr:shifts",
    action: "manage",
    description: "Manage shifts, rosters, and swap requests",
  },
  {
    name: "hr:geofencing:manage",
    resource: "hr:geofencing",
    action: "manage",
    description: "Manage geofence locations",
  },
  {
    name: "hr:biometric:manage",
    resource: "hr:biometric",
    action: "manage",
    description: "Manage biometric devices",
  },
  {
    name: "hr:feedback:view",
    resource: "hr:feedback",
    action: "view",
    description: "View 360 feedback cycles",
  },
  {
    name: "hr:kpis:view",
    resource: "hr:kpis",
    action: "view",
    description: "View KPIs and competency frameworks",
  },
  {
    name: "hr:kpis:manage",
    resource: "hr:kpis",
    action: "manage",
    description: "Manage KPIs and competency frameworks",
  },
  {
    name: "hr:announcements:view",
    resource: "hr:announcements",
    action: "view",
    description: "View announcements",
  },
  {
    name: "hr:announcements:manage",
    resource: "hr:announcements",
    action: "manage",
    description: "Create and manage announcements",
  },
  {
    name: "hr:tax:view",
    resource: "hr:tax",
    action: "view",
    description: "View tax declarations",
  },
  {
    name: "hr:tax:manage",
    resource: "hr:tax",
    action: "manage",
    description: "Review and approve tax declarations",
  },
  {
    name: "hr:travel:view",
    resource: "hr:travel",
    action: "view",
    description: "View travel requests",
  },
  {
    name: "hr:travel:create",
    resource: "hr:travel",
    action: "create",
    description: "Submit travel requests",
  },
  {
    name: "hr:travel:manage",
    resource: "hr:travel",
    action: "manage",
    description: "Approve travel requests",
  },
  {
    name: "hr:requisitions:view",
    resource: "hr:requisitions",
    action: "view",
    description: "View job requisitions",
  },
  {
    name: "hr:requisitions:manage",
    resource: "hr:requisitions",
    action: "manage",
    description: "Manage and approve job requisitions",
  },
  {
    name: "hr:payroll:manage",
    resource: "hr:payroll",
    action: "manage",
    description:
      "Manage payroll templates, policy settings, components, and calendar",
  },
  {
    name: "hr:payroll:lock",
    resource: "hr:payroll",
    action: "lock",
    description: "Lock an approved payroll run to freeze the snapshot",
  },
  {
    name: "hr:payroll:reopen",
    resource: "hr:payroll",
    action: "reopen",
    description: "Reopen an approved or locked payroll run with a reason",
  },
  {
    name: "hr:payroll:publish",
    resource: "hr:payroll",
    action: "publish",
    description: "Publish payslips to the employee portal or via email",
  },
  {
    name: "hr:payroll:export",
    resource: "hr:payroll",
    action: "export",
    description: "Export payroll reports, journal files, and bank payout files",
  },
  {
    name: "hr:bank-details:view",
    resource: "hr:bank-details",
    action: "view",
    description: "View unmasked employee bank account details (sensitive)",
  },
  {
    name: "hr:loans:view",
    resource: "hr:loans",
    action: "view",
    description: "View employee loan requests and EMI schedules",
  },
  {
    name: "hr:loans:manage",
    resource: "hr:loans",
    action: "manage",
    description:
      "Approve, disburse, and manage loan adjustments (skip/foreclose)",
  },
  {
    name: "hr:import:manage",
    resource: "hr:import",
    action: "manage",
    description: "Create, preview, commit, and roll back HR bulk import jobs",
  },
  {
    name: "hr:export:manage",
    resource: "hr:export",
    action: "manage",
    description:
      "Export HR entity data (employees, attendance, assets, leave balances, documents)",
  },
];
