import type { Permission } from "./types";

export const TIMESHEETS_PERMISSIONS: Permission[] = [
  {
    name: "timesheets:payroll:view",
    resource: "timesheets:payroll",
    action: "view",
    description: "View payroll queue and export history",
    scopable: true,
  },
  {
    name: "timesheets:payroll:export",
    resource: "timesheets:payroll",
    action: "export",
    description: "Run payroll exports and manage payroll mapping",
  },
  {
    name: "timesheets:entries:view",
    resource: "timesheets:entries",
    action: "view",
    description: "View time entries and timesheets",
    scopable: true,
  },
  {
    name: "timesheets:entries:create",
    resource: "timesheets:entries",
    action: "create",
    description: "Log time and submit timesheets",
  },
  {
    name: "timesheets:entries:update",
    resource: "timesheets:entries",
    action: "update",
    description: "Edit own draft or rejected time entries",
  },
  {
    name: "timesheets:entries:void",
    resource: "timesheets:entries",
    action: "void",
    description: "Void time entries with a reason",
  },
  {
    name: "timesheets:team:view",
    resource: "timesheets:team",
    action: "view",
    description: "View team timesheets and submission status",
    scopable: true,
  },
  {
    name: "timesheets:approvals:view",
    resource: "timesheets:approvals",
    action: "view",
    description: "View the timesheet approval queue",
    scopable: true,
  },
  {
    name: "timesheets:approvals:manage",
    resource: "timesheets:approvals",
    action: "manage",
    description: "Approve, reject, reopen, and lock timesheets",
    scopable: true,
  },
  {
    name: "timesheets:billing:view",
    resource: "timesheets:billing",
    action: "view",
    description: "View the billing queue and uninvoiced hours",
  },
  {
    name: "timesheets:billing:export",
    resource: "timesheets:billing",
    action: "export",
    description: "Export approved billable hours",
  },
  {
    name: "timesheets:billing:invoice",
    resource: "timesheets:billing",
    action: "invoice",
    description: "Create invoice drafts from approved billable hours",
  },
  {
    name: "timesheets:reports:view",
    resource: "timesheets:reports",
    action: "view",
    description: "View timesheet reports and analytics",
    scopable: true,
  },
  {
    name: "timesheets:settings:view",
    resource: "timesheets:settings",
    action: "view",
    description: "View timesheet settings",
  },
  {
    name: "timesheets:settings:manage",
    resource: "timesheets:settings",
    action: "manage",
    description: "Manage timesheet settings and policies",
  },
  {
    name: "timesheets:rates:view",
    resource: "timesheets:rates",
    action: "view",
    description: "View bill rates and rate cards",
  },
  {
    name: "timesheets:rates:manage",
    resource: "timesheets:rates",
    action: "manage",
    description: "Manage bill rates and rate cards",
  },
  {
    name: "timesheets:audit:view",
    resource: "timesheets:audit",
    action: "view",
    description: "View the timesheet audit trail",
  },
  {
    name: "timesheets:budgets:view",
    resource: "timesheets:budgets",
    action: "view",
    description: "View project budgets and burn",
  },
  {
    name: "timesheets:budgets:manage",
    resource: "timesheets:budgets",
    action: "manage",
    description: "Create and manage project budgets",
  },
  {
    name: "timesheets:exceptions:view",
    resource: "timesheets:exceptions",
    action: "view",
    description: "View timesheet exceptions and data-quality issues",
    scopable: true,
  },
  {
    name: "timesheets:exceptions:manage",
    resource: "timesheets:exceptions",
    action: "manage",
    description: "Resolve, dismiss, and run timesheet exception detection",
  },
];
