export const AI_FEATURE_COSTS: Readonly<Record<string, number>> = {
  "crm.score-lead": 1,
  // Ticket 12: one small-model call per inbound activity, reading a capped
  // conversation and returning a next step plus a stage inference.
  "crm.autonomy-extract": 1,
  // Ticket 15: the second opinion. Registered so its spend is attributed and
  // capped like any other feature -- an unregistered key silently reserves one
  // credit, which is a quiet under-reserve rather than an error.
  "crm.autonomy-shadow-score": 1,
  "crm.predict-deal": 1,
  "crm.churn-risk": 1,
  "crm.next-action": 1,
  "crm.account-summary": 1,
  "crm.meeting-prep": 1,
  "crm.nl-search": 1,
  "crm.enrich-lead": 2,
  "crm.generate-email": 1,
  "crm.objection-handler": 1,
  "crm.sentiment": 1,
  "crm.summarize": 1,
  "crm.report-narrator": 1,
  "crm.prioritize-tasks": 1,
  "crm.copilot.summary": 1,
  "crm.copilot.next-best-actions": 1,
  "crm.copilot.email-draft": 1,
  "crm.copilot.notes": 1,
  "crm.copilot.objection": 1,
  "crm.copilot.duplicates": 1,
  "hr.attrition-risk": 1,
  "hr.generate-review": 2,
  "hr.generate-jd": 1,
  "hr.score-candidate": 1,
  "hr.composite-score": 2,
  "hr.resume-parse": 1,
  "hr.email-template-generate": 1,
  "hr.helpdesk-reply": 1,
  "pm.summary": 1,
  "pm.risks": 1,
  "pm.client-update": 1,
  "pm.plan": 2,
  "pm.extract-tasks": 1,
  "pm.ask": 1,
  "ticket.summarize": 1,
  "ticket.summarize-comments": 1,
  "ticket.improve-description": 1,
  "ticket.suggest-subtasks": 1,
  "ticket.generate-checklist": 1,
  "ticket.suggest-title": 1,
  "ticket.suggest-fields": 1,
  "support.analysis": 1,
  "support.reply": 1,
  "support.macro": 1,
  "support.translate": 1,
  "support.handoff": 1,
  "support.root-cause": 2,
  "kb.ask": 1,
  "kb.public-ask": 1,
  "kb.public-embedding": 1,
  // Embedding ceilings are fractional because the settled charge is tiny: a query
  // embed lands on the 10-milli floor, and `chunkText` caps a document at 400
  // chunks, whose worst case settles near 450 milli.
  "kb.search": 0.05,
  "kb.indexing": 1,
  "support.embedding": 0.05,
  "support.kb-search": 0.05,
  "chat.message": 1,
  "feedbucket.analyze": 5,
  "feedbucket.assist": 5,
  "inv.insight-explain": 1,
  "inv.reorder-explain": 3,
  "inv.supplier-delay-briefing": 2,
  // F1/F2/F3/F5. These five reached the gateway with no catalog entry, so each
  // reserved the `?? 1` default regardless of what it actually costs — a quiet
  // under-reserve rather than an error, which is exactly the shape §4's
  // reserve-before-the-call rule exists to prevent. The ops brief and the
  // copilot's plan call are one small structured response each. The copilot's
  // answer reads up to three capped tables, and the demand-risk narrative reads
  // a stored forecast plus its backtest metrics, so both are larger prompts. The
  // report builder emits one small config and nothing else.
  "inv.ops-brief": 1,
  "inv.copilot-plan": 1,
  "inv.copilot-answer": 2,
  "inv.demand-risk": 2,
  "inv.report-builder": 1,
  "accounting.variance-explain": 2,
  "accounting.reconciliation-explain": 1,
  "accounting.extract-document": 5,
  "meetings.prep": 2,
  "meetings.follow-up": 1,
  "exec.brief.generate": 5,
  "pm.weekly-update": 1,
  "pm.change-impact": 1,
  "pm.extract-meeting-actions": 1,
  "ticket.handoff": 1,
  "crm.meeting-follow-up": 1,
  "crm.stale-pipeline": 1,
  "crm.data-quality": 1,
  "hr.policy-qa": 1,
  "hr.interview-kit": 2,
  "hr.letter-draft": 1,
  "hr.interview-notes-summary": 1,
  "workspace.ask": 1,
  "kb.research-brief": 2,
  "support.kb-gap-draft": 3,
  "inv.digest-narrate": 1,
  "timesheets.period-summary": 1,
  "timesheets.describe-entry": 1,
  "timesheets.billing-narrative": 1,
  "timesheets.reports-narrative": 1,
  "timesheets.rejection-draft": 1,
  "sign.summarize-document": 2,
  "kb.page-summarize": 1,
  "kb.page-ask": 1,
  "kb.page-improve": 2,
  "kb.page-suggest-related": 1,
  "kb.article-summarize": 1,
  "kb.article-ask": 1,
  "kb.article-improve": 2,
  "kb.article-suggest-related": 1,
  "blog.improve-writing": 1,
  "blog.suggest-title": 1,
  "blog.summarize": 1,
  "survey.summarize-responses": 2,
  "chat.summarize": 1,
  "payroll.explain-payslip": 1,
  "timesheets.summarize": 1,
  "mail.inbox-summary": 2,
  "mail.thread-summary": 1,
  "mail.draft": 1,
};

function getFeatureCost(feature: string): number {
  return AI_FEATURE_COSTS[feature] ?? 1;
}

export function getReserveEstimateMilli(feature: string): number {
  return Math.round(getFeatureCost(feature) * 1000);
}
