export interface Permission {
  name: string;
  resource: string;
  action: string;
  description: string;
  scopable?: boolean;
}

const HR_PERMISSIONS: Permission[] = [
  { name: "hr:employees:view", resource: "hr:employees", action: "view", description: "View employees list" },
  { name: "hr:employees:create", resource: "hr:employees", action: "create", description: "Create new employees" },
  { name: "hr:employees:update", resource: "hr:employees", action: "update", description: "Update employee information" },
  { name: "hr:employees:delete", resource: "hr:employees", action: "delete", description: "Delete employees" },
  { name: "hr:attendance:view", resource: "hr:attendance", action: "view", description: "View attendance records" },
  { name: "hr:attendance:manage", resource: "hr:attendance", action: "manage", description: "Manage attendance records", scopable: true },
  { name: "hr:leaves:view", resource: "hr:leaves", action: "view", description: "View leave requests" },
  { name: "hr:leaves:create", resource: "hr:leaves", action: "create", description: "Create leave requests" },
  { name: "hr:leaves:approve", resource: "hr:leaves", action: "approve", description: "Approve/reject leave requests", scopable: true },
  { name: "hr:payroll:view", resource: "hr:payroll", action: "view", description: "View payroll information" },
  { name: "hr:payroll:generate", resource: "hr:payroll", action: "generate", description: "Generate payroll" },
  { name: "hr:payroll:approve", resource: "hr:payroll", action: "approve", description: "Approve payroll" },
  { name: "hr:payroll:read", resource: "hr:payroll", action: "read", description: "Read payroll data for reporting and analytics" },
  { name: "hr:salary:view", resource: "hr:salary", action: "view", description: "View salary structures" },
  { name: "hr:salary:manage", resource: "hr:salary", action: "manage", description: "Manage salary structures" },
  { name: "hr:expenses:view", resource: "hr:expenses", action: "view", description: "View expenses" },
  { name: "hr:expenses:create", resource: "hr:expenses", action: "create", description: "Create expense requests" },
  { name: "hr:expenses:approve", resource: "hr:expenses", action: "approve", description: "Approve expense requests", scopable: true },
  { name: "hr:assets:view", resource: "hr:assets", action: "view", description: "View assets" },
  { name: "hr:assets:manage", resource: "hr:assets", action: "manage", description: "Manage assets" },
  { name: "hr:documents:view", resource: "hr:documents", action: "view", description: "View documents" },
  { name: "hr:documents:manage", resource: "hr:documents", action: "manage", description: "Manage documents" },
  { name: "hr:performance:view", resource: "hr:performance", action: "view", description: "View performance reviews" },
  { name: "hr:performance:manage", resource: "hr:performance", action: "manage", description: "Manage performance reviews" },
  { name: "hr:goals:view", resource: "hr:goals", action: "view", description: "View goals" },
  { name: "hr:goals:manage", resource: "hr:goals", action: "manage", description: "Manage goals" },
  { name: "hr:employees:read", resource: "hr:employees", action: "read", description: "Read employee records" },
  { name: "hr:employees:manage", resource: "hr:employees", action: "manage", description: "Manage employees", scopable: true },
  { name: "hr:leaves:read", resource: "hr:leaves", action: "read", description: "Read leave requests" },
  { name: "hr:leaves:manage", resource: "hr:leaves", action: "manage", description: "Manage leave requests" },
  { name: "hr:expenses:read", resource: "hr:expenses", action: "read", description: "Read expense requests" },
  { name: "hr:expenses:manage", resource: "hr:expenses", action: "manage", description: "Manage expense requests" },
  { name: "hr:payrolls:read", resource: "hr:payrolls", action: "read", description: "Read payroll runs" },
  { name: "hr:payrolls:manage", resource: "hr:payrolls", action: "manage", description: "Manage payroll runs" },
  { name: "hr:bonuses:manage", resource: "hr:bonuses", action: "manage", description: "Manage bonuses" },
  { name: "hr:career-ladders:manage", resource: "hr:career-ladders", action: "manage", description: "Manage career ladders" },
  { name: "hr:compliance:manage", resource: "hr:compliance", action: "manage", description: "Manage compliance records" },
  { name: "hr:email-templates:manage", resource: "hr:email-templates", action: "manage", description: "Manage HR email templates" },
  { name: "hr:exit:manage", resource: "hr:exit", action: "manage", description: "Manage employee exits and offboarding" },
  { name: "hr:feedback:manage", resource: "hr:feedback", action: "manage", description: "Manage feedback" },
  { name: "hr:handbook:manage", resource: "hr:handbook", action: "manage", description: "Manage the employee handbook" },
  { name: "hr:integrations:manage", resource: "hr:integrations", action: "manage", description: "Manage HR integrations" },
  { name: "hr:onboarding:manage", resource: "hr:onboarding", action: "manage", description: "Manage onboarding" },
  { name: "hr:alumni:read", resource: "hr:alumni", action: "read", description: "Read alumni records" },
  { name: "hr:analytics:read", resource: "hr:analytics", action: "read", description: "Read HR analytics" },
  { name: "hr:headcount:read", resource: "hr:headcount", action: "read", description: "Read headcount planning" },
];

const CRM_PERMISSIONS: Permission[] = [
  { name: "crm:leads:view", resource: "crm:leads", action: "view", description: "View CRM leads", scopable: true },
  { name: "crm:leads:create", resource: "crm:leads", action: "create", description: "Create CRM leads" },
  { name: "crm:leads:update", resource: "crm:leads", action: "update", description: "Update CRM leads", scopable: true },
  { name: "crm:leads:assign", resource: "crm:leads", action: "assign", description: "Assign CRM leads" },
  { name: "crm:leads:delete", resource: "crm:leads", action: "delete", description: "Delete CRM leads", scopable: true },
  { name: "crm:targets:view", resource: "crm:targets", action: "view", description: "View targets" },
  { name: "crm:targets:manage", resource: "crm:targets", action: "manage", description: "Manage targets" },
  { name: "crm:reports:view", resource: "crm:reports", action: "view", description: "View CRM reports" },
  { name: "crm:reports:export", resource: "crm:reports", action: "export", description: "Export CRM reports" },
  { name: "crm:clients:read", resource: "crm:clients", action: "read", description: "View client accounts" },
  { name: "crm:clients:update", resource: "crm:clients", action: "update", description: "Update client accounts" },
  { name: "crm:incentives:read", resource: "crm:incentives", action: "read", description: "View incentives" },
  { name: "crm:incentives:approve", resource: "crm:incentives", action: "approve", description: "Approve incentives" },
  { name: "crm:incentives:config", resource: "crm:incentives", action: "config", description: "Configure incentive rates" },
  { name: "crm:deals:read", resource: "crm:deals", action: "read", description: "View CRM deals" },
  { name: "crm:deals:create", resource: "crm:deals", action: "create", description: "Create CRM deals" },
  { name: "crm:deals:delete", resource: "crm:deals", action: "delete", description: "Delete CRM deals" },
  { name: "crm:quotes:delete", resource: "crm:quotes", action: "delete", description: "Delete CRM quotes" },
  { name: "crm:clients:manage", resource: "crm:clients", action: "manage", description: "Manage client accounts" },
  { name: "crm:assignment-rules:manage", resource: "crm:assignment-rules", action: "manage", description: "Manage lead assignment rules" },
  { name: "crm:email-templates:manage", resource: "crm:email-templates", action: "manage", description: "Manage CRM email templates" },
  { name: "crm:scoring-rules:manage", resource: "crm:scoring-rules", action: "manage", description: "Manage lead scoring rules" },
  { name: "crm:sla:manage", resource: "crm:sla", action: "manage", description: "Manage CRM SLA policies" },
];

const SHARED_PERMISSIONS: Permission[] = [
  { name: "accounting:view", resource: "accounting", action: "view", description: "View chart of accounts, journal entries, and accounting reports" },
  { name: "accounting:manage", resource: "accounting", action: "manage", description: "Create and edit accounts and post manual journal entries" },
  { name: "accounting:report", resource: "accounting", action: "report", description: "Generate Trial Balance, P&L, and other accounting reports" },
  { name: "projects:view", resource: "projects", action: "view", description: "View projects" },
  { name: "projects:create", resource: "projects", action: "create", description: "Create projects" },
  { name: "projects:update", resource: "projects", action: "update", description: "Update projects" },
  { name: "projects:delete", resource: "projects", action: "delete", description: "Delete projects" },
  { name: "projects:manage", resource: "projects", action: "manage", description: "Full project management (owner/admin: see and edit all projects)", scopable: true },
  { name: "projects:tickets:view", resource: "projects:tickets", action: "view", description: "View tickets" },
  { name: "projects:tickets:create", resource: "projects:tickets", action: "create", description: "Create tickets" },
  { name: "projects:tickets:update", resource: "projects:tickets", action: "update", description: "Update tickets" },
  { name: "projects:tickets:delete", resource: "projects:tickets", action: "delete", description: "Delete tickets" },
  { name: "projects:tickets:assign", resource: "projects:tickets", action: "assign", description: "Assign tickets" },
  { name: "projects:sprints:view", resource: "projects:sprints", action: "view", description: "View sprints" },
  { name: "projects:sprints:manage", resource: "projects:sprints", action: "manage", description: "Manage sprints" },
  { name: "projects:timesheets:view", resource: "projects:timesheets", action: "view", description: "View timesheets" },
  { name: "projects:timesheets:create", resource: "projects:timesheets", action: "create", description: "Create timesheet entries" },
  { name: "projects:timesheets:manage", resource: "projects:timesheets", action: "manage", description: "Manage all timesheets (owner/admin: see and edit everyone's)", scopable: true },
  { name: "projects:goals:view", resource: "projects:goals", action: "view", description: "View goals and OKRs" },
  { name: "projects:goals:manage", resource: "projects:goals", action: "manage", description: "Create, update, and check in on goals and OKRs" },
  { name: "projects:roadmap:view", resource: "projects:roadmap", action: "view", description: "View the product roadmap, feedback, and changelog" },
  { name: "projects:roadmap:manage", resource: "projects:roadmap", action: "manage", description: "Manage roadmap items, feedback, and changelog entries" },
  { name: "reports:view", resource: "reports", action: "view", description: "View reports" },
  { name: "reports:create", resource: "reports", action: "create", description: "Create reports" },
  { name: "reports:export", resource: "reports", action: "export", description: "Export reports" },
  { name: "reports:generate", resource: "reports", action: "generate", description: "Generate reports" },
  { name: "reports:schedule", resource: "reports", action: "schedule", description: "Schedule reports" },
  { name: "settings:view", resource: "settings", action: "view", description: "View settings" },
  { name: "settings:manage", resource: "settings", action: "manage", description: "Manage settings" },
  { name: "settings:rbac:manage", resource: "settings:rbac", action: "manage", description: "Manage RBAC permissions" },
  { name: "settings:automations:view", resource: "settings:automations", action: "view", description: "View automation rules and run history" },
  { name: "settings:automations:manage", resource: "settings:automations", action: "manage", description: "Create, edit, and run automation rules" },
  { name: "settings:custom-fields:manage", resource: "settings:custom-fields", action: "manage", description: "Manage custom fields" },
  { name: "settings:email-templates:manage", resource: "settings:email-templates", action: "manage", description: "Manage email templates" },
  { name: "settings:onboarding:manage", resource: "settings:onboarding", action: "manage", description: "Manage onboarding settings" },
  { name: "settings:webhooks:manage", resource: "settings:webhooks", action: "manage", description: "Manage webhooks" },
  { name: "audit-log:read", resource: "audit-log", action: "read", description: "View the audit log" },
  { name: "dashboard:sales:view", resource: "dashboard:sales", action: "view", description: "View Sales dashboard" },
  { name: "dashboard:customer-executive:view", resource: "dashboard:customer-executive", action: "view", description: "View Customer Executive dashboard" },
  { name: "dashboard:support:view", resource: "dashboard:support", action: "view", description: "View Support CRM dashboard" },
  { name: "self:attendance", resource: "self", action: "attendance", description: "Check in/out own attendance" },
  { name: "self:leaves", resource: "self", action: "leaves", description: "Submit and view own leave requests" },
  { name: "self:expenses", resource: "self", action: "expenses", description: "Submit and view own expense claims" },
  { name: "self:payslips", resource: "self", action: "payslips", description: "View own payslips" },
  { name: "dm:leads:create", resource: "dm:leads", action: "create", description: "Capture DM leads" },
  { name: "dm:leads:read", resource: "dm:leads", action: "read", description: "View DM leads" },
  { name: "dm:leads:update", resource: "dm:leads", action: "update", description: "Update DM leads" },
  { name: "dm:leads:delete", resource: "dm:leads", action: "delete", description: "Delete DM leads" },
  { name: "dm:leads:export", resource: "dm:leads", action: "export", description: "Export DM leads" },
  { name: "dm:campaigns:create", resource: "dm:campaigns", action: "create", description: "Create campaigns" },
  { name: "dm:campaigns:read", resource: "dm:campaigns", action: "read", description: "View campaigns" },
  { name: "dm:campaigns:update", resource: "dm:campaigns", action: "update", description: "Update campaigns" },
  { name: "dm:social:read", resource: "dm:social", action: "read", description: "View social stats" },
  { name: "dm:social:create", resource: "dm:social", action: "create", description: "Enter social stats" },
  { name: "branch:create", resource: "branch", action: "create", description: "Create branches" },
  { name: "branch:read", resource: "branch", action: "read", description: "View branches" },
  { name: "branch:update", resource: "branch", action: "update", description: "Update branches" },
  { name: "branch:manage_targets", resource: "branch", action: "manage_targets", description: "Manage branch targets" },
  { name: "chat:submit_lead", resource: "chat", action: "submit_lead", description: "Submit leads via chat" },
];

const SUPPORT_PERMISSIONS: Permission[] = [
  { name: "support:kb:view", resource: "support:kb", action: "view", description: "View and browse knowledge base articles" },
  { name: "support:kb:manage", resource: "support:kb", action: "manage", description: "Create, edit, and publish knowledge base articles and categories" },
  { name: "support:macros:view", resource: "support:macros", action: "view", description: "View canned responses and ticket routing rules" },
  { name: "support:macros:manage", resource: "support:macros", action: "manage", description: "Create and edit canned responses and ticket routing rules" },
];

const ACCOUNTING_PERMISSIONS: Permission[] = [
  { name: "accounting:read", resource: "accounting", action: "read", description: "Read accounting data" },
  { name: "accounting:create", resource: "accounting", action: "create", description: "Create accounting records" },
  { name: "accounting:accounts:read", resource: "accounting:accounts", action: "read", description: "View chart of accounts" },
  { name: "accounting:accounts:create", resource: "accounting:accounts", action: "create", description: "Create accounts" },
  { name: "accounting:accounts:update", resource: "accounting:accounts", action: "update", description: "Update accounts" },
  { name: "accounting:journal:read", resource: "accounting:journal", action: "read", description: "View journal entries" },
  { name: "accounting:journal:manage", resource: "accounting:journal", action: "manage", description: "Post and manage journal entries" },
  { name: "accounting:reports:read", resource: "accounting:reports", action: "read", description: "View accounting reports" },
];

const INVENTORY_PERMISSIONS: Permission[] = [
  { name: "inventory:products:read", resource: "inventory:products", action: "read", description: "View products" },
  { name: "inventory:products:create", resource: "inventory:products", action: "create", description: "Create products" },
  { name: "inventory:products:update", resource: "inventory:products", action: "update", description: "Update products" },
  { name: "inventory:products:delete", resource: "inventory:products", action: "delete", description: "Delete products" },
  { name: "inventory:stock:read", resource: "inventory:stock", action: "read", description: "View stock levels" },
  { name: "inventory:stock:adjust", resource: "inventory:stock", action: "adjust", description: "Adjust stock levels" },
  { name: "inventory:stock:transfer", resource: "inventory:stock", action: "transfer", description: "Transfer stock between warehouses" },
  { name: "inventory:warehouses:read", resource: "inventory:warehouses", action: "read", description: "View warehouses" },
  { name: "inventory:warehouses:manage", resource: "inventory:warehouses", action: "manage", description: "Manage warehouses" },
  { name: "inventory:vendors:read", resource: "inventory:vendors", action: "read", description: "View vendors" },
  { name: "inventory:vendors:manage", resource: "inventory:vendors", action: "manage", description: "Manage vendors" },
  { name: "inventory:purchase-orders:read", resource: "inventory:purchase-orders", action: "read", description: "View purchase orders" },
  { name: "inventory:purchase-orders:create", resource: "inventory:purchase-orders", action: "create", description: "Create purchase orders" },
  { name: "inventory:purchase-orders:approve", resource: "inventory:purchase-orders", action: "approve", description: "Approve purchase orders" },
  { name: "inventory:purchase-orders:receive", resource: "inventory:purchase-orders", action: "receive", description: "Receive purchase orders" },
  { name: "inventory:sales-orders:read", resource: "inventory:sales-orders", action: "read", description: "View sales orders" },
  { name: "inventory:sales-orders:create", resource: "inventory:sales-orders", action: "create", description: "Create sales orders" },
  { name: "inventory:sales-orders:confirm", resource: "inventory:sales-orders", action: "confirm", description: "Confirm sales orders" },
  { name: "inventory:sales-orders:ship", resource: "inventory:sales-orders", action: "ship", description: "Ship sales orders" },
  { name: "inventory:sales-orders:invoice", resource: "inventory:sales-orders", action: "invoice", description: "Invoice sales orders" },
  { name: "inventory:reports:read", resource: "inventory:reports", action: "read", description: "View inventory reports" },
];

const KB_PERMISSIONS: Permission[] = [
  { name: "kb:articles:view", resource: "kb:articles", action: "view", description: "View knowledge base articles" },
  { name: "kb:articles:create", resource: "kb:articles", action: "create", description: "Create knowledge base articles" },
  { name: "kb:articles:update", resource: "kb:articles", action: "update", description: "Update knowledge base articles" },
  { name: "kb:articles:delete", resource: "kb:articles", action: "delete", description: "Delete knowledge base articles" },
  { name: "kb:articles:manage", resource: "kb:articles", action: "manage", description: "Manage knowledge base articles" },
  { name: "kb:categories:manage", resource: "kb:categories", action: "manage", description: "Manage knowledge base categories" },
  { name: "kb:spaces:view", resource: "kb:spaces", action: "view", description: "View knowledge base spaces" },
  { name: "kb:spaces:manage", resource: "kb:spaces", action: "manage", description: "Manage knowledge base spaces" },
  { name: "kb:analytics:view", resource: "kb:analytics", action: "view", description: "View knowledge base analytics" },
  { name: "kb:ai:generate", resource: "kb:ai", action: "generate", description: "Generate AI answers from the knowledge base" },
];

const BLOG_PERMISSIONS: Permission[] = [
  { name: "blog:posts:manage", resource: "blog:posts", action: "manage", description: "Manage blog posts" },
  { name: "blog:categories:manage", resource: "blog:categories", action: "manage", description: "Manage blog categories" },
];

const SALES_PERMISSIONS: Permission[] = [
  { name: "sales:view", resource: "sales", action: "view", description: "View sales module" },
  { name: "sales:manage", resource: "sales", action: "manage", description: "Manage sales module" },
];

export const PERMISSIONS: Permission[] = [
  ...HR_PERMISSIONS,
  ...CRM_PERMISSIONS,
  ...ACCOUNTING_PERMISSIONS,
  ...INVENTORY_PERMISSIONS,
  ...KB_PERMISSIONS,
  ...BLOG_PERMISSIONS,
  ...SALES_PERMISSIONS,
  ...SHARED_PERMISSIONS,
  ...SUPPORT_PERMISSIONS,
];

const SCOPABLE_PERMISSIONS = new Set(PERMISSIONS.filter((p) => p.scopable).map((p) => p.name));

export function isScopable(key: string): boolean {
  return SCOPABLE_PERMISSIONS.has(key);
}

const EMPLOYEE_SELF_SERVICE = [
  "self:attendance",
  "self:leaves",
  "self:expenses",
  "self:payslips",
  "hr:leaves:create",
  "hr:expenses:create",
];

const ALL_PERMISSIONS = PERMISSIONS.map((p) => p.name);

export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  OWNER: ALL_PERMISSIONS,

  CEO: ALL_PERMISSIONS,

  HR: [
    ...EMPLOYEE_SELF_SERVICE,
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:employees:delete",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:payroll:generate",
    "hr:payroll:approve",
    "hr:salary:view",
    "hr:salary:manage",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:assets:view",
    "hr:assets:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "accounting:view",
    "accounting:report",
    "accounting:read",
    "accounting:accounts:read",
    "accounting:journal:read",
    "accounting:reports:read",
    "reports:view",
    "reports:create",
    "reports:export",
    "hr:employees:read",
    "hr:employees:manage",
    "hr:leaves:read",
    "hr:leaves:manage",
    "hr:expenses:read",
    "hr:expenses:manage",
    "hr:payrolls:read",
    "hr:payrolls:manage",
    "hr:bonuses:manage",
    "hr:career-ladders:manage",
    "hr:compliance:manage",
    "hr:email-templates:manage",
    "hr:exit:manage",
    "hr:feedback:manage",
    "hr:handbook:manage",
    "hr:integrations:manage",
    "hr:onboarding:manage",
    "hr:alumni:read",
    "hr:analytics:read",
    "hr:headcount:read",
    "settings:onboarding:manage",
    "settings:email-templates:manage",
    "reports:generate",
    "reports:schedule",
    "audit-log:read",
  ],

  SALES: [
    ...EMPLOYEE_SELF_SERVICE,
    "crm:leads:view",
    "crm:leads:create",
    "crm:leads:update",
    "crm:leads:assign",
    "crm:deals:read",
    "crm:deals:create",
    "crm:clients:read",
    "crm:clients:update",
    "crm:targets:view",
    "crm:incentives:read",
    "crm:reports:view",
    "sales:view",
    "dashboard:sales:view",
    "chat:submit_lead",
    "dm:leads:create",
    "dm:leads:read",
    "dm:leads:update",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  CUSTOMER_SUPPORT: [
    ...EMPLOYEE_SELF_SERVICE,
    "dashboard:support:view",
    "dashboard:customer-executive:view",
    "support:kb:view",
    "support:kb:manage",
    "support:macros:view",
    "support:macros:manage",
    "kb:articles:view",
    "kb:articles:create",
    "kb:articles:update",
    "kb:articles:delete",
    "kb:articles:manage",
    "kb:categories:manage",
    "kb:spaces:view",
    "kb:spaces:manage",
    "kb:analytics:view",
    "kb:ai:generate",
    "projects:roadmap:view",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  ENGINEERING: [
    ...EMPLOYEE_SELF_SERVICE,
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:sprints:view",
    "projects:timesheets:view",
    "projects:timesheets:create",
    "projects:goals:view",
    "projects:roadmap:view",
    "kb:articles:view",
    "kb:spaces:view",
  ],

  DESIGN: [
    ...EMPLOYEE_SELF_SERVICE,
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  VIDEO_EDITOR: [
    ...EMPLOYEE_SELF_SERVICE,
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  DIGITAL_MARKETING: [
    ...EMPLOYEE_SELF_SERVICE,
    "blog:posts:manage",
    "blog:categories:manage",
    "dm:leads:create",
    "dm:leads:read",
    "dm:leads:update",
    "dm:leads:delete",
    "dm:leads:export",
    "dm:campaigns:create",
    "dm:campaigns:read",
    "dm:campaigns:update",
    "dm:social:read",
    "dm:social:create",
    "kb:articles:view",
    "kb:spaces:view",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  BLOG_EDITOR: [
    ...EMPLOYEE_SELF_SERVICE,
    "blog:posts:manage",
    "blog:categories:manage",
  ],

  BRANCH_MANAGER: [
    ...EMPLOYEE_SELF_SERVICE,
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "crm:leads:view",
    "crm:leads:create",
    "crm:leads:update",
    "crm:leads:assign",
    "crm:deals:read",
    "crm:deals:create",
    "crm:deals:delete",
    "crm:quotes:delete",
    "crm:clients:read",
    "crm:clients:update",
    "crm:clients:manage",
    "crm:assignment-rules:manage",
    "crm:email-templates:manage",
    "crm:scoring-rules:manage",
    "crm:sla:manage",
    "sales:view",
    "sales:manage",
    "crm:targets:view",
    "crm:targets:manage",
    "crm:reports:view",
    "crm:reports:export",
    "crm:incentives:read",
    "crm:incentives:approve",
    "reports:generate",
    "reports:schedule",
    "projects:view",
    "projects:tickets:view",
    "reports:view",
    "settings:view",
    "dashboard:sales:view",
    "dashboard:customer-executive:view",
    "branch:create",
    "branch:update",
    "branch:manage_targets",
    "settings:automations:manage",
    "settings:custom-fields:manage",
    "settings:webhooks:manage",
    "dashboard:support:view",
    "support:kb:view",
    "support:macros:view",
  ],

  BRANCH_HR: [
    ...EMPLOYEE_SELF_SERVICE,
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:payroll:generate",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:assets:view",
    "hr:assets:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "hr:employees:read",
    "hr:employees:manage",
    "hr:leaves:read",
    "hr:leaves:manage",
    "hr:expenses:read",
    "hr:expenses:manage",
    "hr:payrolls:read",
    "hr:onboarding:manage",
    "hr:exit:manage",
    "hr:handbook:manage",
    "hr:analytics:read",
    "hr:headcount:read",
    "hr:salary:view",
    "hr:salary:manage",
    "hr:bonuses:manage",
    "hr:career-ladders:manage",
    "hr:compliance:manage",
    "hr:email-templates:manage",
    "hr:feedback:manage",
    "hr:integrations:manage",
    "hr:alumni:read",
    "reports:generate",
    "reports:schedule",
    "projects:view",
    "projects:tickets:view",
    "reports:view",
    "settings:email-templates:manage",
    "settings:onboarding:manage",
  ],

  INVENTORY_MANAGER: [
    ...EMPLOYEE_SELF_SERVICE,
    "inventory:products:read",
    "inventory:products:create",
    "inventory:products:update",
    "inventory:products:delete",
    "inventory:stock:read",
    "inventory:stock:adjust",
    "inventory:stock:transfer",
    "inventory:warehouses:read",
    "inventory:warehouses:manage",
    "inventory:vendors:read",
    "inventory:vendors:manage",
    "inventory:purchase-orders:read",
    "inventory:purchase-orders:create",
    "inventory:purchase-orders:approve",
    "inventory:purchase-orders:receive",
    "inventory:sales-orders:read",
    "inventory:sales-orders:create",
    "inventory:sales-orders:confirm",
    "inventory:sales-orders:ship",
    "inventory:sales-orders:invoice",
    "inventory:reports:read",
    "reports:view",
  ],

  ACCOUNTANT: [
    ...EMPLOYEE_SELF_SERVICE,
    "accounting:view",
    "accounting:manage",
    "accounting:report",
    "accounting:read",
    "accounting:create",
    "accounting:accounts:read",
    "accounting:accounts:create",
    "accounting:accounts:update",
    "accounting:journal:read",
    "accounting:journal:manage",
    "accounting:reports:read",
    "reports:view",
    "reports:export",
    "reports:generate",
    "reports:schedule",
    "audit-log:read",
  ],
};
