export interface Permission {
  name: string;
  resource: string;
  action: string;
  description: string;
  scopable?: boolean;
}

const HR_PERMISSIONS: Permission[] = [
  { name: "hr:employees:view", resource: "hr:employees", action: "view", description: "View employees list" },
  { name: "hr:employees:create", resource: "hr:employees", action: "create", description: "Create new employees" },
  { name: "hr:employees:update", resource: "hr:employees", action: "update", description: "Update employee information" },
  { name: "hr:employees:delete", resource: "hr:employees", action: "delete", description: "Delete employees" },
  { name: "hr:attendance:view", resource: "hr:attendance", action: "view", description: "View attendance records" },
  { name: "hr:attendance:manage", resource: "hr:attendance", action: "manage", description: "Manage attendance records", scopable: true },
  { name: "hr:leaves:view", resource: "hr:leaves", action: "view", description: "View leave requests" },
  { name: "hr:leaves:create", resource: "hr:leaves", action: "create", description: "Create leave requests" },
  { name: "hr:leaves:approve", resource: "hr:leaves", action: "approve", description: "Approve/reject leave requests", scopable: true },
  { name: "hr:payroll:view", resource: "hr:payroll", action: "view", description: "View payroll information", scopable: true },
  { name: "hr:payroll:generate", resource: "hr:payroll", action: "generate", description: "Generate payroll" },
  { name: "hr:payroll:approve", resource: "hr:payroll", action: "approve", description: "Approve payroll" },
  { name: "hr:payroll:read", resource: "hr:payroll", action: "read", description: "Read payroll data for reporting and analytics" },
  { name: "hr:salary:view", resource: "hr:salary", action: "view", description: "View salary structures" },
  { name: "hr:salary:manage", resource: "hr:salary", action: "manage", description: "Manage salary structures" },
  { name: "hr:expenses:view", resource: "hr:expenses", action: "view", description: "View expenses" },
  { name: "hr:expenses:create", resource: "hr:expenses", action: "create", description: "Create expense requests" },
  { name: "hr:expenses:approve", resource: "hr:expenses", action: "approve", description: "Approve expense requests", scopable: true },
  { name: "hr:assets:view", resource: "hr:assets", action: "view", description: "View assets" },
  { name: "hr:assets:manage", resource: "hr:assets", action: "manage", description: "Manage assets" },
  { name: "hr:documents:view", resource: "hr:documents", action: "view", description: "View documents" },
  { name: "hr:documents:manage", resource: "hr:documents", action: "manage", description: "Manage documents" },
  { name: "hr:performance:view", resource: "hr:performance", action: "view", description: "View performance reviews" },
  { name: "hr:performance:manage", resource: "hr:performance", action: "manage", description: "Manage performance reviews" },
  { name: "hr:goals:view", resource: "hr:goals", action: "view", description: "View goals" },
  { name: "hr:goals:manage", resource: "hr:goals", action: "manage", description: "Manage goals" },
  { name: "hr:employees:read", resource: "hr:employees", action: "read", description: "Read employee records", scopable: true },
  { name: "hr:employees:manage", resource: "hr:employees", action: "manage", description: "Manage employees", scopable: true },
  { name: "hr:leaves:read", resource: "hr:leaves", action: "read", description: "Read leave requests" },
  { name: "hr:leaves:manage", resource: "hr:leaves", action: "manage", description: "Manage leave requests" },
  { name: "hr:expenses:read", resource: "hr:expenses", action: "read", description: "Read expense requests" },
  { name: "hr:expenses:manage", resource: "hr:expenses", action: "manage", description: "Manage expense requests" },
  { name: "hr:payrolls:read", resource: "hr:payrolls", action: "read", description: "Read payroll runs" },
  { name: "hr:payrolls:manage", resource: "hr:payrolls", action: "manage", description: "Manage payroll runs" },
  { name: "hr:bonuses:manage", resource: "hr:bonuses", action: "manage", description: "Manage bonuses" },
  { name: "hr:career-ladders:manage", resource: "hr:career-ladders", action: "manage", description: "Manage career ladders" },
  { name: "hr:compliance:manage", resource: "hr:compliance", action: "manage", description: "Manage compliance records" },
  { name: "hr:email-templates:manage", resource: "hr:email-templates", action: "manage", description: "Manage HR email templates" },
  { name: "hr:exit:manage", resource: "hr:exit", action: "manage", description: "Manage employee exits and offboarding" },
  { name: "hr:feedback:manage", resource: "hr:feedback", action: "manage", description: "Manage feedback" },
  { name: "hr:handbook:manage", resource: "hr:handbook", action: "manage", description: "Manage the employee handbook" },
  { name: "hr:integrations:manage", resource: "hr:integrations", action: "manage", description: "Manage HR integrations" },
  { name: "hr:onboarding:manage", resource: "hr:onboarding", action: "manage", description: "Manage onboarding" },
  { name: "hr:alumni:read", resource: "hr:alumni", action: "read", description: "Read alumni records" },
  { name: "hr:alumni:write", resource: "hr:alumni", action: "write", description: "Write alumni records" },
  { name: "hr:analytics:read", resource: "hr:analytics", action: "read", description: "Read HR analytics" },
  { name: "hr:headcount:read", resource: "hr:headcount", action: "read", description: "Read headcount planning" },
  { name: "hr:shifts:view", resource: "hr:shifts", action: "view", description: "View shift templates and assignments" },
  { name: "hr:shifts:manage", resource: "hr:shifts", action: "manage", description: "Manage shifts, rosters, and swap requests" },
  { name: "hr:geofencing:manage", resource: "hr:geofencing", action: "manage", description: "Manage geofence locations" },
  { name: "hr:biometric:manage", resource: "hr:biometric", action: "manage", description: "Manage biometric devices" },
  { name: "hr:feedback:view", resource: "hr:feedback", action: "view", description: "View 360 feedback cycles" },
  { name: "hr:kpis:view", resource: "hr:kpis", action: "view", description: "View KPIs and competency frameworks" },
  { name: "hr:kpis:manage", resource: "hr:kpis", action: "manage", description: "Manage KPIs and competency frameworks" },
  { name: "hr:learning:view", resource: "hr:learning", action: "view", description: "View courses and training programs" },
  { name: "hr:learning:manage", resource: "hr:learning", action: "manage", description: "Manage courses, training, and career paths" },
  { name: "hr:announcements:view", resource: "hr:announcements", action: "view", description: "View announcements" },
  { name: "hr:announcements:manage", resource: "hr:announcements", action: "manage", description: "Create and manage announcements" },
  { name: "hr:signatures:view", resource: "hr:signatures", action: "view", description: "View signature requests" },
  { name: "hr:signatures:manage", resource: "hr:signatures", action: "manage", description: "Send and manage signature requests" },
  { name: "hr:tax:view", resource: "hr:tax", action: "view", description: "View tax declarations" },
  { name: "hr:tax:manage", resource: "hr:tax", action: "manage", description: "Review and approve tax declarations" },
  { name: "hr:travel:view", resource: "hr:travel", action: "view", description: "View travel requests" },
  { name: "hr:travel:manage", resource: "hr:travel", action: "manage", description: "Approve travel requests" },
  { name: "hr:requisitions:view", resource: "hr:requisitions", action: "view", description: "View job requisitions" },
  { name: "hr:requisitions:manage", resource: "hr:requisitions", action: "manage", description: "Manage and approve job requisitions" },
];

const CRM_PERMISSIONS: Permission[] = [
  { name: "crm:leads:view", resource: "crm:leads", action: "view", description: "View CRM leads", scopable: true },
  { name: "crm:leads:create", resource: "crm:leads", action: "create", description: "Create CRM leads" },
  { name: "crm:leads:update", resource: "crm:leads", action: "update", description: "Update CRM leads", scopable: true },
  { name: "crm:leads:assign", resource: "crm:leads", action: "assign", description: "Assign CRM leads" },
  { name: "crm:leads:delete", resource: "crm:leads", action: "delete", description: "Delete CRM leads", scopable: true },
  { name: "crm:targets:view", resource: "crm:targets", action: "view", description: "View targets" },
  { name: "crm:targets:manage", resource: "crm:targets", action: "manage", description: "Manage targets" },
  { name: "crm:reports:view", resource: "crm:reports", action: "view", description: "View CRM reports" },
  { name: "crm:reports:export", resource: "crm:reports", action: "export", description: "Export CRM reports" },
  { name: "crm:clients:read", resource: "crm:clients", action: "read", description: "View client accounts", scopable: true },
  { name: "crm:clients:update", resource: "crm:clients", action: "update", description: "Update client accounts" },
  { name: "crm:incentives:read", resource: "crm:incentives", action: "read", description: "View incentives" },
  { name: "crm:incentives:approve", resource: "crm:incentives", action: "approve", description: "Approve incentives" },
  { name: "crm:incentives:config", resource: "crm:incentives", action: "config", description: "Configure incentive rates" },
  { name: "crm:deals:read", resource: "crm:deals", action: "read", description: "View CRM deals", scopable: true },
  { name: "crm:deals:create", resource: "crm:deals", action: "create", description: "Create CRM deals" },
  { name: "crm:deals:update", resource: "crm:deals", action: "update", description: "Update CRM deals" },
  { name: "crm:deals:delete", resource: "crm:deals", action: "delete", description: "Delete CRM deals" },
  { name: "crm:contacts:view", resource: "crm:contacts", action: "view", description: "View CRM contacts", scopable: true },
  { name: "crm:contacts:manage", resource: "crm:contacts", action: "manage", description: "Manage CRM contacts" },
  { name: "crm:quotes:read", resource: "crm:quotes", action: "read", description: "View CRM quotes", scopable: true },
  { name: "crm:quotes:create", resource: "crm:quotes", action: "create", description: "Create CRM quotes" },
  { name: "crm:quotes:update", resource: "crm:quotes", action: "update", description: "Update CRM quotes" },
  { name: "crm:quotes:delete", resource: "crm:quotes", action: "delete", description: "Delete CRM quotes" },
  { name: "crm:clients:manage", resource: "crm:clients", action: "manage", description: "Manage client accounts" },
  { name: "crm:assignment-rules:manage", resource: "crm:assignment-rules", action: "manage", description: "Manage lead assignment rules" },
  { name: "crm:email-templates:manage", resource: "crm:email-templates", action: "manage", description: "Manage CRM email templates" },
  { name: "crm:scoring-rules:manage", resource: "crm:scoring-rules", action: "manage", description: "Manage lead scoring rules" },
  { name: "crm:sla:manage", resource: "crm:sla", action: "manage", description: "Manage CRM SLA policies" },
  { name: "crm:organizations:view", resource: "crm:organizations", action: "view", description: "View CRM organizations" },
  { name: "crm:organizations:manage", resource: "crm:organizations", action: "manage", description: "Manage CRM organizations" },
  { name: "crm:web-forms:manage", resource: "crm:web-forms", action: "manage", description: "Manage CRM web forms" },
  { name: "crm:territories:manage", resource: "crm:territories", action: "manage", description: "Manage CRM territories" },
  { name: "crm:automations:manage", resource: "crm:automations", action: "manage", description: "Manage CRM automation rules" },
  { name: "crm:products:manage", resource: "crm:products", action: "manage", description: "Manage the CRM product catalog" },
];

const SHARED_PERMISSIONS: Permission[] = [
  { name: "tasks:read", resource: "tasks", action: "read", description: "View tasks, sequences, analytics, and queue" },
  { name: "tasks:write", resource: "tasks", action: "write", description: "Create, update, delete, and complete tasks and sequences" },
  { name: "accounting:view", resource: "accounting", action: "view", description: "View chart of accounts, journal entries, and accounting reports" },
  { name: "accounting:manage", resource: "accounting", action: "manage", description: "Create and edit accounts and post manual journal entries" },
  { name: "accounting:report", resource: "accounting", action: "report", description: "Generate Trial Balance, P&L, and other accounting reports" },
  { name: "projects:view", resource: "projects", action: "view", description: "View projects" },
  { name: "projects:create", resource: "projects", action: "create", description: "Create projects" },
  { name: "projects:update", resource: "projects", action: "update", description: "Update projects" },
  { name: "projects:delete", resource: "projects", action: "delete", description: "Delete projects" },
  { name: "projects:manage", resource: "projects", action: "manage", description: "Full project management (owner/admin: see and edit all projects)", scopable: true },
  { name: "projects:tickets:view", resource: "projects:tickets", action: "view", description: "View tickets" },
  { name: "projects:tickets:create", resource: "projects:tickets", action: "create", description: "Create tickets" },
  { name: "projects:tickets:update", resource: "projects:tickets", action: "update", description: "Update tickets" },
  { name: "projects:tickets:delete", resource: "projects:tickets", action: "delete", description: "Delete tickets" },
  { name: "projects:tickets:assign", resource: "projects:tickets", action: "assign", description: "Assign tickets" },
  { name: "projects:sprints:view", resource: "projects:sprints", action: "view", description: "View sprints" },
  { name: "projects:sprints:manage", resource: "projects:sprints", action: "manage", description: "Manage sprints" },
  { name: "projects:timesheets:view", resource: "projects:timesheets", action: "view", description: "View timesheets" },
  { name: "projects:timesheets:create", resource: "projects:timesheets", action: "create", description: "Create timesheet entries" },
  { name: "projects:timesheets:manage", resource: "projects:timesheets", action: "manage", description: "Manage all timesheets (owner/admin: see and edit everyone's)", scopable: true },
  { name: "projects:goals:view", resource: "projects:goals", action: "view", description: "View goals and OKRs" },
  { name: "projects:goals:manage", resource: "projects:goals", action: "manage", description: "Create, update, and check in on goals and OKRs" },
  { name: "projects:roadmap:view", resource: "projects:roadmap", action: "view", description: "View the product roadmap, feedback, and changelog" },
  { name: "projects:roadmap:manage", resource: "projects:roadmap", action: "manage", description: "Manage roadmap items, feedback, and changelog entries" },
  { name: "projects:whiteboards:manage", resource: "projects:whiteboards", action: "manage", description: "Create, edit, share and delete project whiteboards" },
  { name: "projects:workspace:manage", resource: "projects:workspace", action: "manage", description: "Manage project milestones, views, pages and intake requests" },
  { name: "reports:view", resource: "reports", action: "view", description: "View reports" },
  { name: "reports:create", resource: "reports", action: "create", description: "Create reports" },
  { name: "reports:export", resource: "reports", action: "export", description: "Export reports" },
  { name: "reports:generate", resource: "reports", action: "generate", description: "Generate reports" },
  { name: "reports:schedule", resource: "reports", action: "schedule", description: "Schedule reports" },
  { name: "settings:view", resource: "settings", action: "view", description: "View settings" },
  { name: "settings:manage", resource: "settings", action: "manage", description: "Manage settings" },
  { name: "settings:mfa", resource: "settings", action: "mfa", description: "Manage MFA settings for the organization" },
  { name: "settings:rbac:manage", resource: "settings:rbac", action: "manage", description: "Manage RBAC permissions" },
  { name: "settings:automations:view", resource: "settings:automations", action: "view", description: "View automation rules and run history" },
  { name: "settings:automations:manage", resource: "settings:automations", action: "manage", description: "Create, edit, and run automation rules" },
  { name: "settings:custom-fields:manage", resource: "settings:custom-fields", action: "manage", description: "Manage custom fields" },
  { name: "settings:email-templates:manage", resource: "settings:email-templates", action: "manage", description: "Manage email templates" },
  { name: "settings:onboarding:manage", resource: "settings:onboarding", action: "manage", description: "Manage onboarding settings" },
  { name: "settings:webhooks:manage", resource: "settings:webhooks", action: "manage", description: "Manage webhooks" },
  { name: "settings:organization:manage", resource: "settings:organization", action: "manage", description: "Manage workspace onboarding and organization setup", scopable: false },
  { name: "audit-log:read", resource: "audit-log", action: "read", description: "View the audit log" },
  { name: "calendar:read", resource: "calendar", action: "read", description: "View calendar events" },
  { name: "calendar:write", resource: "calendar", action: "write", description: "Create and manage calendar events" },
  { name: "dashboard:sales:view", resource: "dashboard:sales", action: "view", description: "View Sales dashboard" },
  { name: "dashboard:customer-executive:view", resource: "dashboard:customer-executive", action: "view", description: "View Customer Executive dashboard" },
  { name: "dashboard:support:view", resource: "dashboard:support", action: "view", description: "View Support CRM dashboard" },
  { name: "self:attendance", resource: "self", action: "attendance", description: "Check in/out own attendance" },
  { name: "self:leaves", resource: "self", action: "leaves", description: "Submit and view own leave requests" },
  { name: "self:expenses", resource: "self", action: "expenses", description: "Submit and view own expense claims" },
  { name: "self:payslips", resource: "self", action: "payslips", description: "View own payslips" },
  { name: "branch:create", resource: "branch", action: "create", description: "Create branches" },
  { name: "branch:update", resource: "branch", action: "update", description: "Update branches" },
  { name: "branch:manage_targets", resource: "branch", action: "manage_targets", description: "Manage branch targets" },
];

const SUPPORT_PERMISSIONS: Permission[] = [
  { name: "support:kb:view", resource: "support:kb", action: "view", description: "View and browse knowledge base articles" },
  { name: "support:kb:manage", resource: "support:kb", action: "manage", description: "Create, edit, and publish knowledge base articles and categories" },
  { name: "support:macros:view", resource: "support:macros", action: "view", description: "View canned responses and ticket routing rules" },
  { name: "support:macros:manage", resource: "support:macros", action: "manage", description: "Create and edit canned responses and ticket routing rules" },
  { name: "support:tickets:manage", resource: "support:tickets", action: "manage", description: "Manage support tickets", scopable: true },
];

const ACCOUNTING_PERMISSIONS: Permission[] = [
  { name: "accounting:read", resource: "accounting", action: "read", description: "Read accounting data" },
  { name: "accounting:create", resource: "accounting", action: "create", description: "Create accounting records" },
  { name: "accounting:accounts:read", resource: "accounting:accounts", action: "read", description: "View chart of accounts" },
  { name: "accounting:accounts:create", resource: "accounting:accounts", action: "create", description: "Create accounts" },
  { name: "accounting:accounts:update", resource: "accounting:accounts", action: "update", description: "Update accounts" },
  { name: "accounting:journal:read", resource: "accounting:journal", action: "read", description: "View journal entries", scopable: true },
  { name: "accounting:journal:manage", resource: "accounting:journal", action: "manage", description: "Post and manage journal entries" },
  { name: "accounting:reports:read", resource: "accounting:reports", action: "read", description: "View accounting reports" },
];

const INVENTORY_PERMISSIONS: Permission[] = [
  { name: "inventory:products:read", resource: "inventory:products", action: "read", description: "View products", scopable: true },
  { name: "inventory:products:create", resource: "inventory:products", action: "create", description: "Create products" },
  { name: "inventory:products:update", resource: "inventory:products", action: "update", description: "Update products" },
  { name: "inventory:products:delete", resource: "inventory:products", action: "delete", description: "Delete products" },
  { name: "inventory:stock:read", resource: "inventory:stock", action: "read", description: "View stock levels", scopable: true },
  { name: "inventory:stock:adjust", resource: "inventory:stock", action: "adjust", description: "Adjust stock levels" },
  { name: "inventory:stock:transfer", resource: "inventory:stock", action: "transfer", description: "Transfer stock between warehouses" },
  { name: "inventory:warehouses:read", resource: "inventory:warehouses", action: "read", description: "View warehouses" },
  { name: "inventory:warehouses:manage", resource: "inventory:warehouses", action: "manage", description: "Manage warehouses" },
  { name: "inventory:vendors:read", resource: "inventory:vendors", action: "read", description: "View vendors" },
  { name: "inventory:vendors:manage", resource: "inventory:vendors", action: "manage", description: "Manage vendors" },
  { name: "inventory:purchase-orders:read", resource: "inventory:purchase-orders", action: "read", description: "View purchase orders", scopable: true },
  { name: "inventory:purchase-orders:create", resource: "inventory:purchase-orders", action: "create", description: "Create purchase orders" },
  { name: "inventory:purchase-orders:approve", resource: "inventory:purchase-orders", action: "approve", description: "Approve purchase orders" },
  { name: "inventory:purchase-orders:receive", resource: "inventory:purchase-orders", action: "receive", description: "Receive purchase orders" },
  { name: "inventory:sales-orders:read", resource: "inventory:sales-orders", action: "read", description: "View sales orders", scopable: true },
  { name: "inventory:sales-orders:create", resource: "inventory:sales-orders", action: "create", description: "Create sales orders" },
  { name: "inventory:sales-orders:confirm", resource: "inventory:sales-orders", action: "confirm", description: "Confirm sales orders" },
  { name: "inventory:sales-orders:ship", resource: "inventory:sales-orders", action: "ship", description: "Ship sales orders" },
  { name: "inventory:sales-orders:invoice", resource: "inventory:sales-orders", action: "invoice", description: "Invoice sales orders" },
  { name: "inventory:reports:read", resource: "inventory:reports", action: "read", description: "View inventory reports" },
];

const KB_PERMISSIONS: Permission[] = [
  { name: "kb:articles:view", resource: "kb:articles", action: "view", description: "View knowledge base articles", scopable: true },
  { name: "kb:articles:create", resource: "kb:articles", action: "create", description: "Create knowledge base articles" },
  { name: "kb:articles:update", resource: "kb:articles", action: "update", description: "Update knowledge base articles" },
  { name: "kb:articles:delete", resource: "kb:articles", action: "delete", description: "Delete knowledge base articles" },
  { name: "kb:articles:manage", resource: "kb:articles", action: "manage", description: "Manage knowledge base articles" },
  { name: "kb:categories:manage", resource: "kb:categories", action: "manage", description: "Manage knowledge base categories" },
  { name: "kb:spaces:view", resource: "kb:spaces", action: "view", description: "View knowledge base spaces", scopable: true },
  { name: "kb:spaces:manage", resource: "kb:spaces", action: "manage", description: "Manage knowledge base spaces" },
  { name: "kb:analytics:view", resource: "kb:analytics", action: "view", description: "View knowledge base analytics" },
  { name: "kb:ai:generate", resource: "kb:ai", action: "generate", description: "Generate AI answers from the knowledge base" },
  { name: "kb:pages:view", resource: "kb:pages", action: "view", description: "View wiki pages" },
  { name: "kb:pages:create", resource: "kb:pages", action: "create", description: "Create wiki pages" },
  { name: "kb:pages:update", resource: "kb:pages", action: "update", description: "Update wiki pages" },
  { name: "kb:pages:delete", resource: "kb:pages", action: "delete", description: "Delete wiki pages (soft-delete subtree)" },
  { name: "kb:pages:manage", resource: "kb:pages", action: "manage", description: "Lock/unlock pages and manage wiki workspace" },
  { name: "kb:templates:manage", resource: "kb:templates", action: "manage", description: "Create and delete wiki page templates" },
  { name: "kb:reviews:view", resource: "kb:reviews", action: "view", description: "View page review requests" },
  { name: "kb:reviews:manage", resource: "kb:reviews", action: "manage", description: "Create, approve, and reject page review requests" },
  { name: "kb:pages:import", resource: "kb:pages", action: "import", description: "Import pages from markdown, html, or zip" },
  { name: "kb:pages:export", resource: "kb:pages", action: "export", description: "Export pages to markdown or html" },
  { name: "kb:settings:manage", resource: "kb:settings", action: "manage", description: "Manage knowledge base settings" },
];

const BLOG_PERMISSIONS: Permission[] = [
  { name: "blog:posts:manage", resource: "blog:posts", action: "manage", description: "Manage blog posts" },
  { name: "blog:categories:manage", resource: "blog:categories", action: "manage", description: "Manage blog categories" },
];

const SALES_PERMISSIONS: Permission[] = [
  { name: "sales:view", resource: "sales", action: "view", description: "View sales module" },
  { name: "sales:manage", resource: "sales", action: "manage", description: "Manage sales module" },
];

const CHAT_PERMISSIONS: Permission[] = [
  { name: "chat:channels:read", resource: "chat:channels", action: "read", description: "View chat channels" },
  { name: "chat:channels:write", resource: "chat:channels", action: "write", description: "Create and update chat channels" },
  { name: "chat:messages:read", resource: "chat:messages", action: "read", description: "Read chat messages" },
  { name: "chat:messages:write", resource: "chat:messages", action: "write", description: "Send and edit chat messages" },
  { name: "ai:chat:use", resource: "ai:chat", action: "use", description: "Use the AI chat assistant" },
];

const API_TOKEN_PERMISSIONS: Permission[] = [
  { name: "settings:api-tokens:read", resource: "settings:api-tokens", action: "read", description: "View personal API tokens" },
  { name: "settings:api-tokens:write", resource: "settings:api-tokens", action: "write", description: "Create and revoke personal API tokens" },
];

const WORKFLOW_PERMISSIONS: Permission[] = [
  { name: "workflows:workflows:view", resource: "workflows:workflows", action: "view", description: "View workflows" },
  { name: "workflows:workflows:create", resource: "workflows:workflows", action: "create", description: "Create workflows" },
  { name: "workflows:workflows:update", resource: "workflows:workflows", action: "update", description: "Update workflows" },
  { name: "workflows:workflows:delete", resource: "workflows:workflows", action: "delete", description: "Delete workflows" },
  { name: "workflows:workflows:publish", resource: "workflows:workflows", action: "publish", description: "Publish workflows" },
  { name: "workflows:executions:view", resource: "workflows:executions", action: "view", description: "View workflow executions" },
  { name: "workflows:executions:manage", resource: "workflows:executions", action: "manage", description: "Cancel or retry workflow executions" },
  { name: "workflows:approvals:view", resource: "workflows:approvals", action: "view", description: "View workflow approvals" },
  { name: "workflows:approvals:manage", resource: "workflows:approvals", action: "manage", description: "Approve or reject workflow approvals" },
  { name: "workflows:templates:view", resource: "workflows:templates", action: "view", description: "View workflow templates" },
  { name: "workflows:templates:manage", resource: "workflows:templates", action: "manage", description: "Manage workflow templates" },
  { name: "workflows:schedules:manage", resource: "workflows:schedules", action: "manage", description: "Manage workflow schedules" },
  { name: "workflows:analytics:view", resource: "workflows:analytics", action: "view", description: "View workflow analytics" },
  { name: "workflows:secrets:manage", resource: "workflows:secrets", action: "manage", description: "Manage workflow secrets" },
  { name: "workflows:variables:manage", resource: "workflows:variables", action: "manage", description: "Manage workflow variables" },
];

const BILLING_PERMISSIONS: Permission[] = [
  { name: "billing:marketplace:view", resource: "billing:marketplace", action: "view", description: "View marketplace apps", scopable: false },
  { name: "billing:marketplace:install", resource: "billing:marketplace", action: "install", description: "Install and uninstall marketplace apps", scopable: false },
  { name: "billing:ai-credits:view", resource: "billing:ai-credits", action: "view", description: "View AI credits wallet and history", scopable: false },
  { name: "billing:ai-credits:purchase", resource: "billing:ai-credits", action: "purchase", description: "Purchase AI credit packs", scopable: false },
  { name: "billing:analytics:view", resource: "billing:analytics", action: "view", description: "View revenue analytics (platform admin only)", scopable: false },
  { name: "billing:affiliate:manage", resource: "billing:affiliate", action: "manage", description: "Manage affiliate program", scopable: false },
  { name: "billing:profile:update", resource: "billing:profile", action: "update", description: "Update billing profile and GST details", scopable: false },
  { name: "billing:enterprise-quotes:view", resource: "billing:enterprise-quotes", action: "view", description: "View enterprise quotes", scopable: false },
  { name: "billing:enterprise-quotes:create", resource: "billing:enterprise-quotes", action: "create", description: "Create enterprise quotes", scopable: false },
  { name: "billing:enterprise-quotes:approve", resource: "billing:enterprise-quotes", action: "approve", description: "Approve/reject/send enterprise quotes", scopable: false },
];

const ONBOARDING_PERMISSIONS: Permission[] = [
  { name: "onboarding:org:manage", resource: "onboarding:org", action: "manage", description: "Manage org setup wizard/session", scopable: false },
  { name: "onboarding:module-checklists:view", resource: "onboarding:module-checklists", action: "view", description: "View module setup checklists", scopable: false },
  { name: "onboarding:module-checklists:manage", resource: "onboarding:module-checklists", action: "manage", description: "Complete, skip, and dismiss module setup checklist items", scopable: false },
  { name: "onboarding:tours:view", resource: "onboarding:tours", action: "view", description: "View and progress guided tours", scopable: false },
  { name: "onboarding:tours:manage", resource: "onboarding:tours", action: "manage", description: "Manage guided tour definitions", scopable: false },
  { name: "hr:onboarding:plans:manage", resource: "hr:onboarding:plans", action: "manage", description: "Create and launch employee onboarding plans", scopable: false },
  { name: "hr:onboarding:tasks:view", resource: "hr:onboarding:tasks", action: "view", description: "View employee onboarding tasks", scopable: false },
  { name: "hr:onboarding:tasks:complete", resource: "hr:onboarding:tasks", action: "complete", description: "Complete own or assigned employee onboarding tasks", scopable: false },
];

// Payment provider setup permissions (12_Payment_Integration_Setup_Page.md). Not yet
// enforced by any route until the payment-provider module lands, but registered now
// alongside the rest of the onboarding permission surface for a single source of truth.
const PAYMENTS_PERMISSIONS: Permission[] = [
  { name: "payments:providers:view", resource: "payments:providers", action: "view", description: "View configured payment providers and readiness", scopable: false },
  { name: "payments:providers:manage", resource: "payments:providers", action: "manage", description: "Connect, configure, and disable payment providers", scopable: false },
  { name: "payments:credentials:manage", resource: "payments:credentials", action: "manage", description: "Add, rotate, and disconnect provider credentials", scopable: false },
  { name: "payments:webhooks:view", resource: "payments:webhooks", action: "view", description: "View webhook health and event history", scopable: false },
  { name: "payments:webhooks:manage", resource: "payments:webhooks", action: "manage", description: "Generate, verify, and retry payment webhooks", scopable: false },
  { name: "payments:test:run", resource: "payments:test", action: "run", description: "Run test transactions against a payment provider", scopable: false },
  { name: "payments:live:activate", resource: "payments:live", action: "activate", description: "Activate live payment processing", scopable: false },
  { name: "payments:manual-methods:manage", resource: "payments:manual-methods", action: "manage", description: "Configure manual/offline payment methods", scopable: false },
  { name: "payments:audit:view", resource: "payments:audit", action: "view", description: "View payment provider audit log", scopable: false },
];

export const PERMISSIONS: Permission[] = [
  ...HR_PERMISSIONS,
  ...CRM_PERMISSIONS,
  ...ACCOUNTING_PERMISSIONS,
  ...INVENTORY_PERMISSIONS,
  ...KB_PERMISSIONS,
  ...BLOG_PERMISSIONS,
  ...SALES_PERMISSIONS,
  ...SHARED_PERMISSIONS,
  ...SUPPORT_PERMISSIONS,
  ...CHAT_PERMISSIONS,
  ...API_TOKEN_PERMISSIONS,
  ...BILLING_PERMISSIONS,
  ...WORKFLOW_PERMISSIONS,
  ...ONBOARDING_PERMISSIONS,
  ...PAYMENTS_PERMISSIONS,
];

const SCOPABLE_PERMISSIONS = new Set(PERMISSIONS.filter((p) => p.scopable).map((p) => p.name));

export function isScopable(key: string): boolean {
  return SCOPABLE_PERMISSIONS.has(key);
}

const EMPLOYEE_SELF_SERVICE = [
  "self:attendance",
  "self:leaves",
  "self:expenses",
  "self:payslips",
  "hr:leaves:create",
  "hr:expenses:create",
  "chat:channels:read",
  "chat:messages:read",
  "chat:messages:write",
  "ai:chat:use",
  "settings:api-tokens:read",
  "settings:api-tokens:write",
  "calendar:read",
  "calendar:write",
  "onboarding:module-checklists:view",
  "onboarding:tours:view",
  "hr:onboarding:tasks:view",
  "hr:onboarding:tasks:complete",
];

const ALL_PERMISSIONS = PERMISSIONS.map((p) => p.name);

export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  OWNER: ALL_PERMISSIONS,

  CEO: ALL_PERMISSIONS,

  HR: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:employees:delete",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:payroll:generate",
    "hr:payroll:approve",
    "hr:salary:view",
    "hr:salary:manage",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:assets:view",
    "hr:assets:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "accounting:view",
    "accounting:report",
    "accounting:read",
    "accounting:accounts:read",
    "accounting:journal:read",
    "accounting:reports:read",
    "reports:view",
    "reports:create",
    "reports:export",
    "hr:employees:read",
    "hr:employees:manage",
    "hr:leaves:read",
    "hr:leaves:manage",
    "hr:expenses:read",
    "hr:expenses:manage",
    "hr:payrolls:read",
    "hr:payrolls:manage",
    "hr:bonuses:manage",
    "hr:career-ladders:manage",
    "hr:compliance:manage",
    "hr:email-templates:manage",
    "hr:exit:manage",
    "hr:feedback:manage",
    "hr:handbook:manage",
    "hr:integrations:manage",
    "hr:onboarding:manage",
    "hr:onboarding:plans:manage",
    "onboarding:module-checklists:manage",
    "onboarding:org:manage",
    "hr:alumni:read",
    "hr:analytics:read",
    "hr:headcount:read",
    "settings:onboarding:manage",
    "settings:email-templates:manage",
    "reports:generate",
    "reports:schedule",
    "audit-log:read",
    "hr:shifts:view",
    "hr:shifts:manage",
    "hr:geofencing:manage",
    "hr:biometric:manage",
    "hr:feedback:view",
    "hr:kpis:view",
    "hr:kpis:manage",
    "hr:learning:view",
    "hr:learning:manage",
    "hr:announcements:view",
    "hr:announcements:manage",
    "hr:signatures:view",
    "hr:signatures:manage",
    "hr:tax:view",
    "hr:tax:manage",
    "hr:travel:view",
    "hr:travel:manage",
    "hr:requisitions:view",
    "hr:requisitions:manage",
  ],

  SALES: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "crm:leads:view",
    "crm:leads:create",
    "crm:leads:update",
    "crm:leads:assign",
    "crm:deals:read",
    "crm:deals:create",
    "crm:contacts:view",
    "crm:quotes:read",
    "crm:organizations:view",
    "crm:clients:read",
    "crm:clients:update",
    "crm:targets:view",
    "crm:incentives:read",
    "crm:reports:view",
    "sales:view",
    "dashboard:sales:view",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:whiteboards:manage",
    "projects:workspace:manage",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  CUSTOMER_SUPPORT: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "dashboard:support:view",
    "dashboard:customer-executive:view",
    "support:kb:view",
    "support:kb:manage",
    "support:macros:view",
    "support:macros:manage",
    "kb:articles:view",
    "kb:articles:create",
    "kb:articles:update",
    "kb:articles:delete",
    "kb:articles:manage",
    "kb:categories:manage",
    "kb:spaces:view",
    "kb:spaces:manage",
    "kb:analytics:view",
    "kb:ai:generate",
    "kb:pages:view",
    "kb:pages:create",
    "kb:pages:update",
    "kb:pages:delete",
    "kb:pages:manage",
    "kb:templates:manage",
    "kb:reviews:view",
    "kb:reviews:manage",
    "kb:pages:import",
    "kb:pages:export",
    "kb:settings:manage",
    "projects:roadmap:view",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:whiteboards:manage",
    "projects:workspace:manage",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  ENGINEERING: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:whiteboards:manage",
    "projects:workspace:manage",
    "projects:sprints:view",
    "projects:timesheets:view",
    "projects:timesheets:create",
    "projects:goals:view",
    "projects:roadmap:view",
    "kb:articles:view",
    "kb:spaces:view",
  ],

  DESIGN: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:whiteboards:manage",
    "projects:workspace:manage",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  VIDEO_EDITOR: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:whiteboards:manage",
    "projects:workspace:manage",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  DIGITAL_MARKETING: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "blog:posts:manage",
    "blog:categories:manage",
    "kb:articles:view",
    "kb:spaces:view",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:whiteboards:manage",
    "projects:workspace:manage",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  BLOG_EDITOR: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "blog:posts:manage",
    "blog:categories:manage",
  ],

  BRANCH_MANAGER: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "crm:leads:view",
    "crm:leads:create",
    "crm:leads:update",
    "crm:leads:assign",
    "crm:deals:read",
    "crm:deals:create",
    "crm:deals:delete",
    "crm:contacts:view",
    "crm:contacts:manage",
    "crm:quotes:read",
    "crm:quotes:delete",
    "crm:organizations:view",
    "crm:clients:read",
    "crm:clients:update",
    "crm:clients:manage",
    "crm:assignment-rules:manage",
    "crm:email-templates:manage",
    "crm:scoring-rules:manage",
    "crm:sla:manage",
    "crm:automations:manage",
    "crm:products:manage",
    "sales:view",
    "sales:manage",
    "crm:targets:view",
    "crm:targets:manage",
    "crm:reports:view",
    "crm:reports:export",
    "crm:incentives:read",
    "crm:incentives:approve",
    "reports:generate",
    "reports:schedule",
    "projects:view",
    "projects:tickets:view",
    "reports:view",
    "settings:view",
    "dashboard:sales:view",
    "dashboard:customer-executive:view",
    "settings:automations:manage",
    "settings:custom-fields:manage",
    "settings:webhooks:manage",
    "dashboard:support:view",
    "support:kb:view",
    "support:macros:view",
    "accounting:view",
    "accounting:report",
    "accounting:read",
    "accounting:accounts:read",
    "accounting:journal:read",
    "accounting:reports:read",
    "inventory:products:read",
    "inventory:stock:read",
    "inventory:warehouses:read",
    "inventory:vendors:read",
    "inventory:purchase-orders:read",
    "inventory:purchase-orders:approve",
    "inventory:sales-orders:read",
    "inventory:sales-orders:confirm",
    "inventory:sales-orders:ship",
    "inventory:reports:read",
    "workflows:workflows:view",
    "workflows:executions:view",
    "workflows:approvals:view",
    "workflows:templates:view",
    "workflows:analytics:view",
    "hr:shifts:view",
    "hr:leaves:manage",
    "hr:feedback:view",
    "hr:learning:view",
    "hr:announcements:view",
    "hr:travel:view",
    "hr:travel:manage",
    "hr:requisitions:view",
    "hr:requisitions:manage",
  ],

  BRANCH_HR: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:payroll:generate",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:assets:view",
    "hr:assets:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "hr:employees:read",
    "hr:employees:manage",
    "hr:leaves:read",
    "hr:leaves:manage",
    "hr:expenses:read",
    "hr:expenses:manage",
    "hr:payrolls:read",
    "hr:onboarding:manage",
    "hr:exit:manage",
    "hr:handbook:manage",
    "hr:analytics:read",
    "hr:headcount:read",
    "hr:salary:view",
    "hr:salary:manage",
    "hr:bonuses:manage",
    "hr:career-ladders:manage",
    "hr:compliance:manage",
    "hr:email-templates:manage",
    "hr:feedback:manage",
    "hr:integrations:manage",
    "hr:alumni:read",
    "reports:generate",
    "reports:schedule",
    "projects:view",
    "projects:tickets:view",
    "reports:view",
    "settings:email-templates:manage",
    "settings:onboarding:manage",
    "hr:shifts:view",
    "hr:shifts:manage",
    "hr:geofencing:manage",
    "hr:biometric:manage",
    "hr:feedback:view",
    "hr:kpis:view",
    "hr:kpis:manage",
    "hr:learning:view",
    "hr:learning:manage",
    "hr:announcements:view",
    "hr:announcements:manage",
    "hr:signatures:view",
    "hr:signatures:manage",
    "hr:tax:view",
    "hr:tax:manage",
    "hr:travel:view",
    "hr:travel:manage",
    "hr:requisitions:view",
    "hr:requisitions:manage",
  ],

  INVENTORY_MANAGER: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "inventory:products:read",
    "inventory:products:create",
    "inventory:products:update",
    "inventory:products:delete",
    "inventory:stock:read",
    "inventory:stock:adjust",
    "inventory:stock:transfer",
    "inventory:warehouses:read",
    "inventory:warehouses:manage",
    "inventory:vendors:read",
    "inventory:vendors:manage",
    "inventory:purchase-orders:read",
    "inventory:purchase-orders:create",
    "inventory:purchase-orders:approve",
    "inventory:purchase-orders:receive",
    "inventory:sales-orders:read",
    "inventory:sales-orders:create",
    "inventory:sales-orders:confirm",
    "inventory:sales-orders:ship",
    "inventory:sales-orders:invoice",
    "inventory:reports:read",
    "reports:view",
  ],

  ACCOUNTANT: [
    ...EMPLOYEE_SELF_SERVICE,
    "tasks:read",
    "tasks:write",
    "accounting:view",
    "accounting:manage",
    "accounting:report",
    "accounting:read",
    "accounting:create",
    "accounting:accounts:read",
    "accounting:accounts:create",
    "accounting:accounts:update",
    "accounting:journal:read",
    "accounting:journal:manage",
    "accounting:reports:read",
    "reports:view",
    "reports:export",
    "reports:generate",
    "reports:schedule",
    "audit-log:read",
    // Per 12_Payment_Integration_Setup_Page.md: accountants view provider status, webhooks,
    // and audit; they cannot manage credentials, enable/disable a provider, or activate live.
    "payments:providers:view",
    "payments:webhooks:view",
    "payments:audit:view",
  ],
};

export const ALL_ROLES: readonly string[] = Object.keys(ROLE_DEFAULT_PERMISSIONS);
