import { moduleScopedPermissions } from "./permissions";
import { CRM_HR_ROLE_TEMPLATES } from "./role-templates-crm-hr.constants";
import { BUILD_ROLE_TEMPLATES } from "./role-templates-build.constants";
export type { RoleTemplate } from "./role-template.types";

export const ROLE_TEMPLATES: readonly RoleTemplate[] = [
  ...CRM_HR_ROLE_TEMPLATES,
  {
    id: "accountant",
    name: "Accountant",
    slug: "ACCOUNTANT",
    moduleKey: "accounting",
    permissions: [
      "accounting:view",
      "accounting:manage",
      "accounting:report",
      "accounting:read",
      "accounting:create",
      "accounting:accounts:read",
      "accounting:accounts:create",
      "accounting:accounts:update",
      "accounting:journal:read",
      "accounting:journal:manage",
      "accounting:reports:read",
      "reports:view",
      "reports:export",
      "reports:generate",
      "reports:schedule",
      "audit-log:read",
      "payroll:runs:view",
      "payroll:reports:view",
      "payroll:reports:export",
      "payroll:payslips:view",
      "payroll:bank:view",
      "payroll:bank:manage",
      "payroll:tax:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "customer_support",
    name: "Customer Support",
    slug: "CUSTOMER_SUPPORT",
    moduleKey: "support",
    permissions: [
      "dashboard:support:view",
      "dashboard:customer-executive:view",
      "support:kb:view",
      "support:kb:manage",
      "support:macros:view",
      "support:macros:manage",
      "support:tickets:manage",
      "kb:articles:view",
      "kb:articles:create",
      "kb:articles:update",
      "kb:articles:delete",
      "kb:articles:manage",
      "kb:categories:manage",
      "kb:spaces:view",
      "kb:spaces:manage",
      "kb:analytics:view",
      "kb:ai:generate",
      "kb:pages:view",
      "kb:pages:create",
      "kb:pages:update",
      "kb:pages:delete",
      "kb:pages:manage",
      "kb:templates:manage",
      "build:roadmap:view",
      "build:view",
      "build:tickets:view",
      "build:tickets:create",
      "build:tickets:update",
      "build:timesheets:view",
      "build:timesheets:create",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "inventory_manager",
    name: "Inventory Manager",
    slug: "INVENTORY_MANAGER",
    moduleKey: "inventory",
    permissions: [
      "inventory:products:read",
      "inventory:products:create",
      "inventory:products:update",
      "inventory:products:delete",
      "inventory:stock:read",
      "inventory:stock:adjust",
      "inventory:stock:transfer",
      "inventory:warehouses:read",
      "inventory:warehouses:manage",
      "inventory:warehouses:scope-all",
      "inventory:adjustments:approve",
      "inventory:adjustments:post",
      "inventory:vendors:read",
      "inventory:vendors:manage",
      "inventory:purchase-orders:read",
      "inventory:purchase-orders:create",
      "inventory:purchase-orders:approve",
      "inventory:purchase-orders:receive",
      "inventory:sales-orders:read",
      "inventory:sales-orders:create",
      "inventory:sales-orders:confirm",
      "inventory:sales-orders:ship",
      "inventory:sales-orders:invoice",
      "inventory:reports:read",
      "reports:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  ...BUILD_ROLE_TEMPLATES,
  {
    id: "crm_admin",
    name: "CRM Administrator",
    slug: "CRM_ADMIN",
    moduleKey: "crm",
    permissions: moduleScopedPermissions("crm"),
  },
  {
    id: "inventory_admin",
    name: "Inventory Administrator",
    slug: "INVENTORY_ADMIN",
    moduleKey: "inventory",
    permissions: moduleScopedPermissions("inventory"),
  },
];
