export interface RoleTemplate {
  id: string;
  name: string;
  slug: string;
  permissions: readonly string[];
}

export const ROLE_TEMPLATES: readonly RoleTemplate[] = [
  {
    id: "sales_rep",
    name: "Sales Representative",
    slug: "SALES_REP",
    permissions: [
      "crm:leads:view",
      "crm:leads:create",
      "crm:leads:update",
      "crm:deals:read",
      "crm:deals:create",
      "crm:clients:read",
      "crm:targets:view",
      "crm:incentives:read",
      "crm:reports:view",
      "sales:view",
      "dashboard:sales:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "hr_admin",
    name: "HR Administrator",
    slug: "HR_ADMIN",
    permissions: [
      "hr:employees:read",
      "hr:employees:manage",
      "hr:leaves:read",
      "hr:leaves:manage",
      "hr:expenses:read",
      "hr:expenses:manage",
      "hr:payroll:view",
      "hr:payroll:generate",
      "hr:payroll:approve",
      "hr:payrolls:read",
      "hr:payrolls:manage",
      "hr:salary:view",
      "hr:salary:manage",
      "hr:attendance:view",
      "hr:attendance:manage",
      "hr:documents:view",
      "hr:documents:manage",
      "hr:assets:view",
      "hr:assets:manage",
      "hr:performance:view",
      "hr:performance:manage",
      "hr:goals:view",
      "hr:goals:manage",
      "hr:onboarding:manage",
      "hr:exit:manage",
      "hr:handbook:manage",
      "hr:analytics:read",
      "hr:headcount:read",
      "reports:view",
      "reports:generate",
      "reports:schedule",
      "audit-log:read",
      "hr:shifts:view",
      "hr:shifts:manage",
      "hr:geofencing:manage",
      "hr:biometric:manage",
      "hr:feedback:view",
      "hr:kpis:view",
      "hr:kpis:manage",
      "hr:learning:view",
      "hr:learning:manage",
      "hr:announcements:view",
      "hr:announcements:manage",
      "hr:signatures:view",
      "hr:signatures:manage",
      "hr:tax:view",
      "hr:tax:manage",
      "hr:travel:view",
      "hr:travel:manage",
      "hr:requisitions:view",
      "hr:requisitions:manage",
      "payroll:runs:view",
      "payroll:runs:create",
      "payroll:runs:update",
      "payroll:runs:approve",
      "payroll:runs:manage",
      "payroll:salaries:view",
      "payroll:salaries:update",
      "payroll:salaries:manage",
      "payroll:templates:view",
      "payroll:templates:manage",
      "payroll:policies:view",
      "payroll:policies:manage",
      "payroll:components:view",
      "payroll:components:manage",
      "payroll:payslips:view",
      "payroll:payslips:manage",
      "payroll:bank:view",
      "payroll:bank:manage",
      "payroll:tax:view",
      "payroll:tax:manage",
      "payroll:reports:view",
      "payroll:reports:export",
      "payroll:settings:manage",
      "payroll:fnf:view",
      "payroll:fnf:manage",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "branch_hr",
    name: "Branch HR",
    slug: "BRANCH_HR",
    permissions: [
      "hr:employees:view",
      "hr:employees:create",
      "hr:employees:update",
      "hr:employees:read",
      "hr:employees:manage",
      "hr:attendance:view",
      "hr:attendance:manage",
      "hr:leaves:view",
      "hr:leaves:approve",
      "hr:leaves:read",
      "hr:leaves:manage",
      "hr:payroll:view",
      "hr:payroll:generate",
      "hr:expenses:view",
      "hr:expenses:approve",
      "hr:expenses:read",
      "hr:expenses:manage",
      "hr:documents:view",
      "hr:documents:manage",
      "hr:assets:view",
      "hr:assets:manage",
      "hr:performance:view",
      "hr:performance:manage",
      "hr:goals:view",
      "hr:goals:manage",
      "hr:payrolls:read",
      "hr:onboarding:manage",
      "hr:exit:manage",
      "hr:handbook:manage",
      "hr:analytics:read",
      "hr:headcount:read",
      "hr:salary:view",
      "hr:salary:manage",
      "hr:bonuses:manage",
      "hr:career-ladders:manage",
      "hr:compliance:manage",
      "hr:email-templates:manage",
      "hr:feedback:manage",
      "hr:integrations:manage",
      "hr:alumni:read",
      "reports:view",
      "reports:generate",
      "reports:schedule",
      "settings:email-templates:manage",
      "settings:onboarding:manage",
      "hr:shifts:view",
      "hr:shifts:manage",
      "hr:geofencing:manage",
      "hr:biometric:manage",
      "hr:feedback:view",
      "hr:kpis:view",
      "hr:kpis:manage",
      "hr:learning:view",
      "hr:learning:manage",
      "hr:announcements:view",
      "hr:announcements:manage",
      "hr:signatures:view",
      "hr:signatures:manage",
      "hr:tax:view",
      "hr:tax:manage",
      "hr:travel:view",
      "hr:travel:manage",
      "hr:requisitions:view",
      "hr:requisitions:manage",
      "payroll:runs:view",
      "payroll:runs:create",
      "payroll:runs:update",
      "payroll:runs:approve",
      "payroll:runs:manage",
      "payroll:salaries:view",
      "payroll:salaries:update",
      "payroll:salaries:manage",
      "payroll:templates:view",
      "payroll:templates:manage",
      "payroll:policies:view",
      "payroll:policies:manage",
      "payroll:components:view",
      "payroll:components:manage",
      "payroll:payslips:view",
      "payroll:payslips:manage",
      "payroll:bank:view",
      "payroll:bank:manage",
      "payroll:tax:view",
      "payroll:tax:manage",
      "payroll:reports:view",
      "payroll:reports:export",
      "payroll:settings:manage",
      "payroll:fnf:view",
      "payroll:fnf:manage",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "branch_manager",
    name: "Branch Manager",
    slug: "BRANCH_MANAGER",
    permissions: [
      "hr:employees:view",
      "hr:employees:create",
      "hr:employees:update",
      "hr:attendance:view",
      "hr:attendance:manage",
      "hr:leaves:view",
      "hr:leaves:approve",
      "hr:payroll:view",
      "hr:expenses:view",
      "hr:expenses:approve",
      "hr:documents:view",
      "hr:documents:manage",
      "hr:performance:view",
      "hr:performance:manage",
      "hr:goals:view",
      "hr:goals:manage",
      "crm:leads:view",
      "crm:leads:create",
      "crm:leads:update",
      "crm:leads:assign",
      "crm:deals:read",
      "crm:deals:create",
      "crm:deals:delete",
      "crm:clients:read",
      "crm:clients:update",
      "crm:clients:manage",
      "crm:targets:view",
      "crm:targets:manage",
      "crm:reports:view",
      "crm:reports:export",
      "crm:incentives:read",
      "crm:incentives:approve",
      "sales:view",
      "sales:manage",
      "reports:view",
      "reports:generate",
      "reports:schedule",
      "settings:view",
      "dashboard:sales:view",
      "dashboard:customer-executive:view",
      "accounting:view",
      "accounting:read",
      "accounting:accounts:read",
      "accounting:journal:read",
      "accounting:reports:read",
      "inventory:products:read",
      "inventory:stock:read",
      "inventory:warehouses:read",
      "inventory:purchase-orders:read",
      "inventory:purchase-orders:approve",
      "inventory:sales-orders:read",
      "inventory:reports:read",
      "hr:shifts:view",
      "hr:leaves:manage",
      "hr:feedback:view",
      "hr:learning:view",
      "hr:announcements:view",
      "hr:travel:view",
      "hr:travel:manage",
      "hr:requisitions:view",
      "hr:requisitions:manage",
      "payroll:runs:view",
      "payroll:salaries:view",
      "payroll:reports:view",
      "payroll:payslips:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "accountant",
    name: "Accountant",
    slug: "ACCOUNTANT",
    permissions: [
      "accounting:view",
      "accounting:manage",
      "accounting:report",
      "accounting:read",
      "accounting:create",
      "accounting:accounts:read",
      "accounting:accounts:create",
      "accounting:accounts:update",
      "accounting:journal:read",
      "accounting:journal:manage",
      "accounting:reports:read",
      "reports:view",
      "reports:export",
      "reports:generate",
      "reports:schedule",
      "audit-log:read",
      "payroll:runs:view",
      "payroll:reports:view",
      "payroll:reports:export",
      "payroll:payslips:view",
      "payroll:bank:view",
      "payroll:bank:manage",
      "payroll:tax:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "engineering",
    name: "Engineering",
    slug: "ENGINEERING",
    permissions: [
      "projects:view",
      "projects:tickets:view",
      "projects:tickets:create",
      "projects:tickets:update",
      "projects:sprints:view",
      "projects:changerequests:view",
      "projects:changerequests:create",
      "projects:timesheets:view",
      "projects:timesheets:create",
      "projects:goals:view",
      "projects:roadmap:view",
      "kb:articles:view",
      "kb:spaces:view",
      "kb:pages:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "customer_support",
    name: "Customer Support",
    slug: "CUSTOMER_SUPPORT",
    permissions: [
      "dashboard:support:view",
      "dashboard:customer-executive:view",
      "support:kb:view",
      "support:kb:manage",
      "support:macros:view",
      "support:macros:manage",
      "support:tickets:manage",
      "kb:articles:view",
      "kb:articles:create",
      "kb:articles:update",
      "kb:articles:delete",
      "kb:articles:manage",
      "kb:categories:manage",
      "kb:spaces:view",
      "kb:spaces:manage",
      "kb:analytics:view",
      "kb:ai:generate",
      "kb:pages:view",
      "kb:pages:create",
      "kb:pages:update",
      "kb:pages:delete",
      "kb:pages:manage",
      "kb:templates:manage",
      "projects:roadmap:view",
      "projects:view",
      "projects:tickets:view",
      "projects:tickets:create",
      "projects:tickets:update",
      "projects:timesheets:view",
      "projects:timesheets:create",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "digital_marketing",
    name: "Digital Marketing",
    slug: "DIGITAL_MARKETING",
    permissions: [
      "blog:posts:manage",
      "blog:categories:manage",
      "kb:articles:view",
      "kb:spaces:view",
      "kb:pages:view",
      "projects:view",
      "projects:tickets:view",
      "projects:tickets:create",
      "projects:tickets:update",
      "projects:timesheets:view",
      "projects:timesheets:create",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "inventory_manager",
    name: "Inventory Manager",
    slug: "INVENTORY_MANAGER",
    permissions: [
      "inventory:products:read",
      "inventory:products:create",
      "inventory:products:update",
      "inventory:products:delete",
      "inventory:stock:read",
      "inventory:stock:adjust",
      "inventory:stock:transfer",
      "inventory:warehouses:read",
      "inventory:warehouses:manage",
      "inventory:vendors:read",
      "inventory:vendors:manage",
      "inventory:purchase-orders:read",
      "inventory:purchase-orders:create",
      "inventory:purchase-orders:approve",
      "inventory:purchase-orders:receive",
      "inventory:sales-orders:read",
      "inventory:sales-orders:create",
      "inventory:sales-orders:confirm",
      "inventory:sales-orders:ship",
      "inventory:sales-orders:invoice",
      "inventory:reports:read",
      "reports:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "recruiter",
    name: "Recruiter",
    slug: "RECRUITER",
    permissions: [
      "hr:employees:read",
      "hr:onboarding:manage",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "project_manager",
    name: "Project Manager",
    slug: "PROJECT_MANAGER",
    permissions: [
      "projects:view",
      "projects:create",
      "projects:manage",
      "projects:tickets:view",
      "projects:tickets:create",
      "projects:tickets:update",
      "projects:tickets:assign",
      "projects:sprints:view",
      "projects:sprints:manage",
      "projects:changerequests:view",
      "projects:changerequests:manage",
      "projects:approvals:view",
      "projects:approvals:request",
      "projects:approvals:decide",
      "projects:approvals:manage",
      "projects:clientvisibility:manage",
      "projects:ai:use",
      "projects:timesheets:view",
      "projects:timesheets:manage",
      "projects:goals:view",
      "projects:goals:manage",
      "projects:roadmap:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "viewer",
    name: "Read-Only Viewer",
    slug: "VIEWER",
    permissions: [
      "crm:leads:view",
      "crm:deals:read",
      "projects:view",
      "projects:tickets:view",
      "hr:employees:read",
      "reports:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "client_user",
    name: "Client User",
    slug: "CLIENT",
    permissions: [
      "projects:portal:view",
      "projects:changerequests:view",
      "projects:changerequests:create",
    ],
  },
];
