import type { RoleTemplate } from "./role-template.types";

export const CRM_ROLE_TEMPLATES: readonly RoleTemplate[] = [
  {
    id: "sales_rep",
    name: "Sales Representative",
    slug: "SALES_REP",
    moduleKey: "crm",
    permissions: [
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
      "self:cases",
      "hr:leaves:create",
      "hr:expenses:create",
      "hr:expenses:view",
      "hr:expenses:read",
      "hr:travel:view",
      "hr:travel:create",
      "chat:channels:read",
      "chat:channels:write",
      "chat:messages:read",
      "chat:messages:write",
      "chat:huddles:start",
      "chat:invite-links:manage",
      "ai:chat:use",
      "ai:feedback:create",
      "ai:summaries:view",
      "ai:summaries:create",
      "settings:api-tokens:read",
      "settings:api-tokens:write",
      "calendar:read",
      "calendar:write",
      "calendar:ai:use",
      "calendar:events:export",
      "mail:inbox:view",
      "mail:messages:send",
      "mail:messages:manage",
      "mail:ai:use",
      "integrations:connections:view",
      "integrations:connections:manage",
      "onboarding:module-checklists:view",
      "onboarding:tours:view",
      "hr:onboarding:tasks:view",
      "hr:onboarding:tasks:complete",
      "timesheets:entries:view",
      "timesheets:entries:create",
      "timesheets:entries:update",
      "tasks:read",
      "tasks:write",
      "crm:leads:view",
      "crm:tasks:view",
      "crm:tasks:update",
      "crm:leads:create",
      "crm:leads:update",
      "crm:leads:assign",
      "crm:deals:read",
      "crm:deals:create",
      "crm:contacts:view",
      "crm:quotes:read",
      "crm:organizations:view",
      "crm:clients:read",
      "crm:clients:update",
      "crm:targets:view",
      "crm:incentives:read",
      "crm:reports:view",
      "crm:data-quality:view",
      "crm:campaigns:view",
      "crm:customer360:view",
      "crm:settings:view",
      "crm:ai:use",
      "sales:view",
      "dashboard:sales:view",
    ],
  },
];
