import type { RoleTemplate } from "./role-template.types";
import { moduleScopedPermissions } from "./permissions";

export const BUILD_ROLE_TEMPLATES: readonly RoleTemplate[] = [
  {
    id: "engineering",
    name: "Engineering",
    slug: "ENGINEERING",
    moduleKey: "build",
    permissions: [
      "build:view",
      "build:tickets:view",
      "build:tickets:create",
      "build:tickets:update",
      "build:cycles:view",
      "build:changerequests:view",
      "build:changerequests:create",
      "build:timesheets:view",
      "build:timesheets:create",
      "build:goals:view",
      "build:roadmap:view",
      "kb:articles:view",
      "kb:spaces:view",
      "kb:pages:view",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "digital_marketing",
    name: "Digital Marketing",
    slug: "DIGITAL_MARKETING",
    moduleKey: "build",
    permissions: [
      "kb:articles:view",
      "kb:spaces:view",
      "kb:pages:view",
      "build:view",
      "build:tickets:view",
      "build:tickets:create",
      "build:tickets:update",
      "build:timesheets:view",
      "build:timesheets:create",
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
    ],
  },
  {
    id: "project_manager",
    name: "Project Manager",
    slug: "PROJECT_MANAGER",
    moduleKey: "build",
    permissions: [
      "self:attendance",
      "self:leaves",
      "self:expenses",
      "self:payslips",
      "self:cases",
      "hr:leaves:create",
      "hr:expenses:create",
      "chat:channels:read",
      "chat:channels:write",
      "chat:messages:read",
      "chat:messages:write",
      "tasks:read",
      "tasks:write",
      "build:view",
      "build:create",
      "build:update",
      "build:manage",
      "build:tickets:view",
      "build:tickets:create",
      "build:tickets:update",
      "build:tickets:assign",
      "build:cycles:view",
      "build:cycles:manage",
      "build:changerequests:view",
      "build:changerequests:manage",
      "build:approvals:view",
      "build:approvals:request",
      "build:approvals:decide",
      "build:approvals:manage",
      "build:risks:view",
      "build:risks:manage",
      "build:decisions:view",
      "build:decisions:manage",
      "build:meetings:view",
      "build:meetings:manage",
      "build:incidents:view",
      "build:incidents:manage",
      "build:forms:view",
      "build:forms:manage",
      "build:portfolios:view",
      "build:portfolios:manage",
      "build:programs:view",
      "build:programs:manage",
      "build:managed-products:view",
      "build:managed-products:create",
      "build:managed-products:update",
      "build:managed-products:delete",
      "build:workflow:view",
      "build:workflow:manage",
      "build:clientvisibility:manage",
      "build:ai:use",
      "build:timesheets:view",
      "build:timesheets:manage",
      "build:goals:view",
      "build:goals:manage",
      "build:delete",
      "build:restore",
      "build:roadmap:view",
      "build:roadmap:manage",
      "build:tickets:delete",
      "build:tickets:restore",
      "build:members:view",
      "build:members:manage",
      "build:customers:view",
      "build:customers:manage",
      "timesheets:entries:view",
      "timesheets:entries:create",
      "timesheets:entries:update",
      "timesheets:entries:void",
    ],
  },
  {
    id: "product_management_admin",
    name: "Product Management Administrator",
    slug: "PRODUCT_MANAGEMENT_ADMIN",
    moduleKey: "build",
    permissions: moduleScopedPermissions("build"),
  },
];
