import { z } from "zod";
import { wireDate, nullableWireDate } from "../../../common/openapi/wire-types";
import { itemsPagedSchema } from "../../../common/openapi/response-envelopes";

export const signEnvelopeRowSchema = z.object({
  id: z.number().int(),
  orgId: z.string(),
  title: z.string(),
  subject: z.string().nullable(),
  message: z.string().nullable(),
  status: z.enum(["draft", "ready_to_send", "sent", "delivered", "partially_completed", "completed", "declined", "voided", "expired", "correction_required", "failed"]),
  routingMode: z.enum(["parallel", "sequential", "mixed"]),
  ccTiming: z.enum(["on_send", "on_complete"]),
  allowDecline: z.boolean(),
  sourceModule: z.string().nullable(),
  sourceEntityType: z.string().nullable(),
  sourceEntityId: z.string().nullable(),
  templateId: z.number().int().nullable(),
  watermarkPolicyId: z.number().int().nullable(),
  senderMembershipId: z.number().int().nullable(),
  reminderEnabled: z.boolean(),
  reminderFirstAfterDays: z.number().int(),
  reminderRepeatDays: z.number().int(),
  reminderMaxCount: z.number().int(),
  reminderSentCount: z.number().int(),
  lastReminderAt: nullableWireDate(),
  expiresAt: nullableWireDate(),
  sentAt: nullableWireDate(),
  completedAt: nullableWireDate(),
  voidedAt: nullableWireDate(),
  voidedByMembershipId: z.number().int().nullable(),
  voidReason: z.string().nullable(),
  declinedAt: nullableWireDate(),
  correctionRequiredAt: nullableWireDate(),
  correctionReason: z.string().nullable(),
  finalizationKey: z.string().nullable(),
  finalizedAt: nullableWireDate(),
  finalPdfFileKey: z.string().nullable(),
  finalPdfHash: z.string().nullable(),
  publicFormId: z.number().int().nullable(),
  metadataJson: z.record(z.string(), z.unknown()),
  createdAt: wireDate(),
  updatedAt: wireDate(),
});

export const envelopeMutationResponseSchema = signEnvelopeRowSchema;

export const listEnvelopesResponseSchema = itemsPagedSchema(signEnvelopeRowSchema).extend({
  pageSize: z.number().int(),
});

export const getEnvelopeFullResponseSchema = z.object({
  envelope: signEnvelopeRowSchema,
  documents: z.array(
    z.object({
      id: z.number().int(),
      orgId: z.string(),
      envelopeId: z.number().int(),
      originalFileKey: z.string(),
      currentFileKey: z.string(),
      fileName: z.string(),
      mimeType: z.string(),
      pageCount: z.number().int().nullable(),
      fileSize: z.number().int(),
      sha256Hash: z.string(),
      conversionStatus: z.enum(["pending", "converted", "failed", "not_needed"]),
      conversionError: z.string().nullable(),
      orderIndex: z.number().int(),
      createdByMembershipId: z.number().int().nullable(),
      createdAt: wireDate(),
      updatedAt: wireDate(),
    }),
  ),
  recipients: z.array(
    z.object({
      id: z.number().int(),
      orgId: z.string(),
      envelopeId: z.number().int(),
      roleName: z.string(),
      recipientType: z.enum(["signer", "approver", "cc", "viewer", "in_person_host", "internal_reviewer"]),
      name: z.string(),
      email: z.string().nullable(),
      phone: z.string().nullable(),
      userMembershipId: z.number().int().nullable(),
      routingOrder: z.number().int(),
      status: z.enum(["pending", "invited", "viewed", "authenticated", "signing", "completed", "declined", "delegated", "bounced", "expired"]),
      authMethod: z.enum(["email_link", "access_code", "otp_email", "otp_sms", "sso", "passkey", "kba", "id_verification"]),
      accessCodeHash: z.string().nullable(),
      otpCodeHash: z.string().nullable(),
      otpExpiresAt: nullableWireDate(),
      otpAttempts: z.number().int(),
      failedAuthAttempts: z.number().int(),
      authLockedUntil: nullableWireDate(),
      signingTokenHash: z.string().nullable(),
      tokenExpiresAt: nullableWireDate(),
      tokenRevokedAt: nullableWireDate(),
      consentAcceptedAt: nullableWireDate(),
      consentIp: z.string().nullable(),
      consentUserAgent: z.string().nullable(),
      consentDisclosureVersion: z.string().nullable(),
      delegatedToRecipientId: z.number().int().nullable(),
      viewedAt: nullableWireDate(),
      authenticatedAt: nullableWireDate(),
      completedAt: nullableWireDate(),
      declinedAt: nullableWireDate(),
      declinedReason: z.string().nullable(),
      bouncedAt: nullableWireDate(),
      createdAt: wireDate(),
      updatedAt: wireDate(),
    }),
  ),
  fields: z.array(
    z.object({
      id: z.number().int(),
      orgId: z.string(),
      envelopeId: z.number().int(),
      documentId: z.number().int(),
      recipientId: z.number().int(),
      fieldType: z.enum(["signature", "initials", "date_signed", "text", "multiline", "email", "name", "company", "title", "checkbox", "radio", "dropdown", "attachment", "stamp", "strikethrough", "readonly_merge"]),
      label: z.string().nullable(),
      pageNumber: z.number().int(),
      x: z.number().int(),
      y: z.number().int(),
      width: z.number().int(),
      height: z.number().int(),
      required: z.boolean(),
      readonly: z.boolean(),
      orderIndex: z.number().int(),
      groupId: z.string().nullable(),
      defaultValue: z.string().nullable(),
      optionsJson: z.array(z.string()).nullable(),
      validationType: z.string().nullable(),
      validationRulesJson: z.record(z.string(), z.unknown()).nullable(),
      conditionalRulesJson: z.record(z.string(), z.unknown()).nullable(),
      valueJson: z.record(z.string(), z.unknown()).nullable(),
      attachmentFileKey: z.string().nullable(),
      completedAt: nullableWireDate(),
      createdAt: wireDate(),
      updatedAt: wireDate(),
    }),
  ),
});

export const validateEnvelopeResponseSchema = z.object({
  valid: z.boolean(),
  errors: z.array(z.string()),
});

export const resendEnvelopeResponseSchema = z.object({ resentCount: z.number().int() });

export const sendReminderResponseSchema = z.object({ remindedCount: z.number().int() });
