import type { PayrollTemplateSeed } from "../../payroll.types";
import { DEFAULT_PAYROLL_TOGGLES } from "../../payroll.types";

export const CONTRACTOR_SEED: PayrollTemplateSeed = {
  key: "CONTRACTOR",
  name: "Contractor",
  description: "Minimal structure for independent contractors: contract fee with 10% TDS withholding; statutory deductions off.",
  bestFor: "Freelancers, consultants, and independent contractors billed on a fixed or daily rate",
  complexity: "SIMPLE",
  badge: "Contractor Ready",
  category: "CONTRACTOR",
  isRecommended: false,
  defaultToggles: {
    ...DEFAULT_PAYROLL_TOGGLES,
    pf: false,
    esi: false,
    professionalTax: false,
    tds: true,
    lopFromAttendance: false,
    leaveSync: false,
    timesheets: false,
    contractorPayments: true,
    bankPayoutFile: true,
    payslipPublishing: true,
    approvalWorkflow: true,
    lockAfterApproval: true,
  },
  defaultComponents: [
    {
      code: "CONTRACT_FEE",
      name: "Contract Fee",
      type: "EARNING",
      calcMethod: "FIXED",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "TDS",
      name: "TDS Withholding (Sec 194C)",
      type: "TAX",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "10",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "tds",
      sortOrder: 2,
    },
  ],
};

export const GLOBAL_REMOTE_SEED: PayrollTemplateSeed = {
  key: "GLOBAL_REMOTE",
  name: "Global Remote",
  description: "Multi-currency contractor support with country compliance checklists and global payment reporting.",
  bestFor: "Fully remote distributed teams, global contractors, and multi-country payroll operations",
  complexity: "ADVANCED",
  badge: "Global Ready",
  category: "GLOBAL_REMOTE",
  isRecommended: false,
  defaultToggles: {
    ...DEFAULT_PAYROLL_TOGGLES,
    pf: false,
    esi: false,
    professionalTax: false,
    tds: true,
    lopFromAttendance: false,
    contractorPayments: true,
    multiCurrency: true,
    reimbursements: true,
    bonuses: true,
    countryComplianceChecklist: true,
    globalPaymentReport: true,
    bankPayoutFile: true,
    payslipPublishing: true,
    approvalWorkflow: true,
    lockAfterApproval: true,
    essAllowReimbursements: true,
  },
  defaultComponents: [
    {
      code: "CONTRACT_FEE",
      name: "Contract Fee",
      type: "EARNING",
      calcMethod: "FIXED",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "INTERNET",
      name: "Internet / Home Office Allowance",
      type: "REIMBURSEMENT",
      calcMethod: "FIXED",
      amount: "100.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "TRAVEL",
      name: "Travel Allowance",
      type: "REIMBURSEMENT",
      calcMethod: "FIXED",
      amount: "200.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "BONUS",
      name: "Performance Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 4,
    },
    {
      code: "TDS",
      name: "Tax Withholding",
      type: "TAX",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "10",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "tds",
      sortOrder: 5,
    },
  ],
};
