import type { PayrollTemplateSeed } from "../../payroll.types";
import { DEFAULT_PAYROLL_TOGGLES, PAYROLL_TEMPLATE_KEYS } from "../../payroll.types";

type PayrollTemplateKey = (typeof PAYROLL_TEMPLATE_KEYS)[number];

const COUNTRY_STANDARD_TOGGLES = {
  ...DEFAULT_PAYROLL_TOGGLES,
  pf: false,
  esi: false,
  professionalTax: false,
  tds: false,
  gratuity: false,
  lwf: false,
  lopFromAttendance: true,
  leaveSync: true,
  bankPayoutFile: true,
  payslipPublishing: true,
  approvalWorkflow: true,
  lockAfterApproval: true,
  payrollVarianceWarnings: true,
};

export const UAE_STANDARD_SEED: PayrollTemplateSeed = {
  key: "UAE_STANDARD" as PayrollTemplateKey,
  name: "UAE Standard Payroll",
  description: "Typical UAE salary structure (Basic + Housing + Transport allowances) with no income tax, WPS-compliant payout, and gratuity accrual.",
  bestFor: "UAE-registered entities running payroll for expatriate and national employees in WPS-compliant environments",
  complexity: "SIMPLE",
  badge: "UAE",
  category: "COUNTRY_STANDARD",
  isRecommended: false,
  defaultToggles: {
    ...COUNTRY_STANDARD_TOGGLES,
    bonuses: true,
    reimbursements: true,
    gratuity: false,
    essAllowReimbursements: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Basic Salary",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "100",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "HOUSING",
      name: "Housing Allowance",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc * 0.25",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "TRANSPORT",
      name: "Transport Allowance",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc * 0.10",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "BONUS",
      name: "Performance Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 4,
    },
    {
      code: "GPSSA_EMP",
      name: "GPSSA Pension (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "5",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "gpssa",
      sortOrder: 5,
    },
    {
      code: "GPSSA_ER",
      name: "GPSSA Pension (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "12.5",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "gpssa",
      sortOrder: 6,
    },
  ],
};

export const SG_STANDARD_SEED: PayrollTemplateSeed = {
  key: "SG_STANDARD" as PayrollTemplateKey,
  name: "SG Standard Payroll",
  description: "CPF contributions (employee 20% + employer 17% on ordinary wages), itemized payslip, and annual AWS bonus provision for Singapore employees.",
  bestFor: "Singapore-registered companies employing Singapore citizens and permanent residents",
  complexity: "MODERATE",
  badge: "SG",
  category: "COUNTRY_STANDARD",
  isRecommended: false,
  defaultToggles: {
    ...COUNTRY_STANDARD_TOGGLES,
    bonuses: true,
    reimbursements: true,
    essAllowReimbursements: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Basic Salary",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "100",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "AWS_BONUS",
      name: "Annual Wage Supplement (AWS)",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "BONUS",
      name: "Performance Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "CPF_EMP",
      name: "CPF (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "20",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "cpf",
      sortOrder: 4,
    },
    {
      code: "CPF_ER",
      name: "CPF (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "17",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "cpf",
      sortOrder: 5,
    },
  ],
};

export const AU_STANDARD_SEED: PayrollTemplateSeed = {
  key: "AU_STANDARD" as PayrollTemplateKey,
  name: "AU Standard Payroll",
  description: "PAYG withholding, Superannuation Guarantee (12%), and Single Touch Payroll compliant structure for Australian employees.",
  bestFor: "Australian businesses running payroll for permanent and casual employees under STP Phase 2",
  complexity: "MODERATE",
  badge: "AU",
  category: "COUNTRY_STANDARD",
  isRecommended: false,
  defaultToggles: {
    ...COUNTRY_STANDARD_TOGGLES,
    bonuses: true,
    reimbursements: true,
    overtime: true,
    essAllowReimbursements: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Base Salary",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "100",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "BONUS",
      name: "Performance Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "PAYG",
      name: "PAYG Withholding",
      type: "TAX",
      calcMethod: "FORMULA",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "payg",
      sortOrder: 3,
    },
    {
      code: "SUPER_ER",
      name: "Superannuation Guarantee (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "super",
      sortOrder: 4,
    },
  ],
};
