import type { PayrollTemplateSeed } from "../../payroll.types";
import { DEFAULT_PAYROLL_TOGGLES, PAYROLL_TEMPLATE_KEYS } from "../../payroll.types";

type PayrollTemplateKey = (typeof PAYROLL_TEMPLATE_KEYS)[number];

const COUNTRY_STANDARD_TOGGLES = {
  ...DEFAULT_PAYROLL_TOGGLES,
  pf: false,
  esi: false,
  professionalTax: false,
  tds: false,
  gratuity: false,
  lwf: false,
  lopFromAttendance: true,
  leaveSync: true,
  bankPayoutFile: true,
  payslipPublishing: true,
  approvalWorkflow: true,
  lockAfterApproval: true,
  payrollVarianceWarnings: true,
};

export const US_STANDARD_SEED: PayrollTemplateSeed = {
  key: "US_STANDARD" as PayrollTemplateKey,
  name: "US Standard Payroll",
  description: "FICA (Social Security + Medicare), Federal Withholding, and 401(k) placeholder for US salaried employees.",
  bestFor: "US-based companies with salaried W-2 employees requiring FICA and federal withholding compliance",
  complexity: "MODERATE",
  badge: "US",
  category: "COUNTRY_STANDARD",
  isRecommended: false,
  defaultToggles: {
    ...COUNTRY_STANDARD_TOGGLES,
    bonuses: true,
    reimbursements: true,
    employeeDeclarations: false,
    essAllowReimbursements: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Base Salary",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "100",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "BONUS",
      name: "Performance Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "K401_EMP",
      name: "401(k) Employee Contribution",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "0",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "SS_EMP",
      name: "Social Security (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "6.2",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "ss",
      sortOrder: 4,
    },
    {
      code: "SS_ER",
      name: "Social Security (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "6.2",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "ss",
      sortOrder: 5,
    },
    {
      code: "MEDICARE_EMP",
      name: "Medicare (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "1.45",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "medicare",
      sortOrder: 6,
    },
    {
      code: "MEDICARE_ER",
      name: "Medicare (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "1.45",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "medicare",
      sortOrder: 7,
    },
    {
      code: "FWT",
      name: "Federal Withholding Tax",
      type: "TAX",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "fwt",
      sortOrder: 8,
    },
  ],
};

export const UK_STANDARD_SEED: PayrollTemplateSeed = {
  key: "UK_STANDARD" as PayrollTemplateKey,
  name: "UK Standard Payroll",
  description: "PAYE income tax withholding, National Insurance (employee and employer), and workplace pension auto-enrolment for UK employees.",
  bestFor: "UK-registered employers running payroll for PAYE employees with full RTI compliance",
  complexity: "MODERATE",
  badge: "UK",
  category: "COUNTRY_STANDARD",
  isRecommended: false,
  defaultToggles: {
    ...COUNTRY_STANDARD_TOGGLES,
    bonuses: true,
    reimbursements: true,
    essAllowReimbursements: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Base Salary",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "100",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "BONUS",
      name: "Performance Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "PAYE",
      name: "PAYE Income Tax",
      type: "TAX",
      calcMethod: "FORMULA",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "paye",
      sortOrder: 3,
    },
    {
      code: "NI_EMP",
      name: "National Insurance (Employee)",
      type: "DEDUCTION",
      calcMethod: "FORMULA",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "ni_emp",
      sortOrder: 4,
    },
    {
      code: "NI_ER",
      name: "National Insurance (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "FORMULA",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "ni_er",
      sortOrder: 5,
    },
    {
      code: "PENSION_AE_EMP",
      name: "Workplace Pension (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "5",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pension_ae",
      sortOrder: 6,
    },
    {
      code: "PENSION_AE_ER",
      name: "Workplace Pension (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "3",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "pension_ae",
      sortOrder: 7,
    },
  ],
};
