import type { PayrollTemplateSeed } from "../../payroll.types";
import { DEFAULT_PAYROLL_TOGGLES } from "../../payroll.types";

export const EXECUTIVE_SEED: PayrollTemplateSeed = {
  key: "EXECUTIVE",
  name: "Executive / Senior Leadership",
  description: "High fixed compensation with performance bonuses, retention bonus, gratuity provisioning, and full declaration support.",
  bestFor: "C-suite, VPs, directors, and senior leadership with complex compensation and tax needs",
  complexity: "ADVANCED",
  badge: "Executive",
  category: "EXECUTIVE",
  isRecommended: false,
  defaultToggles: {
    ...DEFAULT_PAYROLL_TOGGLES,
    pf: true,
    gratuity: true,
    professionalTax: true,
    tds: true,
    lopFromAttendance: true,
    bonuses: true,
    manualAdjustments: true,
    employeeDeclarations: true,
    bankPayoutFile: true,
    payslipPublishing: true,
    approvalWorkflow: true,
    lockAfterApproval: true,
    payrollVarianceWarnings: true,
    essShowSalaryStructure: true,
    essAllowTaxDeclarations: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Basic Salary",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc * 0.40",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "HRA",
      name: "House Rent Allowance",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "50",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "SPECIAL",
      name: "Special Allowance",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc - basic - (basic * 0.50)",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "BONUS",
      name: "Performance Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 4,
    },
    {
      code: "RETENTION_BONUS",
      name: "Retention Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 5,
    },
    {
      code: "PF_EMP",
      name: "Provident Fund (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 6,
    },
    {
      code: "PF_ER",
      name: "Provident Fund (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 7,
    },
    {
      code: "GRATUITY_ER",
      name: "Gratuity Provision (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "4.81",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "gratuity",
      sortOrder: 8,
    },
    {
      code: "PT",
      name: "Professional Tax",
      type: "DEDUCTION",
      calcMethod: "FIXED",
      amount: "200.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pt",
      sortOrder: 9,
    },
    {
      code: "TDS",
      name: "Tax Deducted at Source",
      type: "TAX",
      calcMethod: "MANUAL",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "tds",
      sortOrder: 10,
    },
    {
      code: "LOP",
      name: "Loss of Pay",
      type: "DEDUCTION",
      calcMethod: "ATTENDANCE_BASED",
      formula: "(basic / days_in_month) * lop_days",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 11,
    },
  ],
};
