import type { PayrollTemplateSeed } from "../../payroll.types";
import { DEFAULT_PAYROLL_TOGGLES } from "../../payroll.types";

export const OT_MULTIPLIER_DEFAULT = "1.50";

export const HOURLY_SEED: PayrollTemplateSeed = {
  key: "HOURLY",
  name: "Hourly / Timesheet",
  description: "Timesheet-driven earnings with overtime multiplier. Ideal for hourly workers billed on actual hours worked.",
  bestFor: "Part-time workers, hourly contract staff, and project-based billing by the hour",
  complexity: "MODERATE",
  badge: null,
  category: "HOURLY",
  isRecommended: false,
  defaultToggles: {
    ...DEFAULT_PAYROLL_TOGGLES,
    pf: true,
    professionalTax: true,
    tds: true,
    timesheets: true,
    overtime: true,
    lopFromAttendance: true,
    bankPayoutFile: true,
    payslipPublishing: true,
    approvalWorkflow: true,
    lockAfterApproval: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Basic Wages",
      type: "EARNING",
      calcMethod: "TIMESHEET_BASED",
      formula: "(basic / days_in_month / 8) * paid_days * 8",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "OT",
      name: "Overtime Pay",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: `(basic / days_in_month / 8) * overtime_hours * ${OT_MULTIPLIER_DEFAULT}`,
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "PF_EMP",
      name: "Provident Fund (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 3,
    },
    {
      code: "PF_ER",
      name: "Provident Fund (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 4,
    },
    {
      code: "PT",
      name: "Professional Tax",
      type: "DEDUCTION",
      calcMethod: "FIXED",
      amount: "200.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pt",
      sortOrder: 5,
    },
    {
      code: "TDS",
      name: "Tax Deducted at Source",
      type: "TAX",
      calcMethod: "MANUAL",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "tds",
      sortOrder: 6,
    },
  ],
};

export const MANUFACTURING_SEED: PayrollTemplateSeed = {
  key: "MANUFACTURING",
  name: "Manufacturing",
  description: "Shift-based and overtime-heavy payroll with full ESI + PF compliance. Covers hourly overtime at 1.5x.",
  bestFor: "Factory workers, plant staff, and blue-collar manufacturing employees",
  complexity: "ADVANCED",
  badge: null,
  category: "MANUFACTURING",
  isRecommended: false,
  defaultToggles: {
    ...DEFAULT_PAYROLL_TOGGLES,
    pf: true,
    esi: true,
    professionalTax: true,
    tds: true,
    overtime: true,
    lopFromAttendance: true,
    leaveSync: true,
    bankPayoutFile: true,
    payslipPublishing: true,
    approvalWorkflow: true,
    lockAfterApproval: true,
    payrollVarianceWarnings: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Basic Wages",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc * 0.40",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "HRA",
      name: "House Rent Allowance",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "50",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "SPECIAL",
      name: "Special Allowance",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc - basic - (basic * 0.50)",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "OT",
      name: "Overtime Pay",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: `(basic / days_in_month / 8) * overtime_hours * ${OT_MULTIPLIER_DEFAULT}`,
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 4,
    },
    {
      code: "ESI_EMP",
      name: "ESI (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "0.75",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "esi",
      sortOrder: 5,
    },
    {
      code: "ESI_ER",
      name: "ESI (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_GROSS",
      percent: "3.25",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "esi",
      sortOrder: 6,
    },
    {
      code: "PF_EMP",
      name: "Provident Fund (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 7,
    },
    {
      code: "PF_ER",
      name: "Provident Fund (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 8,
    },
    {
      code: "PT",
      name: "Professional Tax",
      type: "DEDUCTION",
      calcMethod: "FIXED",
      amount: "200.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pt",
      sortOrder: 9,
    },
    {
      code: "TDS",
      name: "Tax Deducted at Source",
      type: "TAX",
      calcMethod: "MANUAL",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "tds",
      sortOrder: 10,
    },
    {
      code: "LOP",
      name: "Loss of Pay",
      type: "DEDUCTION",
      calcMethod: "ATTENDANCE_BASED",
      formula: "(basic / days_in_month) * lop_days",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 11,
    },
  ],
};
