import type { PayrollTemplateSeed } from "../../payroll.types";
import { DEFAULT_PAYROLL_TOGGLES } from "../../payroll.types";

export const INDIAN_STANDARD_SEED: PayrollTemplateSeed = {
  key: "INDIAN_STANDARD",
  name: "Indian Standard",
  description: "Full statutory compliance for salaried employees in India: PF, PT, ESI-optional, TDS with declaration mode, and LOP-linked attendance.",
  bestFor: "Mid-size Indian companies with salaried workforce and full statutory obligations",
  complexity: "MODERATE",
  badge: "Most Popular",
  category: "INDIAN_STANDARD",
  isRecommended: true,
  defaultToggles: {
    ...DEFAULT_PAYROLL_TOGGLES,
    pf: true,
    professionalTax: true,
    tds: true,
    lopFromAttendance: true,
    leaveSync: true,
    employeeDeclarations: true,
    bankPayoutFile: true,
    payslipPublishing: true,
    approvalWorkflow: true,
    lockAfterApproval: true,
    payrollVarianceWarnings: true,
    requireLockedPayrollInputs: true,
    essAllowReimbursements: false,
    essAllowTaxDeclarations: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Basic Salary",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc * 0.40",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "HRA",
      name: "House Rent Allowance",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "50",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "SPECIAL",
      name: "Special Allowance",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc - basic - (basic * 0.50)",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "PF_EMP",
      name: "Provident Fund (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 4,
    },
    {
      code: "PF_ER",
      name: "Provident Fund (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 5,
    },
    {
      code: "PT",
      name: "Professional Tax",
      type: "DEDUCTION",
      calcMethod: "FIXED",
      amount: "200.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pt",
      sortOrder: 6,
    },
    {
      code: "TDS",
      name: "Tax Deducted at Source",
      type: "TAX",
      calcMethod: "MANUAL",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "tds",
      sortOrder: 7,
    },
    {
      code: "LOP",
      name: "Loss of Pay",
      type: "DEDUCTION",
      calcMethod: "ATTENDANCE_BASED",
      formula: "(basic / days_in_month) * lop_days",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 8,
    },
  ],
};

export const INDIAN_STARTUP_SEED: PayrollTemplateSeed = {
  key: "INDIAN_STARTUP",
  name: "Indian Startup",
  description: "Lean structure for startup employees with flexible reimbursements, bonuses, and simplified PF compliance.",
  bestFor: "Early-stage and growth startups with tech employees, flexible comp, and reimbursement culture",
  complexity: "MODERATE",
  badge: "Startup Friendly",
  category: "INDIAN_STARTUP",
  isRecommended: true,
  defaultToggles: {
    ...DEFAULT_PAYROLL_TOGGLES,
    pf: true,
    professionalTax: true,
    tds: true,
    lopFromAttendance: true,
    reimbursements: true,
    bonuses: true,
    employeeDeclarations: true,
    bankPayoutFile: true,
    payslipPublishing: true,
    approvalWorkflow: true,
    lockAfterApproval: true,
    payrollVarianceWarnings: true,
    essAllowReimbursements: true,
    essAllowTaxDeclarations: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Basic Salary",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc * 0.40",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "HRA",
      name: "House Rent Allowance",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "50",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "SPECIAL",
      name: "Special Allowance",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc - basic - (basic * 0.50)",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "INTERNET",
      name: "Internet Allowance",
      type: "REIMBURSEMENT",
      calcMethod: "FIXED",
      amount: "1000.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 4,
    },
    {
      code: "TRAVEL",
      name: "Travel Allowance",
      type: "REIMBURSEMENT",
      calcMethod: "FIXED",
      amount: "2000.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 5,
    },
    {
      code: "MEAL",
      name: "Meal Allowance",
      type: "REIMBURSEMENT",
      calcMethod: "FIXED",
      amount: "2200.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 6,
    },
    {
      code: "BONUS",
      name: "Performance Bonus",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 7,
    },
    {
      code: "PF_EMP",
      name: "Provident Fund (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 8,
    },
    {
      code: "PF_ER",
      name: "Provident Fund (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 9,
    },
    {
      code: "PT",
      name: "Professional Tax",
      type: "DEDUCTION",
      calcMethod: "FIXED",
      amount: "200.00",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pt",
      sortOrder: 10,
    },
    {
      code: "LOP",
      name: "Loss of Pay",
      type: "DEDUCTION",
      calcMethod: "ATTENDANCE_BASED",
      formula: "(basic / days_in_month) * lop_days",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 11,
    },
  ],
};
