import type { PayrollTemplateSeed } from "../../payroll.types";
import { DEFAULT_PAYROLL_TOGGLES } from "../../payroll.types";

export const SALES_INCENTIVE_SEED: PayrollTemplateSeed = {
  key: "SALES_INCENTIVE",
  name: "Sales Incentive",
  description: "Fixed base plus variable commission and clawback support. Designed for quota-carrying sales roles.",
  bestFor: "Sales teams, BDRs, account executives, and commission-based field staff",
  complexity: "ADVANCED",
  badge: "Sales Optimized",
  category: "SALES_INCENTIVE",
  isRecommended: true,
  defaultToggles: {
    ...DEFAULT_PAYROLL_TOGGLES,
    pf: true,
    professionalTax: true,
    tds: true,
    lopFromAttendance: true,
    salesIncentives: true,
    incentives: true,
    manualAdjustments: true,
    employeeDeclarations: true,
    bankPayoutFile: true,
    payslipPublishing: true,
    approvalWorkflow: true,
    lockAfterApproval: true,
    payrollVarianceWarnings: true,
    essAllowTaxDeclarations: true,
  },
  defaultComponents: [
    {
      code: "BASIC",
      name: "Basic Salary",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc * 0.40",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 1,
    },
    {
      code: "HRA",
      name: "House Rent Allowance",
      type: "EARNING",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "50",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 2,
    },
    {
      code: "SPECIAL",
      name: "Special Allowance",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "ctc - basic - (basic * 0.50)",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: false,
      sortOrder: 3,
    },
    {
      code: "INCENTIVE",
      name: "Variable Incentive",
      type: "EARNING",
      calcMethod: "MANUAL",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 4,
    },
    {
      code: "COMMISSION",
      name: "Sales Commission",
      type: "EARNING",
      calcMethod: "FORMULA",
      formula: "incentive_amount * 0.05",
      taxable: true,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 5,
    },
    {
      code: "PF_EMP",
      name: "Provident Fund (Employee)",
      type: "DEDUCTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 6,
    },
    {
      code: "PF_ER",
      name: "Provident Fund (Employer)",
      type: "EMPLOYER_CONTRIBUTION",
      calcMethod: "PERCENT_OF_BASIC",
      percent: "12",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: true,
      isStatutory: true,
      statutoryKey: "pf",
      sortOrder: 7,
    },
    {
      code: "TDS",
      name: "Tax Deducted at Source",
      type: "TAX",
      calcMethod: "MANUAL",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: true,
      statutoryKey: "tds",
      sortOrder: 8,
    },
    {
      code: "CLAWBACK",
      name: "Incentive Clawback",
      type: "ADJUSTMENT",
      calcMethod: "MANUAL",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 9,
    },
    {
      code: "LOP",
      name: "Loss of Pay",
      type: "DEDUCTION",
      calcMethod: "ATTENDANCE_BASED",
      formula: "(basic / days_in_month) * lop_days",
      taxable: false,
      showOnPayslip: true,
      includeInCtc: false,
      isStatutory: false,
      sortOrder: 10,
    },
  ],
};
